import { Star, Shield, TrendingUp, TrendingDown, Activity, BarChart3 } from "lucide-react";
import type { LangKey } from "@/contexts/LanguageContext";
import type { StockNewsItem } from "@/hooks/useStockData";
import ProbabilityGauge from "./ProbabilityGauge";
import PeerComparisonTable from "./PeerComparisonTable";
import RecommendationSidebar from "./RecommendationSidebar";
import AnalystConfidenceGauge from "./AnalystConfidenceGauge";
import PriceVsIndexChart from "./PriceVsIndexChart";
import MarketDepthSection from "./MarketDepthSection";
import CompanyProfile from "./CompanyProfile";
import NewsSection from "./NewsSection";
import dragonLogo from "@/assets/dragon-logo.png";

/* ── Trilingual labels ───────────────────────── */
const t = {
  en: {
    reportTitle: "AI Stock Probability Report",
    subject: "Subject",
    dateLabel: "Date of Analysis",
    status: "Cognitive Engagement Exercise",
    marketData: "Market Data",
    livePrice: "Live Price",
    weekHigh: "52-Week High",
    weekLow: "52-Week Low",
    volume: "Volume",
    techIndicators: "Technical Indicators",
    rsiIndicator: "RSI Indicator",
    macdIndicator: "MACD Indicator",
    macdLine: "MACD Line",
    signalLine: "Signal Line",
    histogram: "Histogram",
    aiProbPricing: "AI Probability Pricing",
    aiProbability: "AI Probability",
    buyTarget: "Buy Target",
    sellTarget: "Sell Target",
    decisionMatrix: "Decision Matrix",
    buy: "Buy",
    hold: "Hold",
    sell: "Sell",
    aiRecommendation: "AI Recommendation",
    deepDive: "AI Deep-Dive Analysis",
    bullCase: "The Bull Case (Positive Drivers)",
    bearCase: "The Bear Case (Risk Factors)",
    financialSnapshot: "Financial Snapshot",
    healthScoreTitle: "Financial Health Score",
    healthExcellent: "Excellent",
    healthGood: "Good",
    healthFair: "Fair",
    healthWeak: "Weak",
    healthAdviceExcellent: "Strong fundamentals across all dimensions — suitable for long-term holding with high conviction.",
    healthAdviceGood: "Solid overall health with minor areas to monitor — a dependable choice for most portfolios.",
    healthAdviceFair: "Mixed financial signals — conduct deeper research before committing significant capital.",
    healthAdviceWeak: "Multiple financial concerns detected — higher risk, only suitable for speculative positions.",
    debtLabel: "Debt-to-Equity",
    cashFlowLabel: "Cash Flow Trend",
    cashFlowUp: "Increasing",
    cashFlowStable: "Stable",
    cashFlowDown: "Declining",
    dividendYield: "Dividend Yield",
    volatilityIndex: "Volatility Index",
    strategicAdvice: "Strategic Advice",
    conservative: "Conservative Investor:",
    value: "Value Investor:",
    sentiment: "Algorithmic Sentiment",
    trendStrength: "Trend Strength",
    addWatchlist: "Add to Watchlist",
    addedWatchlist: "In Watchlist",
    selfDecision: "Principle of Self-Decision",
    finalDisclaimer: "This report is generated by a mathematical AI model for educational and mental stimulation purposes only. The founder holds No Professional or Gambling Licenses. This is not financial advice.",
    confidential: "CONFIDENTIAL — For Intended Recipient Only",
    executiveThesisTitle: "Executive Investment Thesis",
    sectorLabel: "Sector",
    industryLabel: "Industry",
    keyMultiples: "Key Financial Multiples",
    marketCap: "Market Cap",
    peRatio: "P/E Ratio",
    roeLabel: "ROE",
    riskTitle: "Investment Risk Assessment",
    riskTierLabel: "Risk Tier",
    riskTierConservative: "Conservative",
    riskTierGrowth: "Growth",
    riskTierHighRisk: "High Risk",
    riskTierAdviceConservative: "This stock has low volatility — suitable as a core holding with stable returns.",
    riskTierAdviceGrowth: "This stock has moderate volatility — consider limiting to 10-15% of your total portfolio.",
    riskTierAdviceHighRisk: "This stock has high volatility — consider limiting to no more than 5% of your total portfolio.",
    riskMarket: "Market Risk",
    riskMarketDesc: "Risks from broad market movements that affect all stocks",
    riskCompany: "Company-Specific Risk",
    riskCompanyDesc: "Risks unique to this particular company or its sector",
    riskModel: "AI Model Limitations",
    riskModelDesc: "Limitations of the mathematical model used in this analysis",
    riskSelfDecision: "Principle of Self-Decision",
    riskSelfDecisionBody: "AI probability scores are mathematical calculations based on historical data — they are NOT guarantees of profit or loss. Always make your own informed decision and consult a licensed financial advisor before investing.",
     footnote1: "This document is produced by DragonGPAi.com for informational purposes only and does not constitute an offer, solicitation, or recommendation to buy or sell any security.",
     footnote2: "The analysis herein is based on mathematical probability models and publicly available market data. DragonGPAi.com holds no professional financial advisory or gambling licenses.",
    footnote3: "Past performance is not indicative of future results. All investments carry risk, including the possible loss of principal.",
    priceVsIndex: "12-Month Price vs. Index Performance",
    reportFooter: "Report created by DragonGPAi.com, powered by Gemini",
  },
  tc: {
    reportTitle: "AI 股票概率報告",
    subject: "標的",
    dateLabel: "分析日期",
    status: "認知參與練習",
    marketData: "市場數據",
    livePrice: "現價",
    weekHigh: "52週高",
    weekLow: "52週低",
    volume: "成交量",
    techIndicators: "技術指標",
    rsiIndicator: "RSI 指標",
    macdIndicator: "MACD 指標",
    macdLine: "MACD 線",
    signalLine: "信號線",
    histogram: "柱狀圖",
    aiProbPricing: "AI 概率定價",
    aiProbability: "AI 概率",
    buyTarget: "買入目標",
    sellTarget: "賣出目標",
    decisionMatrix: "決策矩陣",
    buy: "買入",
    hold: "持有",
    sell: "賣出",
    aiRecommendation: "AI 建議",
    deepDive: "AI 深度分析",
    bullCase: "牛市論點（正面驅動因素）",
    bearCase: "熊市論點（風險因素）",
    financialSnapshot: "財務概況",
    healthScoreTitle: "財務健康綜合評分",
    healthExcellent: "優秀",
    healthGood: "良好",
    healthFair: "普通",
    healthWeak: "偏弱",
    healthAdviceExcellent: "各維度基本面強勁——適合高信心長期持有。",
    healthAdviceGood: "整體健康穩健，少數方面需關注——對大多數投資組合是可靠選擇。",
    healthAdviceFair: "財務信號喜憂參半——投入大量資金前需做更深入研究。",
    healthAdviceWeak: "偵測到多項財務隱憂——風險較高，僅適合投機性持倉。",
    debtLabel: "負債權益比",
    cashFlowLabel: "現金流趨勢",
    cashFlowUp: "上升",
    cashFlowStable: "穩定",
    cashFlowDown: "下降",
    dividendYield: "股息收益率",
    volatilityIndex: "波動指數",
    strategicAdvice: "策略建議",
    conservative: "穩健型投資者：",
    value: "價值型投資者：",
    sentiment: "算法情緒",
    trendStrength: "趨勢強度",
    addWatchlist: "加入自選",
    addedWatchlist: "已加入自選",
    selfDecision: "自主決策原則",
    finalDisclaimer: "本報告由數學 AI 模型生成，僅供教育和認知刺激之用。創辦人不持有任何專業或博弈牌照。此非財務建議。",
    confidential: "機密 — 僅限預期收件人",
    executiveThesisTitle: "執行投資論點",
    sectorLabel: "板塊",
    industryLabel: "行業",
    keyMultiples: "主要財務指標",
    marketCap: "市值",
    peRatio: "市盈率",
    roeLabel: "股本回報率",
    riskTitle: "投資風險評估",
    riskTierLabel: "風險等級",
    riskTierConservative: "穩健型",
    riskTierGrowth: "成長型",
    riskTierHighRisk: "高風險型",
    riskTierAdviceConservative: "本標的波動較低，適合作為核心持倉，回報相對穩定。",
    riskTierAdviceGrowth: "本標的波動適中，建議佔總倉位不超過 10-15%。",
    riskTierAdviceHighRisk: "本標的波動較大，建議佔總倉位不超過 5%。",
    riskMarket: "市場風險",
    riskMarketDesc: "影響所有股票的大盤波動風險",
    riskCompany: "個股風險",
    riskCompanyDesc: "此公司或其板塊特有的風險",
    riskModel: "AI 模型限制",
    riskModelDesc: "本分析所用數學模型的局限性",
    riskSelfDecision: "自主決策原則",
    riskSelfDecisionBody: "AI 概率評分是基於歷史數據的數學推算——並非獲利或虧損的保證。請務必自行做出明智決定，並在投資前諮詢持牌財務顧問。",
     footnote1: "本文件由 DragonGPAi.com 製作，僅供參考之用，不構成任何買賣證券的要約、招攬或建議。",
     footnote2: "本分析基於數學概率模型及公開市場數據。DragonGPAi.com 不持有任何專業財務顧問或博弈牌照。",
    footnote3: "過往表現並非未來表現的指標。所有投資均存在風險，包括可能損失本金。",
    priceVsIndex: "12個月股價 vs 指數表現",
    reportFooter: "報告由 DragonGPAi.com 製作，由 Gemini 提供支持",
  },
  sc: {
    reportTitle: "AI 股票概率报告",
    subject: "标的",
    dateLabel: "分析日期",
    status: "认知参与练习",
    marketData: "市场数据",
    livePrice: "现价",
    weekHigh: "52周高",
    weekLow: "52周低",
    volume: "成交量",
    techIndicators: "技术指标",
    rsiIndicator: "RSI 指标",
    macdIndicator: "MACD 指标",
    macdLine: "MACD 线",
    signalLine: "信号线",
    histogram: "柱状图",
    aiProbPricing: "AI 概率定价",
    aiProbability: "AI 概率",
    buyTarget: "买入目标",
    sellTarget: "卖出目标",
    decisionMatrix: "决策矩阵",
    buy: "买入",
    hold: "持有",
    sell: "卖出",
    aiRecommendation: "AI 建议",
    deepDive: "AI 深度分析",
    bullCase: "牛市论点（正面驱动因素）",
    bearCase: "熊市论点（风险因素）",
    financialSnapshot: "财务概况",
    healthScoreTitle: "财务健康综合评分",
    healthExcellent: "优秀",
    healthGood: "良好",
    healthFair: "普通",
    healthWeak: "偏弱",
    healthAdviceExcellent: "各维度基本面强劲——适合高信心长期持有。",
    healthAdviceGood: "整体健康稳健，少数方面需关注——对大多数投资组合是可靠选择。",
    healthAdviceFair: "财务信号喜忧参半——投入大量资金前需做更深入研究。",
    healthAdviceWeak: "侦测到多项财务隐忧——风险较高，仅适合投机性持仓。",
    debtLabel: "负债权益比",
    cashFlowLabel: "现金流趋势",
    cashFlowUp: "上升",
    cashFlowStable: "稳定",
    cashFlowDown: "下降",
    dividendYield: "股息收益率",
    volatilityIndex: "波动指数",
    strategicAdvice: "策略建议",
    conservative: "稳健型投资者：",
    value: "价值型投资者：",
    sentiment: "算法情绪",
    trendStrength: "趋势强度",
    addWatchlist: "加入自选",
    addedWatchlist: "已加入自选",
    selfDecision: "自主决策原则",
    finalDisclaimer: "本报告由数学 AI 模型生成，仅供教育和认知刺激之用。创办人不持有任何专业或博弈牌照。此非财务建议。",
    confidential: "机密 — 仅限预期收件人",
    executiveThesisTitle: "执行投资论点",
    sectorLabel: "板块",
    industryLabel: "行业",
    keyMultiples: "主要财务指标",
    marketCap: "市值",
    peRatio: "市盈率",
    roeLabel: "股本回报率",
    riskTitle: "投资风险评估",
    riskTierLabel: "风险等级",
    riskTierConservative: "稳健型",
    riskTierGrowth: "成长型",
    riskTierHighRisk: "高风险型",
    riskTierAdviceConservative: "本标的波动较低，适合作为核心持仓，回报相对稳定。",
    riskTierAdviceGrowth: "本标的波动适中，建议占总仓位不超过 10-15%。",
    riskTierAdviceHighRisk: "本标的波动较大，建议占总仓位不超过 5%。",
    riskMarket: "市场风险",
    riskMarketDesc: "影响所有股票的大盘波动风险",
    riskCompany: "个股风险",
    riskCompanyDesc: "此公司或其板块特有的风险",
    riskModel: "AI 模型限制",
    riskModelDesc: "本分析所用数学模型的局限性",
    riskSelfDecision: "自主决策原则",
    riskSelfDecisionBody: "AI 概率评分是基于历史数据的数学推算——并非获利或亏损的保证。请务必自行做出明智决定，并在投资前咨询持牌财务顾问。",
     footnote1: "本文件由 DragonGPAi.com 制作，仅供参考之用，不构成任何买卖证券的要约、招揽或建议。",
     footnote2: "本分析基于数学概率模型及公开市场数据。DragonGPAi.com 不持有任何专业财务顾问或博弈牌照。",
    footnote3: "过往表现并非未来表现的指标。所有投资均存在风险，包括可能损失本金。",
    priceVsIndex: "12个月股价 vs 指数表现",
    reportFooter: "报告由 DragonGPAi.com 制作，由 Gemini 提供支持",
  },
};

export interface ReportData {
  ticker: string;
  companyName?: string;
  date: string;
  price: string;
  priceChange: string;
  priceUp: boolean;
  weekHigh: string;
  weekLow: string;
  volume: string;
  rsi: number;
  rsiStatus: string;
  macdLine: string;
  signalLine: string;
  histogram: string;
  macdStatus: string;
  probability: number;
  buyTarget: string;
  sellTarget: string;
  buyPct: number;
  holdPct: number;
  sellPct: number;
  recommendation: string;
  bullPoints: string[];
  bearPoints: string[];
  dividendYield: string;
  volatility: string;
  conservativeAdvice: string;
  valueAdvice: string;
  sentimentScore: number;
  trendStrength: number;
  /* Institutional fields */
  executiveThesis: string;
  sector: string;
  industry: string;
  marketCap: string;
  peRatio: string;
  roe: string;
  riskAssessment: {
    market: string[];
    company: string[];
    model: string[];
  };
  financialHealthScore: number;
  debtToEquity: number;
  cashFlowTrend: "up" | "stable" | "down";
  /* New fields */
  bid: number;
  ask: number;
  bidSize: number;
  askSize: number;
  dayRange: string;
  marketState: string;
  currencySymbol: string;
  previousCloseVolume: string;
  companyDescription: string;
  news: StockNewsItem[];
  upcomingDividend?: { amount: string; exDate: string } | null;
}

/* ── Section helpers ──────────────────────────── */
const Section = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => (
  <div className={`py-3 ${className}`} style={{ pageBreakInside: "avoid", breakInside: "avoid" }}>
    {children}
  </div>
);

const SectionTitle = ({ children }: { children: React.ReactNode }) => (
  <h3
    className="text-[13px] font-bold tracking-wide uppercase pb-1.5 mb-2"
    style={{
      fontFamily: "'Playfair Display', Georgia, 'Times New Roman', serif",
      color: "#1e293b",
      borderBottom: "2px solid #1e293b",
    }}
  >
    {children}
  </h3>
);

interface Props {
  report: ReportData;
  lang: LangKey;
  inWatchlist: boolean;
  onAddWatchlist: () => void;
}

const StockReport = ({ report, lang, inWatchlist, onAddWatchlist }: Props) => {
  const l = t[lang];
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  return (
    <div
      id="stock-report"
      className="animate-fade-in"
      style={{
        fontFamily: "'Inter', 'Helvetica Neue', Arial, sans-serif",
        fontSize: "10pt",
        lineHeight: 1.5,
        color: "#334155",
        background: "#f1f3f5",
        padding: "20px 12px",
        borderRadius: "6px",
      }}
    >
      {/* ══ Fonts + Print styles ═════════════════ */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700;900&family=Inter:wght@400;500;600;700&display=swap');

        @media print {
          * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
          body { background: #fff !important; color: #000 !important; margin: 0 !important; padding: 0 !important; zoom: 0.9; }

          /* Hide all UI chrome */
          header, footer, nav,
          .no-print, button,
          [data-no-print],
          [class*="lang-toggle"],
          [class*="top-up"],
          [class*="credits-badge"] { display: none !important; }

          /* Report fills full page width */
          #stock-report {
            max-width: 100% !important;
            width: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
            background: #fff !important;
            box-shadow: none !important;
            border-radius: 0 !important;
            font-size: 7.5pt !important;
            line-height: 1.3 !important;
          }
          .report-container {
            max-width: 100% !important;
            width: 100% !important;
            box-shadow: none !important;
            border: none !important;
            border-radius: 0 !important;
          }

          /* Compact all sections */
          .report-section { padding-top: 2px !important; padding-bottom: 2px !important; }
          .report-section h3 { font-size: 9px !important; margin-bottom: 2px !important; padding-bottom: 1px !important; }

          /* Compact padding */
          .report-px { padding-left: 8px !important; padding-right: 8px !important; }
          .report-py { padding-top: 2px !important; padding-bottom: 2px !important; }

          /* Force compact grid gaps */
          .report-section .grid { gap: 3px !important; }
          .report-section .space-y-4 > * + * { margin-top: 3px !important; }
          .report-section .space-y-3 > * + * { margin-top: 2px !important; }
          .report-section .space-y-2 > * + * { margin-top: 1px !important; }

          /* Compact cards */
          .report-section .p-4 { padding: 3px 5px !important; }
          .report-section .p-3 { padding: 2px 4px !important; }
          .report-section .p-5 { padding: 3px 6px !important; }
          .report-section .p-2 { padding: 2px 4px !important; }

          /* Smaller text in print */
          .report-section .text-\\[12px\\] { font-size: 8px !important; }
          .report-section .text-\\[11px\\] { font-size: 7.5px !important; }
          .report-section .text-\\[10px\\] { font-size: 7px !important; }
          .report-section .text-\\[9px\\] { font-size: 6.5px !important; }
          .report-section .text-\\[8px\\] { font-size: 6px !important; }
          .report-section .text-\\[15px\\] { font-size: 9px !important; }
          .report-section .text-\\[17px\\] { font-size: 10px !important; }
          .report-section .text-\\[13px\\] { font-size: 8px !important; }
          .report-section .text-\\[14px\\] { font-size: 9px !important; }

          .stock-chart-container { max-height: 140px !important; overflow: hidden !important; }
          .stock-chart-container .recharts-responsive-container { max-height: 130px !important; }

          /* 2/3-column grids for print */
          .print-2col { display: grid !important; grid-template-columns: 1fr 1fr !important; gap: 3px !important; }
          .print-3col { display: grid !important; grid-template-columns: 1fr 1fr 1fr !important; gap: 3px !important; }

          /* Prevent splitting sections */
          .report-section,
          .report-section table,
          .grid { page-break-inside: avoid; break-inside: avoid; }

          .report-page-break { page-break-before: always; break-before: page; }
          .print-only { display: flex !important; }

          /* Print header compact */
          .print-header-compact { padding: 4px 8px !important; }
          .print-header-compact h2 { font-size: 11px !important; }
          .print-header-compact img { height: 16px !important; width: 16px !important; }

          /* Page footer on every page */
          .report-page-footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 3px 12mm;
            font-size: 6.5px;
            color: #94a3b8;
            border-top: 1px solid #e5e7eb;
            background: white;
            display: flex !important;
            justify-content: space-between;
            align-items: center;
          }

          /* Eliminate divide-y borders extra spacing */
          .divide-y > * + * { border-top-width: 1px !important; }

          @page {
            size: A4 portrait;
            margin: 8mm 10mm 14mm 10mm;
          }
        }
        @media screen {
          .print-only { display: none !important; }
          .report-page-footer { display: none !important; }
          .stock-chart-container { max-height: 220px; overflow: hidden; }
          .print-3col { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; }
        }
      `}</style>

      {/* ══ Print-only page footer (every page) ═══ */}
      <div className="report-page-footer">
        <span>{l.reportFooter} — {today}</span>
        <span>{l.confidential}</span>
      </div>

      {/* ══ Running document header (always visible) ═══ */}
      <div
        className="flex items-center justify-between mx-auto mb-2 px-1"
        style={{ maxWidth: "210mm" }}
      >
        <div className="flex items-center gap-2">
           <img src={dragonLogo} alt="DragonGPAi.com" className="h-4 w-4" />
           <span style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: "11px", fontWeight: 700, color: "#1e293b" }}>
             DragonGPAi.com
           </span>
        </div>
        <div className="flex items-center gap-3" style={{ fontSize: "9px", color: "#64748b" }}>
          <span>{report.date}</span>
          <span style={{ color: "#94a3b8", letterSpacing: "0.08em", textTransform: "uppercase", fontSize: "8px", fontWeight: 600 }}>
            {l.confidential}
          </span>
        </div>
      </div>

      {/* ══ Report container (A4 width) ═════════ */}
      <div
        className="report-container mx-auto bg-white overflow-hidden relative"
        style={{
          maxWidth: "210mm",
          border: "1px solid #d1d5db",
          borderRadius: "2px",
          boxShadow: "0 4px 32px rgba(0,0,0,0.12), 0 1px 4px rgba(0,0,0,0.08)",
        }}
      >
        {/* Watermark */}
        <div
          className="absolute inset-0 pointer-events-none flex items-center justify-center"
          style={{ zIndex: 0 }}
        >
          <img
            src={dragonLogo}
            alt=""
            className="select-none"
            style={{ width: "280px", height: "280px", opacity: 0.03, filter: "grayscale(100%)" }}
          />
        </div>

        {/* ── Cover header — "L" layout: Logo left, info right ── */}
        <div style={{ background: "#1e293b" }} className="px-3 py-1.5 print-header-compact">
          {/* Row 1: Logo + Ticker/Price/Industry */}
          <div className="flex items-center gap-2">
            <img src={dragonLogo} alt="DragonGPAi.com" className="h-6 w-6 rounded shrink-0" />
            <div className="flex items-center gap-2 flex-wrap flex-1 min-w-0">
              <span className="text-[13px] font-bold text-white" style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
                {report.ticker}
              </span>
              {report.companyName && (
                <span className="text-[9px]" style={{ color: "rgba(255,255,255,0.6)" }}>— {report.companyName}</span>
              )}
              <span className="text-[13px] font-bold" style={{ color: report.priceUp ? "#86efac" : "#fca5a5" }}>
                {report.price}
              </span>
              <span className="text-[8px] font-semibold px-1 py-0.5 rounded" style={{ background: report.priceUp ? "rgba(34,197,94,0.2)" : "rgba(239,68,68,0.2)", color: report.priceUp ? "#86efac" : "#fca5a5" }}>
                {report.priceChange}
              </span>
              <span className="text-[7px] px-1 py-0.5 rounded" style={{ background: "rgba(255,255,255,0.1)", color: "rgba(255,255,255,0.5)" }}>{report.sector} · {report.industry}</span>
              <span
                className="text-[7px] font-bold px-1 py-0.5 rounded-full"
                style={{
                  background: report.marketState === "REGULAR" ? "rgba(34,197,94,0.2)" : report.marketState === "PRE" || report.marketState === "POST" ? "rgba(245,158,11,0.2)" : "rgba(239,68,68,0.2)",
                  color: report.marketState === "REGULAR" ? "#86efac" : report.marketState === "PRE" || report.marketState === "POST" ? "#fcd34d" : "#fca5a5",
                }}
              >
                {report.marketState === "REGULAR" ? (lang === "en" ? "Market Open" : "交易中")
                  : report.marketState === "PRE" ? (lang === "en" ? "Pre-Market" : lang === "tc" ? "盤前" : "盘前")
                  : report.marketState === "POST" ? (lang === "en" ? "After Hours" : lang === "tc" ? "盤後" : "盘后")
                  : (lang === "en" ? "Market Closed" : "已收市")}
              </span>
            </div>
            <div className="text-right shrink-0 text-[8px]" style={{ color: "rgba(255,255,255,0.6)" }}>
              <p>{report.date}</p>
              <span className="text-[6px] py-0.5 px-1 rounded" style={{ background: "rgba(255,255,255,0.08)", color: "rgba(255,255,255,0.4)" }}>{l.status}</span>
            </div>
          </div>
        </div>

        {/* ── Action bar (watchlist + recommendation — screen only most compact) ── */}
        <div className="px-4 py-2 flex items-center justify-between flex-wrap gap-2 report-section" style={{ background: "#f8fafc", borderBottom: "1px solid #e5e7eb" }}>
          <button
            onClick={onAddWatchlist}
            disabled={inWatchlist}
            className="no-print inline-flex items-center gap-1 rounded px-2 py-1 text-[10px] font-semibold transition-colors"
            style={{
              border: inWatchlist ? "1px solid rgba(245,158,11,0.3)" : "1px solid #e5e7eb",
              background: inWatchlist ? "#fffbeb" : "transparent",
              color: inWatchlist ? "#d97706" : "#64748b",
              cursor: inWatchlist ? "default" : "pointer",
            }}
          >
            <Star size={10} className={inWatchlist ? "fill-[#d97706]" : ""} />
            {inWatchlist ? l.addedWatchlist : l.addWatchlist}
          </button>
          <div className="w-full sm:w-auto sm:max-w-[220px]">
            <RecommendationSidebar
              lang={lang}
              currentPrice={report.price}
              targetPrice={report.buyTarget}
              buyPct={report.buyPct}
              holdPct={report.holdPct}
              sellPct={report.sellPct}
            />
          </div>
        </div>

        {/* ── 2-Column Executive Summary Grid (Desktop/Print) ── */}
        <div className="px-5 py-3 grid grid-cols-1 lg:grid-cols-2 gap-4 print-2col" style={{ borderBottom: "1px solid #e5e7eb" }}>
          {/* Left Column: Investment Thesis + Confidence */}
          <div className="report-section">
            <SectionTitle>{l.executiveThesisTitle}</SectionTitle>
            {/* Bulletized thesis: split by sentence or use AI-generated text */}
            {(() => {
              // Split thesis into sentences and create bullet points
              const sentences = report.executiveThesis
                .split(/(?<=[.!?])\s+/)
                .filter((s) => s.trim().length > 10);
              const bulletLabels = lang === "en"
                ? ["Technical Momentum", "Valuation Context", "Upside Conviction", "Key Catalyst"]
                : lang === "tc"
                  ? ["技術動能", "估值背景", "上升信心", "關鍵催化"]
                  : ["技术动能", "估值背景", "上升信心", "关键催化"];
              const bullets = sentences.slice(0, 4);
              return (
                <ul className="space-y-1.5">
                  {bullets.map((b, i) => (
                    <li key={i} className="flex items-start gap-1.5 text-[10px] leading-snug" style={{ color: "#334155" }}>
                      <span className="w-1.5 h-1.5 rounded-full mt-[5px] shrink-0" style={{ background: "#b45309" }} />
                      <span>
                        <strong style={{ color: "#1e293b" }}>{bulletLabels[i % bulletLabels.length]}:</strong>{" "}
                        {b.trim()}
                      </span>
                    </li>
                  ))}
                </ul>
              );
            })()}
            <div className="mt-2">
              <AnalystConfidenceGauge value={report.sentimentScore} lang={lang} />
            </div>
          </div>

          {/* Right Column: Key Multiples + Market Data */}
          <div className="report-section">
            <SectionTitle>{l.keyMultiples}</SectionTitle>
            <div className="grid grid-cols-2 gap-2">
              {[
                { label: l.marketCap, value: report.marketCap },
                { label: l.peRatio, value: report.peRatio },
                { label: l.dividendYield, value: report.dividendYield + (report.upcomingDividend ? ` ⬆` : "") },
                { label: l.roeLabel, value: report.roe },
              ].map((item) => (
                <div
                  key={item.label}
                  className="p-2 text-center rounded"
                  style={{ border: "1px solid #e5e7eb", background: "#f8fafc" }}
                >
                  <p className="text-[9px] uppercase tracking-[0.1em]" style={{ color: "#94a3b8" }}>{item.label}</p>
                  <p className="text-[13px] font-bold mt-0.5" style={{ color: "#1e293b" }}>{item.value}</p>
                </div>
              ))}
            </div>
            {/* Upcoming Dividend Banner */}
            {report.upcomingDividend && (
              <div className="mt-2 p-2 rounded" style={{ background: "#ecfdf5", border: "1px solid #86efac" }}>
                <p className="text-[10px] font-semibold" style={{ color: "#166534" }}>
                  {lang === "en"
                    ? `📣 Upcoming Dividend: ${report.upcomingDividend.amount} per share (Ex-date: ${report.upcomingDividend.exDate})`
                    : lang === "tc"
                      ? `📣 即將派息：每股 ${report.upcomingDividend.amount}（除息日：${report.upcomingDividend.exDate}）`
                      : `📣 即将派息：每股 ${report.upcomingDividend.amount}（除息日：${report.upcomingDividend.exDate}）`}
                </p>
              </div>
            )}
            {/* Market Data inline */}
            <div className="grid grid-cols-2 gap-2 mt-2">
              {[
                { label: l.weekHigh, value: report.weekHigh, color: "#15803d" },
                { label: l.weekLow, value: report.weekLow, color: "#dc2626" },
                { label: l.volume, value: report.volume, color: "#b45309" },
                { label: l.livePrice, value: report.price, color: "#1e293b" },
              ].map((item) => (
                <div
                  key={item.label}
                  className="p-1.5 text-center rounded"
                  style={{ border: "1px solid #e5e7eb", background: "#f8fafc" }}
                >
                  <p className="text-[8px] uppercase tracking-[0.1em]" style={{ color: "#94a3b8" }}>{item.label}</p>
                  <p className="text-[12px] font-bold" style={{ color: item.color }}>{item.value}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ── Bull vs. Bear Summary ──────────────── */}
        <div className="px-5 py-2 report-section" style={{ borderBottom: "1px solid #e5e7eb", pageBreakInside: "avoid", breakInside: "avoid" }}>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 print-2col">
            {/* Bull Case */}
            <div className="rounded p-2.5" style={{ background: "#f0fdf4", border: "1px solid #86efac" }}>
              <h4 className="text-[11px] font-bold mb-1.5" style={{ color: "#15803d" }}>
                🐂 {l.bullCase}
              </h4>
              <ul className="space-y-1">
                {report.bullPoints.slice(0, 3).map((pt, i) => (
                  <li key={i} className="flex items-start gap-1.5 text-[9px] leading-snug" style={{ color: "#334155" }}>
                    <span className="mt-[4px] shrink-0 w-1 h-1 rounded-full" style={{ background: "#15803d" }} />
                    <span>{pt}</span>
                  </li>
                ))}
              </ul>
            </div>
            {/* Bear Case */}
            <div className="rounded p-2.5" style={{ background: "#fef2f2", border: "1px solid #fca5a5" }}>
              <h4 className="text-[11px] font-bold mb-1.5" style={{ color: "#dc2626" }}>
                🐻 {l.bearCase}
              </h4>
              <ul className="space-y-1">
                {report.bearPoints.slice(0, 3).map((pt, i) => (
                  <li key={i} className="flex items-start gap-1.5 text-[9px] leading-snug" style={{ color: "#334155" }}>
                    <span className="mt-[4px] shrink-0 w-1 h-1 rounded-full" style={{ background: "#dc2626" }} />
                    <span>{pt}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* ── Content sections ───────────────────── */}
        <div className="px-5 divide-y" style={{ borderColor: "#e5e7eb" }}>

          {/* Market Depth */}
          <MarketDepthSection
            lang={lang}
            bid={report.bid}
            ask={report.ask}
            bidSize={report.bidSize}
            askSize={report.askSize}
            dayRange={report.dayRange}
            volume={report.volume}
            marketState={report.marketState}
            currencySymbol={report.currencySymbol}
            previousCloseVolume={report.previousCloseVolume}
          />

          {/* Company Profile */}
          <CompanyProfile
            lang={lang}
            companyName={report.companyName || report.ticker}
            description={report.companyDescription}
            sector={report.sector}
            industry={report.industry}
          />

          {/* Technical Indicators — compact 2-col */}
          <Section className="report-section">
            <SectionTitle>{l.techIndicators}</SectionTitle>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="text-center space-y-1">
                <p className="text-[9px] uppercase tracking-[0.1em]" style={{ color: "#94a3b8" }}>{l.rsiIndicator}</p>
                <div className="relative flex justify-center">
                  <ProbabilityGauge value={report.rsi} size={100} label={report.rsiStatus} />
                </div>
              </div>
              <div className="space-y-2">
                <p className="text-[9px] uppercase tracking-[0.1em]" style={{ color: "#94a3b8" }}>{l.macdIndicator}</p>
                <div className="grid grid-cols-3 gap-2 text-center">
                  {[
                    { label: l.macdLine, value: report.macdLine },
                    { label: l.signalLine, value: report.signalLine },
                    { label: l.histogram, value: report.histogram },
                  ].map((m) => (
                    <div key={m.label} className="p-1.5 rounded" style={{ border: "1px solid #e5e7eb", background: "#f8fafc" }}>
                      <p className="text-[8px]" style={{ color: "#94a3b8" }}>{m.label}</p>
                      <p className="text-[11px] font-bold mt-0.5" style={{ color: "#1e293b" }}>{m.value}</p>
                    </div>
                  ))}
                </div>
                <div className="flex justify-center">
                  <span
                    className="text-[10px] font-semibold px-2 py-0.5 rounded"
                    style={{ border: "1px solid rgba(21,128,61,0.25)", color: "#15803d", background: "#dcfce7" }}
                  >
                    {report.macdStatus}
                  </span>
                </div>
              </div>
            </div>
          </Section>

          {/* AI Probability + Decision Matrix side-by-side */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 py-3 print-2col report-section" style={{ pageBreakInside: "avoid" }}>
            {/* AI Probability */}
            <div>
              <SectionTitle>{l.aiProbPricing}</SectionTitle>
              <div className="flex items-center justify-between mb-1">
                <span className="text-[10px]" style={{ color: "#64748b" }}>{l.aiProbability}</span>
                <span className="text-[15px] font-bold" style={{ color: "#1e293b" }}>{report.probability}%</span>
              </div>
              <div className="w-full h-[8px] rounded-full overflow-hidden mb-3" style={{ background: "#e2e8f0" }}>
                <div
                  className="h-full rounded-full transition-all duration-700"
                  style={{ width: `${report.probability}%`, background: "linear-gradient(90deg, #b45309, #15803d)" }}
                />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div className="p-2 text-center rounded" style={{ border: "1px solid rgba(21,128,61,0.2)", background: "#f0fdf4" }}>
                  <p className="text-[9px] uppercase tracking-[0.1em]" style={{ color: "#64748b" }}>{l.buyTarget}</p>
                  <p className="text-[15px] font-bold mt-0.5" style={{ color: "#15803d" }}>{report.buyTarget}</p>
                </div>
                <div className="p-2 text-center rounded" style={{ border: "1px solid rgba(220,38,38,0.2)", background: "#fef2f2" }}>
                  <p className="text-[9px] uppercase tracking-[0.1em]" style={{ color: "#64748b" }}>{l.sellTarget}</p>
                  <p className="text-[15px] font-bold mt-0.5" style={{ color: "#dc2626" }}>{report.sellTarget}</p>
                </div>
              </div>
            </div>
            {/* Decision Matrix + Sentiment */}
            <div>
              <SectionTitle>{l.decisionMatrix}</SectionTitle>
              <div className="w-full h-[24px] rounded overflow-hidden flex text-[10px] font-bold text-white">
                <div className="flex items-center justify-center" style={{ width: `${report.buyPct}%`, background: "#15803d" }}>
                  {report.buyPct}%
                </div>
                <div className="flex items-center justify-center" style={{ width: `${report.holdPct}%`, background: "#b45309" }}>
                  {report.holdPct}%
                </div>
                <div className="flex items-center justify-center" style={{ width: `${report.sellPct}%`, background: "#dc2626" }}>
                  {report.sellPct}%
                </div>
              </div>
              <div className="flex justify-between mt-1 text-[9px]" style={{ color: "#64748b" }}>
                <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full" style={{ background: "#15803d" }} />{l.buy}</span>
                <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full" style={{ background: "#b45309" }} />{l.hold}</span>
                <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full" style={{ background: "#dc2626" }} />{l.sell}</span>
              </div>
              {/* Sentiment + Trend inline */}
              <div className="grid grid-cols-2 gap-2 mt-3">
                <div className="p-2 text-center rounded" style={{ border: "1px solid #e5e7eb", background: "#f8fafc" }}>
                  <Activity className="mx-auto mb-0.5" size={14} style={{ color: "#b45309" }} />
                  <p className="text-[8px] uppercase tracking-[0.12em]" style={{ color: "#94a3b8" }}>{l.sentiment}</p>
                  <p className="text-[15px] font-bold" style={{ color: "#1e293b" }}>{report.sentimentScore}/100</p>
                </div>
                <div className="p-2 text-center rounded" style={{ border: "1px solid #e5e7eb", background: "#f8fafc" }}>
                  <BarChart3 className="mx-auto mb-0.5" size={14} style={{ color: "#15803d" }} />
                  <p className="text-[8px] uppercase tracking-[0.12em]" style={{ color: "#94a3b8" }}>{l.trendStrength}</p>
                  <p className="text-[15px] font-bold" style={{ color: "#1e293b" }}>{report.trendStrength}/100</p>
                </div>
              </div>
            </div>
          </div>

          {/* Price vs Index Chart — height capped at 220px */}
          <Section className="report-section">
            <div className="stock-chart-container" style={{ maxHeight: "220px" }}>
              <PriceVsIndexChart lang={lang} ticker={report.ticker} />
            </div>
          </Section>

          {/* Bull/Bear Analysis side-by-side */}
          <Section className="report-section">
            <SectionTitle>{l.deepDive}</SectionTitle>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 print-2col">
              <div className="p-3 rounded" style={{ background: "#f0fdf4", border: "1px solid #86efac" }}>
                <p className="text-[10px] font-bold uppercase tracking-[0.1em] mb-1.5" style={{ color: "#15803d" }}>
                  <TrendingUp size={12} className="inline mr-1" />{l.bullCase}
                </p>
                <ul className="space-y-1">
                  {report.bullPoints.map((p, i) => (
                    <li key={i} className="flex items-start gap-1.5 text-[10px]" style={{ color: "#166534" }}>
                      <span className="w-1.5 h-1.5 rounded-full mt-[5px] shrink-0" style={{ background: "#15803d" }} />
                      {p}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="p-3 rounded" style={{ background: "#fef2f2", border: "1px solid #fca5a5" }}>
                <p className="text-[10px] font-bold uppercase tracking-[0.1em] mb-1.5" style={{ color: "#dc2626" }}>
                  <TrendingDown size={12} className="inline mr-1" />{l.bearCase}
                </p>
                <ul className="space-y-1">
                  {report.bearPoints.map((p, i) => (
                    <li key={i} className="flex items-start gap-1.5 text-[10px]" style={{ color: "#991b1b" }}>
                      <span className="w-1.5 h-1.5 rounded-full mt-[5px] shrink-0" style={{ background: "#dc2626" }} />
                      {p}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </Section>

          {/* Financial Snapshot */}
          <Section className="report-section">
            <SectionTitle>{l.financialSnapshot}</SectionTitle>
            <div className="space-y-3">
              {/* Health Score */}
              {(() => {
                const score = report.financialHealthScore;
                const tier = score >= 80 ? "excellent" : score >= 60 ? "good" : score >= 40 ? "fair" : "weak";
                const tierLabel = tier === "excellent" ? l.healthExcellent : tier === "good" ? l.healthGood : tier === "fair" ? l.healthFair : l.healthWeak;
                const tierColor = tier === "excellent" ? "#15803d" : tier === "good" ? "#2563eb" : tier === "fair" ? "#f59e0b" : "#dc2626";
                const tierAdvice = tier === "excellent" ? l.healthAdviceExcellent : tier === "good" ? l.healthAdviceGood : tier === "fair" ? l.healthAdviceFair : l.healthAdviceWeak;

                const peNum = parseFloat(report.peRatio.replace("x", ""));
                const roeNum = parseFloat(report.roe.replace("%", ""));
                const de = report.debtToEquity;
                const cf = report.cashFlowTrend;
                const peS = isNaN(peNum) ? 12 : peNum < 15 ? 22 : peNum < 25 ? 18 : peNum < 40 ? 12 : 6;
                const roeS = isNaN(roeNum) ? 12 : roeNum > 20 ? 23 : roeNum > 12 ? 18 : roeNum > 5 ? 12 : 5;
                const debtS = de < 0.3 ? 24 : de < 0.8 ? 20 : de < 1.5 ? 12 : 4;
                const cfS = cf === "up" ? 23 : cf === "stable" ? 16 : 6;
                const cfLabel = cf === "up" ? l.cashFlowUp : cf === "stable" ? l.cashFlowStable : l.cashFlowDown;
                const cfColor = cf === "up" ? "#15803d" : cf === "stable" ? "#b45309" : "#dc2626";

                const cx = 55, cy = 55, r = 45;
                const circumference = 2 * Math.PI * r;
                const arcLen = (score / 100) * circumference;

                return (
                  <div className="p-3 rounded" style={{ border: `1px solid ${tierColor}22`, background: `${tierColor}08` }}>
                    <div className="flex items-start gap-3">
                      {/* Score donut — compact */}
                      <div className="flex flex-col items-center shrink-0">
                        <svg width={90} height={90} viewBox="0 0 110 110">
                          <circle cx={cx} cy={cy} r={r} fill="none" stroke="#e2e8f0" strokeWidth={8} />
                          <circle cx={cx} cy={cy} r={r} fill="none" stroke={`url(#healthGrad-${score})`} strokeWidth={8}
                            strokeDasharray={`${arcLen} ${circumference}`}
                            strokeLinecap="round" transform={`rotate(-90 ${cx} ${cy})`}
                          />
                          <defs>
                            <linearGradient id={`healthGrad-${score}`} x1="0%" y1="0%" x2="100%" y2="0%">
                              <stop offset="0%" stopColor="#dc2626" />
                              <stop offset="35%" stopColor="#f59e0b" />
                              <stop offset="70%" stopColor="#2563eb" />
                              <stop offset="100%" stopColor="#15803d" />
                            </linearGradient>
                          </defs>
                          <text x={cx} y={cy - 6} textAnchor="middle" style={{ fontSize: "20px", fontWeight: 800, fill: tierColor }}>
                            {score}
                          </text>
                          <text x={cx} y={cy + 8} textAnchor="middle" style={{ fontSize: "9px", fontWeight: 600, fill: tierColor }}>
                            /100
                          </text>
                        </svg>
                        <span className="text-[9px] font-bold px-2 py-0.5 rounded-full" style={{ background: tierColor, color: "#fff" }}>
                          {tierLabel}
                        </span>
                      </div>
                      {/* Breakdown */}
                      <div className="flex-1 min-w-0">
                        <p className="text-[10px] leading-relaxed mb-2" style={{ color: "#334155" }}>{tierAdvice}</p>
                        <div className="grid grid-cols-2 gap-1.5">
                          {[
                            { label: l.peRatio, score: peS, max: 25, value: report.peRatio },
                            { label: l.roeLabel, score: roeS, max: 25, value: report.roe },
                            { label: l.debtLabel, score: debtS, max: 25, value: `${report.debtToEquity.toFixed(2)}x` },
                            { label: l.cashFlowLabel, score: cfS, max: 25, value: cfLabel },
                          ].map((sub) => (
                            <div key={sub.label} className="p-1.5 rounded" style={{ background: "rgba(255,255,255,0.6)", border: "1px solid rgba(0,0,0,0.06)" }}>
                              <div className="flex items-center justify-between mb-0.5">
                                <span className="text-[8px] uppercase tracking-[0.08em] font-semibold" style={{ color: "#64748b" }}>{sub.label}</span>
                                <span className="text-[9px] font-bold" style={{ color: "#1e293b" }}>{sub.value}</span>
                              </div>
                              <div className="w-full h-[4px] rounded-full overflow-hidden" style={{ background: "#e2e8f0" }}>
                                <div
                                  className="h-full rounded-full"
                                  style={{
                                    width: `${(sub.score / sub.max) * 100}%`,
                                    background: sub.score >= 20 ? "#15803d" : sub.score >= 12 ? "#2563eb" : sub.score >= 8 ? "#f59e0b" : "#dc2626",
                                  }}
                                />
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })()}

              {/* Financial metric details — compact */}
              {(() => {
                const peNum = parseFloat(report.peRatio.replace("x", ""));
                const roeNum = parseFloat(report.roe.replace("%", ""));
                const divNum = parseFloat(report.dividendYield.replace("%", ""));
                const sector = report.sector;
                const isTech = sector === "Technology" || sector === "Communication Services";
                const isFinancial = sector === "Financials";
                const price = parseFloat(report.price.replace(/[^0-9.]/g, ""));
                const currency = report.price.replace(/[0-9.,]/g, "").trim();
                const isHK = currency.includes("HK");
                const investAmount = isHK ? 100000 : 10000;
                const investLabel = isHK ? (lang === "en" ? "HK$100,000" : "10萬港幣") : (lang === "en" ? "$10,000" : "$10,000");
                const annualDiv = Math.round(investAmount * divNum / 100);

                const metrics = [
                  (() => {
                    const isExpensive = isTech ? peNum > 35 : isFinancial ? peNum > 15 : peNum > 25;
                    const isCheap = isTech ? peNum < 20 : isFinancial ? peNum < 8 : peNum < 15;
                    const signal: "green" | "amber" | "red" = isCheap ? "green" : isExpensive ? "red" : "amber";
                    const sectorBenchmark = isTech ? (lang === "en" ? "25-35x" : "25-35倍") : isFinancial ? (lang === "en" ? "8-15x" : "8-15倍") : (lang === "en" ? "15-25x" : "15-25倍");
                    const explanation = {
                      en: isExpensive ? `P/E ${report.peRatio} — premium vs ${sector} avg ${sectorBenchmark}.` : isCheap ? `P/E ${report.peRatio} — below ${sector} avg ${sectorBenchmark}, potentially undervalued.` : `P/E ${report.peRatio} — normal for ${sector} (${sectorBenchmark}).`,
                      tc: isExpensive ? `市盈率 ${report.peRatio}——高於 ${sector} 平均 ${sectorBenchmark}。` : isCheap ? `市盈率 ${report.peRatio}——低於 ${sector} 平均 ${sectorBenchmark}，可能被低估。` : `市盈率 ${report.peRatio}——處於 ${sector} 正常範圍（${sectorBenchmark}）。`,
                      sc: isExpensive ? `市盈率 ${report.peRatio}——高于 ${sector} 平均 ${sectorBenchmark}。` : isCheap ? `市盈率 ${report.peRatio}——低于 ${sector} 平均 ${sectorBenchmark}，可能被低估。` : `市盈率 ${report.peRatio}——处于 ${sector} 正常范围（${sectorBenchmark}）。`,
                    };
                    return { label: l.peRatio, value: report.peRatio, signal, explanation: explanation[lang] };
                  })(),
                  (() => {
                    const isStrong = roeNum > 15;
                    const isWeak = roeNum < 8;
                    const signal: "green" | "amber" | "red" = isStrong ? "green" : isWeak ? "red" : "amber";
                    const explanation = {
                      en: isStrong ? `ROE ${report.roe} — high capital efficiency, strong earnings.` : isWeak ? `ROE ${report.roe} — weak capital efficiency.` : `ROE ${report.roe} — moderate efficiency.`,
                      tc: isStrong ? `ROE ${report.roe}——資本效率高，盈利能力強。` : isWeak ? `ROE ${report.roe}——資本效率偏弱。` : `ROE ${report.roe}——資本效率中等。`,
                      sc: isStrong ? `ROE ${report.roe}——资本效率高，盈利能力强。` : isWeak ? `ROE ${report.roe}——资本效率偏弱。` : `ROE ${report.roe}——资本效率中等。`,
                    };
                    return { label: l.roeLabel, value: report.roe, signal, explanation: explanation[lang] };
                  })(),
                  (() => {
                    const isHigh = divNum > 4;
                    const isZero = divNum < 0.1;
                    const signal: "green" | "amber" | "red" = isHigh ? "green" : isZero ? "red" : "amber";
                    const divCalc = lang === "en" ? `Invest ${investLabel} → ~${currency}${annualDiv.toLocaleString()}/yr.` : lang === "tc" ? `投資 ${investLabel} → 年約 ${currency}${annualDiv.toLocaleString()}。` : `投资 ${investLabel} → 年约 ${currency}${annualDiv.toLocaleString()}。`;
                    const explanation = {
                      en: isHigh ? `Yield ${report.dividendYield} — strong income. ${divCalc}` : isZero ? `No dividend — growth reinvestment.` : `Yield ${report.dividendYield} — modest income. ${divCalc}`,
                      tc: isHigh ? `收益率 ${report.dividendYield}——可觀收入。${divCalc}` : isZero ? `不派息——利潤再投資於增長。` : `收益率 ${report.dividendYield}——適度收入。${divCalc}`,
                      sc: isHigh ? `收益率 ${report.dividendYield}——可观收入。${divCalc}` : isZero ? `不派息——利润再投资于增长。` : `收益率 ${report.dividendYield}——适度收入。${divCalc}`,
                    };
                    return { label: l.dividendYield, value: report.dividendYield, signal, explanation: explanation[lang] };
                  })(),
                  (() => {
                    const vol = report.volatility.toLowerCase();
                    const isHigh = vol.includes("high") || vol.includes("高");
                    const isLow = vol.includes("low") || vol.includes("低");
                    const signal: "green" | "amber" | "red" = isLow ? "green" : isHigh ? "red" : "amber";
                    const explanation = {
                      en: isHigh ? `High volatility — expect sharp price swings.` : isLow ? `Low volatility — stable, predictable.` : `Moderate volatility — typical for active stocks.`,
                      tc: isHigh ? `高波動——預計價格劇烈波動。` : isLow ? `低波動——穩定可預測。` : `中等波動——活躍交易股票的典型特徵。`,
                      sc: isHigh ? `高波动——预计价格剧烈波动。` : isLow ? `低波动——稳定可预测。` : `中等波动——活跃交易股票的典型特征。`,
                    };
                    return { label: l.volatilityIndex, value: report.volatility, signal, explanation: explanation[lang] };
                  })(),
                ];

                const signalColors = { green: { bg: "#f0fdf4", border: "#86efac", dot: "#15803d" }, amber: { bg: "#fffbeb", border: "#fcd34d", dot: "#b45309" }, red: { bg: "#fef2f2", border: "#fca5a5", dot: "#dc2626" } };

                return (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 print-2col">
                    {metrics.map((m, i) => {
                      const sc = signalColors[m.signal];
                      return (
                        <div key={i} className="p-2 rounded" style={{ border: `1px solid ${sc.border}`, background: sc.bg }}>
                          <div className="flex items-center justify-between mb-1">
                            <div className="flex items-center gap-1.5">
                              <span className="w-2 h-2 rounded-full" style={{ background: sc.dot }} />
                              <span className="text-[9px] uppercase tracking-[0.1em] font-bold" style={{ color: "#64748b" }}>{m.label}</span>
                            </div>
                            <span className="text-[13px] font-bold" style={{ color: "#1e293b" }}>{m.value}</span>
                          </div>
                          <p className="text-[9px] leading-relaxed" style={{ color: "#334155" }}>{m.explanation}</p>
                        </div>
                      );
                    })}
                  </div>
                );
              })()}
            </div>
          </Section>

          {/* Strategic Advice — compact */}
          <Section className="report-section">
            <SectionTitle>{l.strategicAdvice}</SectionTitle>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 print-2col">
              <div className="p-2 rounded" style={{ border: "1px solid #e5e7eb", background: "#f8fafc" }}>
                <p className="text-[9px] uppercase tracking-[0.1em] mb-0.5" style={{ color: "#94a3b8" }}>{l.conservative}</p>
                <p className="text-[10px]" style={{ color: "#334155" }}>{report.conservativeAdvice}</p>
              </div>
              <div className="p-2 rounded" style={{ border: "1px solid #e5e7eb", background: "#f8fafc" }}>
                <p className="text-[9px] uppercase tracking-[0.1em] mb-0.5" style={{ color: "#94a3b8" }}>{l.value}</p>
                <p className="text-[10px]" style={{ color: "#334155" }}>{report.valueAdvice}</p>
              </div>
            </div>
          </Section>

          {/* Peer Comparison */}
          <Section className="report-section report-page-break">
            <PeerComparisonTable
              lang={lang}
              targetTicker={report.ticker}
              targetCompany={report.companyName || report.ticker}
              targetPrice={report.price}
              targetMarketCap={report.marketCap}
              targetPE={report.peRatio}
              targetROE={report.roe}
              targetDivYield={report.dividendYield}
            />
          </Section>

          {/* Investment Risk Assessment — Market + Company side by side */}
          <Section className="report-section">
            <SectionTitle>⚠️ {l.riskTitle}</SectionTitle>
            <div className="space-y-3">
              {/* Risk Tier Gauge */}
              {(() => {
                const vol = report.volatility.toLowerCase();
                const isHigh = vol.includes("high") || vol.includes("高");
                const isLow = vol.includes("low") || vol.includes("低");
                const tier = isHigh ? "high" : isLow ? "conservative" : "growth";
                const tierLabel = tier === "high" ? l.riskTierHighRisk : tier === "conservative" ? l.riskTierConservative : l.riskTierGrowth;
                const tierAdvice = tier === "high" ? l.riskTierAdviceHighRisk : tier === "conservative" ? l.riskTierAdviceConservative : l.riskTierAdviceGrowth;
                const tierColor = tier === "high" ? "#dc2626" : tier === "conservative" ? "#15803d" : "#b45309";
                const tierBg = tier === "high" ? "#fef2f2" : tier === "conservative" ? "#f0fdf4" : "#fffbeb";
                const tierBorder = tier === "high" ? "#fca5a5" : tier === "conservative" ? "#86efac" : "#fcd34d";
                const gaugePos = tier === "high" ? 85 : tier === "conservative" ? 20 : 50;
                return (
                  <div className="p-3 rounded" style={{ background: tierBg, border: `1px solid ${tierBorder}` }}>
                    <div className="flex items-center gap-2 mb-2">
                      <Shield size={12} style={{ color: tierColor }} />
                      <span className="text-[10px] font-bold" style={{ color: tierColor }}>{l.riskTierLabel}</span>
                    </div>
                    <div className="relative mb-2">
                      <div className="flex h-[8px] rounded-full overflow-hidden" style={{ background: "#e2e8f0" }}>
                        <div className="h-full" style={{ width: "33.3%", background: "linear-gradient(90deg, #15803d, #22c55e)" }} />
                        <div className="h-full" style={{ width: "33.3%", background: "linear-gradient(90deg, #eab308, #f59e0b)" }} />
                        <div className="h-full" style={{ width: "33.4%", background: "linear-gradient(90deg, #ef4444, #dc2626)" }} />
                      </div>
                      <div className="absolute top-[-3px] transition-all duration-500" style={{ left: `${gaugePos}%`, transform: "translateX(-50%)" }}>
                        <div style={{ width: 0, height: 0, borderLeft: "4px solid transparent", borderRight: "4px solid transparent", borderTop: `6px solid ${tierColor}` }} />
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-[9px] font-bold px-2 py-0.5 rounded-full" style={{ background: tierColor, color: "#fff" }}>{tierLabel}</span>
                      <span className="text-[9px]" style={{ color: "#475569" }}>{tierAdvice}</span>
                    </div>
                  </div>
                );
              })()}

              {/* All 3 risk categories — 3-column grid, no icons, 9pt font */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-2 print-3col" style={{ pageBreakInside: "avoid", breakInside: "avoid" }}>
                <div className="p-2 rounded" style={{ background: "#f1f5f9", border: "1px solid #cbd5e1" }}>
                  <span className="text-[9px] font-bold block mb-1" style={{ color: "#334155" }}>{l.riskMarket}</span>
                  <ul className="space-y-0.5">
                    {report.riskAssessment.market.map((r, i) => (
                      <li key={i} className="text-[8px] leading-tight" style={{ color: "#475569" }}>• {r}</li>
                    ))}
                  </ul>
                </div>
                <div className="p-2 rounded" style={{ background: "#fefce8", border: "1px solid #fbbf24" }}>
                  <span className="text-[9px] font-bold block mb-1" style={{ color: "#92400e" }}>{l.riskCompany}</span>
                  <ul className="space-y-0.5">
                    {report.riskAssessment.company.map((r, i) => (
                      <li key={i} className="text-[8px] leading-tight" style={{ color: "#78350f" }}>• {r}</li>
                    ))}
                  </ul>
                </div>
                <div className="p-2 rounded" style={{ background: "#eff6ff", border: "1px solid #93c5fd" }}>
                  <span className="text-[9px] font-bold block mb-1" style={{ color: "#1e40af" }}>{l.riskModel}</span>
                  <ul className="space-y-0.5">
                    {report.riskAssessment.model.map((r, i) => (
                      <li key={i} className="text-[8px] leading-tight" style={{ color: "#1e3a5f" }}>• {r}</li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Self-Decision — compact */}
              <div className="p-2 rounded" style={{ background: "#fef2f2", border: "1px solid #fca5a5" }}>
                <div className="flex items-start gap-1.5">
                  <Shield className="shrink-0 mt-0.5" size={12} style={{ color: "#dc2626" }} />
                  <div>
                    <span className="text-[10px] font-bold" style={{ color: "#991b1b" }}>{l.riskSelfDecision}</span>
                    <p className="text-[9px] mt-0.5 leading-relaxed" style={{ color: "#7f1d1d" }}>{l.riskSelfDecisionBody}</p>
                  </div>
                </div>
              </div>
            </div>
          </Section>

          {/* Latest News */}
          {report.news && report.news.length > 0 && (
            <Section className="report-section">
              <NewsSection lang={lang} news={report.news} />
            </Section>
          )}
        </div>

        {/* ── Institutional Footnotes ─────────── */}
        <div className="px-5 py-2" style={{ borderTop: "1px solid #e5e7eb", background: "#ffffff" }}>
          <div className="space-y-0.5">
            <p className="text-[7px] leading-relaxed" style={{ color: "#94a3b8" }}>
              <sup>1</sup> {l.footnote1}
            </p>
            <p className="text-[7px] leading-relaxed" style={{ color: "#94a3b8" }}>
              <sup>2</sup> {l.footnote2}
            </p>
            <p className="text-[7px] leading-relaxed" style={{ color: "#94a3b8" }}>
              <sup>3</sup> {l.footnote3}
            </p>
          </div>
        </div>

        {/* ── Branding footer ────────────────── */}
        <div className="px-5 py-2 flex items-center justify-between" style={{ background: "#f8fafc", borderTop: "1px solid #e5e7eb" }}>
          <div className="flex items-center gap-2">
            <img src={dragonLogo} alt="" className="h-4 w-4" />
            <span className="text-[8px]" style={{ color: "#64748b" }}>{l.reportFooter} — {today}</span>
          </div>
          <div className="flex items-start gap-2">
            <Shield className="shrink-0 mt-0.5" size={12} style={{ color: "#1e293b" }} />
            <span className="text-[8px]" style={{ color: "#64748b" }}>
              <span className="font-bold" style={{ color: "#1e293b" }}>{l.selfDecision}:</span> {l.finalDisclaimer}
            </span>
          </div>
        </div>

        {/* ── Confidential strip ───────────────── */}
        <div className="text-center py-1.5" style={{ background: "#1e293b" }}>
          <p className="text-[8px] uppercase tracking-[0.2em]" style={{ color: "rgba(255,255,255,0.5)" }}>
            {l.confidential}
          </p>
        </div>
      </div>

      {/* ══ Print-only footer ═══════════════════ */}
      <div className="print-only items-center justify-between pt-2 mt-3" style={{ borderTop: "1px solid #e5e7eb" }}>
        <p className="text-[7px] uppercase tracking-[0.15em]" style={{ color: "#94a3b8" }}>{l.confidential}</p>
        <p className="text-[7px]" style={{ color: "#94a3b8" }}>DragonGPAi.com — {report.date}</p>
      </div>
    </div>
  );
};

export default StockReport;
