// src/components/ai-stocks/StockReport.tsx
import { useState, useEffect, useRef } from "react";
import {
  Star,
  Shield,
  TrendingUp,
  TrendingDown,
  Activity,
  BarChart3,
  Volume2,
  Printer,
  FileDown,
  Share2,
  Facebook,
  Copy,
  Check,
  ArrowLeft,
  Sparkles,
  AlertTriangle,
  ChevronDown,
  Heart,
  ArrowRight,
  Play,
  Pause,
  Square,
  Twitter,
  Linkedin,
  MessageCircle,
  Download,
  Loader2
} from "lucide-react";
import type { LangKey } from "@/contexts/LanguageContext";
import type { StockNewsItem } from "@/hooks/useStockData";
import { Button } from "@/components/ui/button";
import ProbabilityGauge from "./ProbabilityGauge";
import PeerComparisonTable from "./PeerComparisonTable";
import RecommendationSidebar from "./RecommendationSidebar";
import AnalystConfidenceGauge from "./AnalystConfidenceGauge";
import PriceVsIndexChart from "./PriceVsIndexChart";
import MarketDepthSection from "./MarketDepthSection";
import CompanyProfile from "./CompanyProfile";
import NewsSection from "./NewsSection";
import dragonLogo from "@/assets/dragon-logo.png";
import founderIcon from "@/assets/founder-icon.png";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { toast } from "sonner";
import { Link } from "react-router-dom";
import { useWatchlist } from "@/hooks/useWatchlist";
import { useSpeech } from "@/hooks/useSpeech";

/* ── Trilingual labels ───────────────────────── */
const translations = {
  en: {
    reportTitle: "AI Stock Probability Report",
    subject: "Subject",
    dateLabel: "Date of Analysis",
    status: "Cognitive Engagement Exercise",
    marketData: "Market Data",
    livePrice: "Live Price",
    weekHigh: "52-Week High",
    weekLow: "52-Week Low",
    volume: "Volume",
    techIndicators: "Technical Indicators",
    rsiIndicator: "RSI (14) Indicator",
    macdIndicator: "MACD Indicator",
    macdLine: "MACD Line",
    signalLine: "Signal Line",
    histogram: "Histogram",
    aiProbPricing: "AI Probability Pricing",
    aiProbability: "AI Probability",
    buyTarget: "Buy Target",
    sellTarget: "Sell Target",
    decisionMatrix: "Decision Matrix",
    buy: "Buy",
    hold: "Hold",
    sell: "Sell",
    aiRecommendation: "AI Recommendation",
    deepDive: "AI Deep-Dive Analysis",
    bullCase: "The Bull Case (Positive Drivers)",
    bearCase: "The Bear Case (Risk Factors)",
    financialSnapshot: "Financial Snapshot",
    healthScoreTitle: "Financial Health Score",
    healthExcellent: "Excellent",
    healthGood: "Good",
    healthFair: "Fair",
    healthWeak: "Weak",
    healthAdviceExcellent: "Strong fundamentals across all dimensions — suitable for long-term holding with high conviction.",
    healthAdviceGood: "Solid overall health with minor areas to monitor — a dependable choice for most portfolios.",
    healthAdviceFair: "Mixed financial signals — conduct deeper research before committing significant capital.",
    healthAdviceWeak: "Multiple financial concerns detected — higher risk, only suitable for speculative positions.",
    debtLabel: "Debt-to-Equity",
    cashFlowLabel: "Cash Flow Trend",
    cashFlowUp: "Increasing",
    cashFlowStable: "Stable",
    cashFlowDown: "Declining",
    dividendYield: "Dividend Yield",
    volatilityIndex: "Volatility Index",
    strategicAdvice: "Strategic Advice",
    conservative: "Conservative Investor:",
    value: "Value Investor:",
    sentiment: "Algorithmic Sentiment",
    trendStrength: "Trend Strength",
    addWatchlist: "Save to Watchlist",
    savedToWatchlist: "⭐ Saved",
    selfDecision: "Principle of Self-Decision",
    finalDisclaimer: "This report is generated by a mathematical AI model for educational and mental stimulation purposes only. The founder holds No Professional or Gambling Licenses. This is not financial advice.",
    confidential: "CONFIDENTIAL — For Intended Recipient Only",
    executiveThesisTitle: "Executive Investment Thesis",
    sectorLabel: "Sector",
    industryLabel: "Industry",
    keyMultiples: "Key Financial Multiples",
    marketCap: "Market Cap",
    peRatio: "P/E Ratio",
    roeLabel: "ROE",
    riskTitle: "Investment Risk Assessment",
    riskTierLabel: "Risk Tier",
    riskTierConservative: "Conservative",
    riskTierGrowth: "Growth",
    riskTierHighRisk: "High Risk",
    riskTierAdviceConservative: "This stock has low volatility — suitable as a core holding with stable returns.",
    riskTierAdviceGrowth: "This stock has moderate volatility — consider limiting to 10-15% of your total portfolio.",
    riskTierAdviceHighRisk: "This stock has high volatility — consider limiting to no more than 5% of your total portfolio.",
    riskMarket: "Market Risk",
    riskMarketDesc: "Risks from broad market movements that affect all stocks",
    riskCompany: "Company-Specific Risk",
    riskCompanyDesc: "Risks unique to this particular company or its sector",
    riskModel: "AI Model Limitations",
    riskModelDesc: "Limitations of the mathematical model used in this analysis",
    riskSelfDecision: "Principle of Self-Decision",
    riskSelfDecisionBody: "AI probability scores are mathematical calculations based on historical data — they are NOT guarantees of profit or loss. Always make your own informed decision and consult a licensed financial advisor before investing.",
    footnote1: "This document is produced by DragonGPAi.com for informational purposes only and does not constitute an offer, solicitation, or recommendation to buy or sell any security.",
    footnote2: "The analysis herein is based on mathematical probability models and publicly available market data. DragonGPAi.com holds no professional financial advisory or gambling licenses.",
    footnote3: "Past performance is not indicative of future results. All investments carry risk, including the possible loss of principal.",
    priceVsIndex: "12-Month Price vs. Index Performance",
    reportFooter: "Report created by DragonGPAi.com, powered by Gemini",
    noAdvice: "Maintain existing positions with tight risk management.",
    noValueAdvice: "Wait for clearer value signals before making decisions.",
    loading: "Loading report data...",
    printPDF: "Print",
    savePDF: "Save as Text",
    downloadPDF: "Download PDF",
    share: "Share",
    textToVoice: "Text-to-Voice",
    textToVoiceDesc: "Click the 🔊 Read Analysis button above to listen to this report. The AI will read the full analysis including price, RSI, MACD, and recommendations in your selected language.",
    textToVoiceSpeaking: "🔊 AI is now reading the report aloud...",
    shareFacebook: "Share on Facebook",
    shareWhatsApp: "Share on WhatsApp",
    shareTwitter: "Share on Twitter",
    shareLinkedIn: "Share on LinkedIn",
    copyReport: "Copy Report",
    copied: "Copied!",
    goToMark6: "Go to AI Mark6 Probability Game Now",
    selectAnother: "Next Select",
    scrollDown: "Scroll Down for Full Report / 向下移動查看完整報告",
    aiAnalysisLogic: "AI Analysis Logic",
    rsiExplanation: "Measures if the stock is overextended (overbought/oversold).",
    macdExplanation: "Measures the strength and direction of the current trend.",
    saveToWatchlist: "Save to Watchlist",
    watchlistCTA: "Want to add to your Watch List? (Max 10)",
    watchlistFull: "Watch List full. Please remove a stock first.",
    marketDepth: "Market Depth",
    bid: "Bid",
    ask: "Ask",
    dayRange: "Day Range",
    prevClose: "Prev. Close",
    marketOpen: "Market Open",
    marketClosed: "Market Closed",
    companyProfile: "Company Profile",
    noDividends: "No Dividends",
    readReport: "Read Analysis",
    speaking: "Speaking...",
    paused: "Paused",
    ready: "Ready",
    play: "Play",
    pauseCtrl: "Pause",
    stop: "Stop",
    buySignal: "RSI(14) at {value} indicates oversold conditions. This is typically considered a BUY signal, suggesting the stock may be undervalued and due for a rebound.",
    sellSignal: "RSI(14) at {value} indicates overbought conditions. This is typically considered a SELL signal, suggesting the stock may be overvalued and due for a pullback.",
    voiceTranscript: "📢 AI Voice Analysis Transcript",
  },
  "zh-TW": {
    reportTitle: "AI 股票概率報告",
    subject: "標的",
    dateLabel: "分析日期",
    status: "認知參與練習",
    marketData: "市場數據",
    livePrice: "現價",
    weekHigh: "52週高",
    weekLow: "52週低",
    volume: "成交量",
    techIndicators: "技術指標",
    rsiIndicator: "RSI (14) 指標",
    macdIndicator: "MACD 指標",
    macdLine: "MACD 線",
    signalLine: "信號線",
    histogram: "柱狀圖",
    aiProbPricing: "AI 概率定價",
    aiProbability: "AI 概率",
    buyTarget: "買入目標",
    sellTarget: "賣出目標",
    decisionMatrix: "決策矩陣",
    buy: "買入",
    hold: "持有",
    sell: "賣出",
    aiRecommendation: "AI 建議",
    deepDive: "AI 深度分析",
    bullCase: "牛市論點（正面驅動因素）",
    bearCase: "熊市論點（風險因素）",
    financialSnapshot: "財務概況",
    healthScoreTitle: "財務健康綜合評分",
    healthExcellent: "優秀",
    healthGood: "良好",
    healthFair: "普通",
    healthWeak: "偏弱",
    healthAdviceExcellent: "各維度基本面強勁——適合高信心長期持有。",
    healthAdviceGood: "整體健康穩健，少數方面需關注——對大多數投資組合是可靠選擇。",
    healthAdviceFair: "財務信號喜憂參半——投入大量資金前需做更深入研究。",
    healthAdviceWeak: "偵測到多項財務隱憂——風險較高，僅適合投機性持倉。",
    debtLabel: "負債權益比",
    cashFlowLabel: "現金流趨勢",
    cashFlowUp: "上升",
    cashFlowStable: "穩定",
    cashFlowDown: "下降",
    dividendYield: "股息收益率",
    volatilityIndex: "波動指數",
    strategicAdvice: "策略建議",
    conservative: "穩健型投資者：",
    value: "價值型投資者：",
    sentiment: "算法情緒",
    trendStrength: "趨勢強度",
    addWatchlist: "加入自選",
    savedToWatchlist: "⭐ 已儲存",
    selfDecision: "自主決策原則",
    finalDisclaimer: "本報告由數學 AI 模型生成，僅供教育和認知刺激之用。創辦人不持有任何專業或博弈牌照。此非財務建議。",
    confidential: "機密 — 僅限預期收件人",
    executiveThesisTitle: "執行投資論點",
    sectorLabel: "板塊",
    industryLabel: "行業",
    keyMultiples: "主要財務指標",
    marketCap: "市值",
    peRatio: "市盈率",
    roeLabel: "股本回報率",
    riskTitle: "投資風險評估",
    riskTierLabel: "風險等級",
    riskTierConservative: "穩健型",
    riskTierGrowth: "成長型",
    riskTierHighRisk: "高風險型",
    riskTierAdviceConservative: "本標的波動較低，適合作為核心持倉，回報相對穩定。",
    riskTierAdviceGrowth: "本標的波動適中，建議佔總倉位不超過 10-15%。",
    riskTierAdviceHighRisk: "本標的波動較大，建議佔總倉位不超過 5%。",
    riskMarket: "市場風險",
    riskMarketDesc: "影響所有股票的大盤波動風險",
    riskCompany: "個股風險",
    riskCompanyDesc: "此公司或其板塊特有的風險",
    riskModel: "AI 模型限制",
    riskModelDesc: "本分析所用數學模型的局限性",
    riskSelfDecision: "自主決策原則",
    riskSelfDecisionBody: "AI 概率評分是基於歷史數據的數學推算——並非獲利或虧損的保證。請務必自行做出明智決定，並在投資前諮詢持牌財務顧問。",
    footnote1: "本文件由 DragonGPAi.com 製作，僅供參考之用，不構成任何買賣證券的要約、招攬或建議。",
    footnote2: "本分析基於數學概率模型及公開市場數據。DragonGPAi.com 不持有任何專業財務顧問或博弈牌照。",
    footnote3: "過往表現並非未來表現的指標。所有投資均存在風險，包括可能損失本金。",
    priceVsIndex: "12個月股價 vs 指數表現",
    reportFooter: "報告由 DragonGPAi.com 製作，由 Gemini 提供支持",
    noAdvice: "維持現有倉位，嚴格風險管理。",
    noValueAdvice: "等待更清晰的價值信號再做決策。",
    loading: "正在載入報告數據...",
    printPDF: "列印",
    savePDF: "儲存為文字",
    downloadPDF: "下載 PDF",
    share: "分享",
    textToVoice: "文字轉語音",
    textToVoiceDesc: "點擊上方的 🔊 朗讀分析 按鈕收聽此報告。AI 將以您選擇的語言朗讀完整分析，包括價格、RSI、MACD 和建議。",
    textToVoiceSpeaking: "🔊 AI 正在朗讀報告...",
    shareFacebook: "分享到 Facebook",
    shareWhatsApp: "分享到 WhatsApp",
    shareTwitter: "分享到 Twitter",
    shareLinkedIn: "分享到 LinkedIn",
    copyReport: "複製報告",
    copied: "已複製！",
    goToMark6: "立即前往 AI 六合彩概率遊戲",
    selectAnother: "下一隻",
    scrollDown: "向下滾動查看完整報告 / Scroll Down for Full Report",
    aiAnalysisLogic: "AI 分析邏輯",
    rsiExplanation: "衡量股票是否超買或超賣。",
    macdExplanation: "衡量當前趨勢的強度與方向。",
    saveToWatchlist: "加入自選股",
    watchlistCTA: "想加入您的自選股名單嗎？(最多10個)",
    watchlistFull: "自選股名單已滿，請先刪除一個。",
    marketDepth: "市場深度",
    bid: "買盤",
    ask: "賣盤",
    dayRange: "日內範圍",
    prevClose: "前收盤價",
    marketOpen: "交易中",
    marketClosed: "已收盤",
    companyProfile: "公司簡介",
    noDividends: "不派息",
    readReport: "朗讀分析",
    speaking: "朗讀中...",
    paused: "暫停",
    ready: "就緒",
    play: "播放",
    pauseCtrl: "暫停",
    stop: "停止",
    buySignal: "RSI(14) 為 {value}，處於超賣區間。這通常被視為買入信號，顯示該股可能被低估，有望反彈。",
    sellSignal: "RSI(14) 為 {value}，處於超買區間。這通常被視為賣出信號，顯示該股可能被高估，有望回調。",
    voiceTranscript: "📢 AI 語音分析轉錄",
  },
  "zh-CN": {
    reportTitle: "AI 股票概率报告",
    subject: "标的",
    dateLabel: "分析日期",
    status: "认知参与练习",
    marketData: "市场数据",
    livePrice: "现价",
    weekHigh: "52周高",
    weekLow: "52周低",
    volume: "成交量",
    techIndicators: "技术指标",
    rsiIndicator: "RSI (14) 指标",
    macdIndicator: "MACD 指标",
    macdLine: "MACD 线",
    signalLine: "信号线",
    histogram: "柱状图",
    aiProbPricing: "AI 概率定价",
    aiProbability: "AI 概率",
    buyTarget: "买入目标",
    sellTarget: "卖出目标",
    decisionMatrix: "决策矩阵",
    buy: "买入",
    hold: "持有",
    sell: "卖出",
    aiRecommendation: "AI 建议",
    deepDive: "AI 深度分析",
    bullCase: "牛市论点（正面驱动因素）",
    bearCase: "熊市论点（风险因素）",
    financialSnapshot: "财务概况",
    healthScoreTitle: "财务健康综合评分",
    healthExcellent: "优秀",
    healthGood: "良好",
    healthFair: "普通",
    healthWeak: "偏弱",
    healthAdviceExcellent: "各维度基本面强劲——适合高信心长期持有。",
    healthAdviceGood: "整体健康稳健，少数方面需关注——对大多数投资组合是可靠选择。",
    healthAdviceFair: "财务信号喜忧参半——投入大量资金前需做更深入研究。",
    healthAdviceWeak: "侦测到多项财务隐忧——风险较高，仅适合投机性持仓。",
    debtLabel: "负债权益比",
    cashFlowLabel: "现金流趋势",
    cashFlowUp: "上升",
    cashFlowStable: "稳定",
    cashFlowDown: "下降",
    dividendYield: "股息收益率",
    volatilityIndex: "波动指数",
    strategicAdvice: "策略建议",
    conservative: "稳健型投资者：",
    value: "价值型投资者：",
    sentiment: "算法情绪",
    trendStrength: "趋势强度",
    addWatchlist: "加入自选",
    savedToWatchlist: "⭐ 已保存",
    selfDecision: "自主决策原则",
    finalDisclaimer: "本报告由数学 AI 模型生成，仅供教育和认知刺激之用。创办人不持有任何专业或博弈牌照。此非财务建议。",
    confidential: "机密 — 仅限预期收件人",
    executiveThesisTitle: "执行投资论点",
    sectorLabel: "板块",
    industryLabel: "行业",
    keyMultiples: "主要财务指标",
    marketCap: "市值",
    peRatio: "市盈率",
    roeLabel: "股本回报率",
    riskTitle: "投资风险评估",
    riskTierLabel: "风险等级",
    riskTierConservative: "稳健型",
    riskTierGrowth: "成长型",
    riskTierHighRisk: "高风险型",
    riskTierAdviceConservative: "本标的波动较低，适合作为核心持仓，回报相对稳定。",
    riskTierAdviceGrowth: "本标的波动适中，建议占总仓位不超过 10-15%。",
    riskTierAdviceHighRisk: "本标的波动较大，建议占总仓位不超过 5%。",
    riskMarket: "市场风险",
    riskMarketDesc: "影响所有股票的大盘波动风险",
    riskCompany: "个股风险",
    riskCompanyDesc: "此公司或其板块特有的风险",
    riskModel: "AI 模型限制",
    riskModelDesc: "本分析所用数学模型的局限性",
    riskSelfDecision: "自主决策原则",
    riskSelfDecisionBody: "AI 概率评分是基于历史数据的数学推算——并非获利或亏损的保证。请务必自行做出明智决定，并在投资前咨询持牌财务顾问。",
    footnote1: "本文件由 DragonGPAi.com 制作，仅供参考之用，不构成任何买卖证券的要约、招揽或建议。",
    footnote2: "本分析基于数学概率模型及公开市场数据。DragonGPAi.com 不持有任何专业财务顾问或博弈牌照。",
    footnote3: "过往表现并非未来表现的指标。所有投资均存在风险，包括可能损失本金。",
    priceVsIndex: "12个月股价 vs 指数表现",
    reportFooter: "报告由 DragonGPAi.com 制作，由 Gemini 提供支持",
    noAdvice: "维持现有仓位，严格风险管理。",
    noValueAdvice: "等待更清晰的价值信号再做决策。",
    loading: "正在加载报告数据...",
    printPDF: "打印",
    savePDF: "保存为文字",
    downloadPDF: "下载 PDF",
    share: "分享",
    textToVoice: "文字转语音",
    textToVoiceDesc: "点击上方的 🔊 朗读分析 按钮收听此报告。AI 将以您选择的语言朗读完整分析，包括价格、RSI、MACD 和建议。",
    textToVoiceSpeaking: "🔊 AI 正在朗读报告...",
    shareFacebook: "分享到 Facebook",
    shareWhatsApp: "分享到 WhatsApp",
    shareTwitter: "分享到 Twitter",
    shareLinkedIn: "分享到 LinkedIn",
    copyReport: "复制报告",
    copied: "已复制！",
    goToMark6: "立即前往 AI 六合彩概率游戏",
    selectAnother: "下一只",
    scrollDown: "向下滚动查看完整报告 / Scroll Down for Full Report",
    aiAnalysisLogic: "AI 分析逻辑",
    rsiExplanation: "衡量股票是否超买或超卖。",
    macdExplanation: "衡量当前趋势的强度与方向。",
    saveToWatchlist: "加入自选股",
    watchlistCTA: "想加入您的自选股名单吗？(最多10个)",
    watchlistFull: "自选股名单已满，请先删除一个。",
    marketDepth: "市场深度",
    bid: "买盘",
    ask: "卖盘",
    dayRange: "日内范围",
    prevClose: "前收盘价",
    marketOpen: "交易中",
    marketClosed: "已收盘",
    companyProfile: "公司简介",
    noDividends: "不派息",
    readReport: "朗读分析",
    speaking: "朗读中...",
    paused: "暂停",
    ready: "就绪",
    play: "播放",
    pauseCtrl: "暂停",
    stop: "停止",
    buySignal: "RSI(14) 为 {value}，处于超卖区间。这通常被视为买入信号，显示该股可能被低估，有望反弹。",
    sellSignal: "RSI(14) 为 {value}，处于超买区间。这通常被视为卖出信号，显示该股可能被高估，有望回调。",
    voiceTranscript: "📢 AI 语音分析转录",
  },
};

export interface ReportData {
  ticker: string;
  companyName?: string;
  date: string;
  price: string;
  priceChange: string;
  priceUp: boolean;
  weekHigh: string;
  weekLow: string;
  volume: string;
  rsi: number;
  rsiStatus: string;
  macdLine: string;
  signalLine: string;
  histogram: string;
  macdStatus: string;
  probability: number;
  buyTarget: string;
  sellTarget: string;
  buyPct: number;
  holdPct: number;
  sellPct: number;
  recommendation: string;
  bullPoints: string[];
  bearPoints: string[];
  dividendYield: string;
  volatility: string;
  conservativeAdvice: string;
  valueAdvice: string;
  sentimentScore: number;
  trendStrength: number;
  executiveThesis: string;
  sector: string;
  industry: string;
  marketCap: string;
  peRatio: string;
  roe: string;
  riskAssessment: {
    market: string[];
    company: string[];
    model: string[];
  };
  financialHealthScore: number;
  debtToEquity: number;
  cashFlowTrend: "up" | "stable" | "down";
  bid: number;
  ask: number;
  bidSize: number;
  askSize: number;
  dayRange: string;
  marketState: string;
  currencySymbol: string;
  previousCloseVolume: string;
  companyDescription: string;
  news: StockNewsItem[];
  upcomingDividend?: { amount: string; exDate: string } | null;
  confidenceScore?: number;
  trend?: string;
}

/* ── Section helpers ──────────────────────────── */
const Section = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => (
  <div className={`py-3 ${className}`} style={{ pageBreakInside: "avoid", breakInside: "avoid" }}>
    {children}
  </div>
);

const SectionTitle = ({ children }: { children: React.ReactNode }) => (
  <h3
    className="text-[13px] font-bold tracking-wide uppercase pb-1.5 mb-2"
    style={{
      fontFamily: "'Playfair Display', Georgia, 'Times New Roman', serif",
      color: "#1e293b",
      borderBottom: "2px solid #1e293b",
    }}
  >
    {children}
  </h3>
);

interface Props {
  report: ReportData;
  lang: LangKey;
  inWatchlist: boolean;
  onAddWatchlist: () => void;
  onSpeakAnalysis?: () => void;
  isSpeaking?: boolean;
}

const StockReport = ({ report, lang, inWatchlist, onAddWatchlist }: Props) => {
  const l = translations[lang] || translations.en;
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const [isCopied, setIsCopied] = useState(false);
  const [isReading, setIsReading] = useState(false);
  // Change this (around line 220):
const [voiceText, setVoiceText] = useState(''); // ← Keep this as empty string
  const { speak, stop, isSpeaking: speechIsSpeaking, isSupported } = useSpeech({
    lang: lang === 'zh-TW' ? 'zh-HK' : lang === 'zh-CN' ? 'zh-CN' : 'en-US',
    rate: 0.9,
  });

  const conservativeAdvice = report.conservativeAdvice && report.conservativeAdvice !== 'N/A'
    ? report.conservativeAdvice
    : l.noAdvice;

  const valueAdvice = report.valueAdvice && report.valueAdvice !== 'N/A'
    ? report.valueAdvice
    : l.noValueAdvice;

  const formatValue = (value: any, fallback: string = 'N/A') => {
    if (value === undefined || value === null || value === '' || value === 'N/A') {
      return fallback;
    }
    return value;
  };

  const currencySymbol = report.currencySymbol || '$';

  // ── Generate Voice Text with 8 Sections ──
  const generateVoiceText = (): string => {
    const isChinese = lang === 'zh-TW' || lang === 'zh-CN';
    const parts: string[] = [];

    // 1. Summary
    parts.push(isChinese
      ? `【摘要】${report.companyName || report.ticker} 目前價格 ${report.price}，${report.priceUp ? '上漲' : '下跌'} ${report.priceChange}。AI 預測概率 ${report.probability}%，建議 ${report.recommendation}。`
      : `[Summary] ${report.companyName || report.ticker} is currently trading at ${report.price}, ${report.priceUp ? 'up' : 'down'} ${report.priceChange}. AI probability is ${report.probability}% with a ${report.recommendation} recommendation.`
    );

    // 2. Technical Analysis
    parts.push(isChinese
      ? `【技術分析】RSI 指標為 ${report.rsi.toFixed(1)}，${report.rsiStatus}。MACD 顯示 ${report.macdStatus} 信號。`
      : `[Technical Analysis] RSI is ${report.rsi.toFixed(1)}, indicating ${report.rsiStatus}. MACD shows a ${report.macdStatus} signal.`
    );

    // 3. Fundamental Analysis
    parts.push(isChinese
      ? `【基本面分析】市值 ${report.marketCap}，市盈率 ${report.peRatio}，股本回報率 ${report.roe}%。`
      : `[Fundamental Analysis] Market cap is ${report.marketCap} with a P/E ratio of ${report.peRatio} and ROE of ${report.roe}%.`
    );

    // 4. News Sentiment
    const sentimentText = report.sentimentScore > 60 ? (isChinese ? '正面' : 'positive') :
                          report.sentimentScore > 40 ? (isChinese ? '中性' : 'neutral') :
                          (isChinese ? '負面' : 'negative');
    parts.push(isChinese
      ? `【新聞情緒】整體情緒為 ${sentimentText}，信心指數 ${report.sentimentScore}%。`
      : `[News Sentiment] Overall sentiment is ${sentimentText} with a confidence score of ${report.sentimentScore}%.`
    );

    // 5. Risk Analysis
    // 5. Risk Analysis
const riskLevel = report.volatility.includes('High') ? (isChinese ? '高' : 'High') :
                  report.volatility.includes('Moderate') ? (isChinese ? '中等' : 'Moderate') :
                  (isChinese ? '低' : 'Low');
    parts.push(isChinese
      ? `【風險分析】波動率 ${riskLevel}，風險等級 ${report.riskTierLabel || '中等'}。`
      : `[Risk Analysis] Volatility is ${riskLevel} with a ${report.riskTierLabel || 'Moderate'} risk tier.`
    );

    // 6. Bull Case
    const bullText = report.bullPoints?.slice(0, 2).join(isChinese ? '；' : '; ') || (isChinese ? '看好因素包括技術面改善和市場情緒向好' : 'Bullish factors include improving technicals and positive market sentiment.');
    parts.push(isChinese
      ? `【看好因素】${bullText}`
      : `[Bull Case] ${bullText}`
    );

    // 7. Bear Case
    const bearText = report.bearPoints?.slice(0, 2).join(isChinese ? '；' : '; ') || (isChinese ? '看淡因素包括宏觀不確定性和行業競爭加劇' : 'Bearish factors include macro uncertainty and increasing competition.');
    parts.push(isChinese
      ? `【看淡因素】${bearText}`
      : `[Bear Case] ${bearText}`
    );

    // 8. Final Recommendation
    parts.push(isChinese
      ? `【最終建議】${report.recommendation}。目標價 ${report.buyTarget}，止蝕位 ${report.sellTarget}。${l.selfDecision}`
      : `[Final Recommendation] ${report.recommendation}. Target price is ${report.buyTarget} with stop loss at ${report.sellTarget}. ${l.selfDecision}`
    );

    return parts.join('。 ');
  };

  // ── Handle Voice Play ──
  const handleSpeakAnalysis = () => {
  if (speechIsSpeaking || isReading) {
    stop();
    setIsReading(false);
    return;
  }
  setIsReading(true);
  const text = generateVoiceText();
  setVoiceText(text);
  speak(text);
  setTimeout(() => {
    setIsReading(false);
  }, Math.min(text.length * 80, 30000));
};
  // ── ADD THE useEffect HERE (after handleSpeakAnalysis) ──
// 4. Auto-play useEffect
useEffect(() => {
  const timer = setTimeout(() => {
    const text = generateVoiceText();
    setVoiceText(text);
    speak(text);
    setIsReading(true);
    
    setTimeout(() => {
      setIsReading(false);
    }, Math.min(text.length * 80, 30000));
  }, 1500);
  
  return () => {
    clearTimeout(timer);
    stop();
  };
}, [report]); // ← or [] if you only want it once


  // ── Share Text Generation ──
  const getShareText = (includeFullAnalysis: boolean = false) => {
    const isChinese = lang === 'zh-TW' || lang === 'zh-CN';
    const companyName = report.companyName || report.ticker || 'N/A';
    const ticker = report.ticker || 'N/A';
    const price = report.price || 'N/A';
    const change = report.priceChange || '0.00%';
    const rsi = report.rsi !== undefined ? report.rsi.toFixed(1) : 'N/A';
    const rsiStatus = report.rsiStatus || 'Neutral';
    const probability = report.probability !== undefined ? report.probability : 50;
    const recommendation = report.recommendation || 'HOLD';
    const buyTarget = report.buyTarget || 'N/A';
    const sellTarget = report.sellTarget || 'N/A';
    const weekHigh = report.weekHigh || 'N/A';
    const weekLow = report.weekLow || 'N/A';

    const parts = [
      isChinese ? `📊 今日關注：${companyName} (${ticker})` : `📊 Stock Watch: ${companyName} (${ticker})`,
      isChinese ? `💰 股價 ${price} (${change})` : `💰 Price ${price} (${change})`,
      isChinese ? `📈 RSI(14) ${rsi} (${rsiStatus})` : `📈 RSI(14) ${rsi} (${rsiStatus})`,
      isChinese ? `🎯 AI預測概率 ${probability}%` : `🎯 AI Probability ${probability}%`,
      isChinese ? `💡 AI建議 ${recommendation}` : `💡 AI Recommendation ${recommendation}`,
      isChinese ? `🎯 目標價 ${buyTarget} | 止蝕位 ${sellTarget}` : `🎯 Target ${buyTarget} | Stop Loss ${sellTarget}`,
      isChinese ? `📆 52週區間 ${weekLow} - ${weekHigh}` : `📆 52-week Range ${weekLow} - ${weekHigh}`,
      '',
      isChinese ? `⚡ 由 DragonGP.AI 提供 AI 分析` : `⚡ Powered by DragonGP.AI`,
      isChinese ? `🔗 了解更多：https://dragongp.ai` : `🔗 Learn more: https://dragongp.ai`
    ];

    // If full analysis is requested, include the voice text
    if (includeFullAnalysis && voiceText) {
      parts.push('');
      parts.push('📝 ' + (isChinese ? '完整分析：' : 'Full Analysis:'));
      parts.push(voiceText);
    }

    return parts.join('\n');
  };
  // At the top of your component, add this useEffect to load Facebook SDK
useEffect(() => {
  // Load Facebook SDK only once
  if (typeof window !== 'undefined' && !window.fbAsyncInit) {
    window.fbAsyncInit = function() {
      FB.init({
        appId: '1741862253519730', // Replace with your actual App ID
        autoLogAppEvents: true,
        xfbml: true,
        version: 'v18.0'
      });
    };

    // Load the SDK script
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "https://connect.facebook.net/en_US/sdk.js";
      fjs.parentNode?.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  }
}, []);

// ── Share Handlers ──
// ── Share Handlers ──
const handleFacebookShare = () => {
  const voiceContent = voiceText || generateVoiceText();
  const isChinese = lang === 'zh-TW' || lang === 'zh-CN';
  const companyName = report.companyName || report.ticker || 'N/A';
  const ticker = report.ticker || 'N/A';
  const price = report.price || 'N/A';
  const change = report.priceChange || '0.00%';
  const probability = report.probability !== undefined ? report.probability : 50;
  const recommendation = report.recommendation || 'HOLD';
  const rsi = report.rsi !== undefined ? report.rsi.toFixed(1) : 'N/A';
  const rsiStatus = report.rsiStatus || 'Neutral';
  
  // Create share text with voice content
  const shareText = isChinese 
    ? `📊 今日關注：${companyName} (${ticker})\n💰 股價 ${price} (${change})\n📈 RSI(14) ${rsi} (${rsiStatus})\n🎯 AI預測概率 ${probability}%\n💡 AI建議 ${recommendation}\n\n📝 完整分析：\n${voiceContent}\n\n⚡ 由 DragonGP.AI 提供 AI 分析\n🔗 https://dragongp.ai`
    : `📊 Stock Watch: ${companyName} (${ticker})\n💰 Price ${price} (${change})\n📈 RSI(14) ${rsi} (${rsiStatus})\n🎯 AI Probability ${probability}%\n💡 AI Recommendation ${recommendation}\n\n📝 Full Analysis:\n${voiceContent}\n\n⚡ Powered by DragonGP.AI\n🔗 https://dragongp.ai`;

  // Check if Web Share API is available (mobile)
  if (navigator.share) {
    navigator.share({
      title: `${companyName} - AI Stock Analysis`,
      text: shareText,
      url: window.location.href,
    }).then(() => {
      toast.success('Shared successfully!');
    }).catch((error) => {
      if (error.name !== 'AbortError') {
        console.error('Share error:', error);
        // Fallback to Facebook sharer
        fallbackFacebookShare(shareText);
      }
    });
  } else {
    // Desktop fallback - open Facebook sharer
    fallbackFacebookShare(shareText);
  }
};

// Helper function for Facebook fallback sharing
const fallbackFacebookShare = (shareText: string) => {
  const encodedText = encodeURIComponent(shareText);
  const encodedUrl = encodeURIComponent(window.location.href);
  
  // Use Facebook sharer.php - this works on desktop
  const shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}&quote=${encodedText}`;
  
  // Open in a popup window
  const width = 626;
  const height = 436;
  const left = (window.innerWidth - width) / 2;
  const top = (window.innerHeight - height) / 2;
  
  const popup = window.open(
    shareUrl,
    'facebook-share-dialog',
    `width=${width},height=${height},left=${left},top=${top},toolbar=0,menubar=0,scrollbars=yes`
  );
  
  if (!popup) {
    // If popup is blocked, open in new tab
    window.open(shareUrl, '_blank');
  }
};

const handleWhatsAppShare = () => {
  const voiceContent = voiceText || generateVoiceText();
  const isChinese = lang === 'zh-TW' || lang === 'zh-CN';
  const companyName = report.companyName || report.ticker || 'N/A';
  const ticker = report.ticker || 'N/A';
  const price = report.price || 'N/A';
  const change = report.priceChange || '0.00%';
  const probability = report.probability !== undefined ? report.probability : 50;
  const recommendation = report.recommendation || 'HOLD';
  const rsi = report.rsi !== undefined ? report.rsi.toFixed(1) : 'N/A';
  const rsiStatus = report.rsiStatus || 'Neutral';
  
  const shareText = isChinese 
    ? `📊 今日關注：${companyName} (${ticker})\n💰 股價 ${price} (${change})\n📈 RSI(14) ${rsi} (${rsiStatus})\n🎯 AI預測概率 ${probability}%\n💡 AI建議 ${recommendation}\n\n📝 完整分析：\n${voiceContent}\n\n⚡ 由 DragonGP.AI 提供 AI 分析\n🔗 https://dragongp.ai`
    : `📊 Stock Watch: ${companyName} (${ticker})\n💰 Price ${price} (${change})\n📈 RSI(14) ${rsi} (${rsiStatus})\n🎯 AI Probability ${probability}%\n💡 AI Recommendation ${recommendation}\n\n📝 Full Analysis:\n${voiceContent}\n\n⚡ Powered by DragonGP.AI\n🔗 https://dragongp.ai`;

  // Check if Web Share API is available (mobile)
  if (navigator.share) {
    navigator.share({
      title: `${companyName} - AI Stock Analysis`,
      text: shareText,
      url: window.location.href,
    }).then(() => {
      toast.success('Shared successfully!');
    }).catch((error) => {
      if (error.name !== 'AbortError') {
        console.error('Share error:', error);
        // Fallback to WhatsApp URL
        fallbackWhatsAppShare(shareText);
      }
    });
  } else {
    // Desktop fallback - open WhatsApp URL
    fallbackWhatsAppShare(shareText);
  }
};

// Helper function for WhatsApp fallback sharing
const fallbackWhatsAppShare = (shareText: string) => {
  const encodedText = encodeURIComponent(shareText);
  const whatsappUrl = `https://wa.me/?text=${encodedText}`;
  window.open(whatsappUrl, '_blank');
};

const handleTwitterShare = () => {
  const voiceContent = voiceText || generateVoiceText();
  const isChinese = lang === 'zh-TW' || lang === 'zh-CN';
  const companyName = report.companyName || report.ticker || 'N/A';
  
  const shortContent = voiceContent.substring(0, 80) + (voiceContent.length > 80 ? '...' : '');
  const shareText = isChinese
    ? `📊 ${companyName} AI分析：${shortContent} 由 DragonGP.AI 提供`
    : `📊 ${companyName} AI Analysis: ${shortContent} Powered by DragonGP.AI`;
  
  const encodedText = encodeURIComponent(shareText);
  const twitterUrl = `https://twitter.com/intent/tweet?text=${encodedText}&url=${encodeURIComponent(window.location.href)}`;
  window.open(twitterUrl, '_blank');
};

const handleLinkedInShare = () => {
  const voiceContent = voiceText || generateVoiceText();
  const isChinese = lang === 'zh-TW' || lang === 'zh-CN';
  const companyName = report.companyName || report.ticker || 'N/A';
  
  const shareText = isChinese
    ? `${companyName} (${report.ticker}) AI分析報告\n\n${voiceContent}\n\n由 DragonGP.AI 提供\nhttps://dragongpai.com`
    : `${companyName} (${report.ticker}) AI Analysis Report\n\n${voiceContent}\n\nPowered by DragonGP.AI\nhttps://dragongpai.com`;
  
  const encodedText = encodeURIComponent(shareText);
  const linkedinUrl = `https://www.linkedin.com/sharing/share-offsite/?summary=${encodedText}`;
  window.open(linkedinUrl, '_blank');
};

const handleCopyText = () => {
  const voiceContent = voiceText || generateVoiceText();
  const isChinese = lang === 'zh-TW' || lang === 'zh-CN';
  const companyName = report.companyName || report.ticker || 'N/A';
  const ticker = report.ticker || 'N/A';
  const price = report.price || 'N/A';
  const change = report.priceChange || '0.00%';
  const probability = report.probability !== undefined ? report.probability : 50;
  const recommendation = report.recommendation || 'HOLD';
  const rsi = report.rsi !== undefined ? report.rsi.toFixed(1) : 'N/A';
  const rsiStatus = report.rsiStatus || 'Neutral';
  
  const shareText = isChinese 
    ? `📊 今日關注：${companyName} (${ticker})\n💰 股價 ${price} (${change})\n📈 RSI(14) ${rsi} (${rsiStatus})\n🎯 AI預測概率 ${probability}%\n💡 AI建議 ${recommendation}\n\n📝 完整分析：\n${voiceContent}\n\n⚡ 由 DragonGP.AI 提供 AI 分析\n🔗 https://dragongpai.COM`
    : `📊 Stock Watch: ${companyName} (${ticker})\n💰 Price ${price} (${change})\n📈 RSI(14) ${rsi} (${rsiStatus})\n🎯 AI Probability ${probability}%\n💡 AI Recommendation ${recommendation}\n\n📝 Full Analysis:\n${voiceContent}\n\n⚡ Powered by DragonGP.AI\n🔗 https://dragongpai.COM`;

  navigator.clipboard.writeText(shareText).then(() => {
    setIsCopied(true);
    toast.success(l.copied || 'Copied!');
    setTimeout(() => setIsCopied(false), 3000);
  }).catch(() => {
    toast.error('Failed to copy');
  });
};

  // ── Print/PDF functions ──
  const handlePrint = () => {
    if (typeof window.print !== "function") {
      toast.error("Printing is not supported in this browser.", { duration: 5000 });
      return;
    }
    try {
      window.print();
    } catch (error) {
      console.error("Print failed:", error);
      toast.error("Print failed. Please try again.", { duration: 5000 });
    }
  };

  const [pdfLoading, setPdfLoading] = useState(false);

  const handleSavePDF = async () => {
    const element = document.getElementById("stock-report");
    if (!element) return;

    setPdfLoading(true);
    const loadingToast = toast.loading("Generating PDF...");

    try {
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#ffffff",
        logging: false,
        windowWidth: element.scrollWidth,
        windowHeight: element.scrollHeight,
      });

      const imgData = canvas.toDataURL('image/jpeg', 0.95);
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 5;
      const usableWidth = pageWidth - margin * 2;
      const imgAspect = canvas.height / canvas.width;
      const imgHeightInMM = usableWidth * imgAspect;

      pdf.addImage(imgData, 'JPEG', margin, margin, usableWidth, imgHeightInMM);
      pdf.save(`${report.ticker || "stock"}-AI-Report.pdf`);

      toast.dismiss(loadingToast);
      toast.success("PDF downloaded successfully!", { duration: 3000 });
    } catch (error) {
      console.error("PDF generation failed:", error);
      toast.dismiss(loadingToast);
      toast.error("Failed to generate PDF. Please try again.", { duration: 5000 });
    } finally {
      setPdfLoading(false);
    }
  };

  const handleSaveAsText = () => {
    const el = document.getElementById("stock-report");
    if (!el) return;
    const text = el.innerText;
    const blob = new Blob([text], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${report.ticker || "stock"}-report.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const handleSelectAnother = () => {
    window.location.reload();
  };

  // ── Get RSI Signal Text ──
  const getRSISignalText = (rsi: number): string => {
    if (rsi < 30) {
      return l.buySignal.replace('{value}', rsi.toFixed(1));
    } else if (rsi > 70) {
      return l.sellSignal.replace('{value}', rsi.toFixed(1));
    }
    return '';
  };

  // ── Report Content ──
  return (
    <div id="stock-report" className="max-w-4xl mx-auto px-4 py-6 print:px-0 print:py-0">
      {/* ── Voice Button Bar ── */}
      <div className="flex flex-wrap items-center justify-between gap-3 mb-4 print:hidden">
        <div className="flex items-center gap-2">
          <Button
            onClick={handleSpeakAnalysis}
            className={`gap-2 ${isReading || speechIsSpeaking ? 'bg-red-500 hover:bg-red-600' : 'bg-blue-600 hover:bg-blue-700'}`}
          >
            {isReading || speechIsSpeaking ? <Square className="h-4 w-4" /> : <Volume2 className="h-4 w-4" />}
            {isReading || speechIsSpeaking ? l.stop : l.readReport}
          </Button>
          {(isReading || speechIsSpeaking) && (
            <span className="text-sm text-muted-foreground animate-pulse">
              {l.speaking}
            </span>
          )}
        </div>
        <span className="text-xs text-muted-foreground">
          {lang === 'zh-TW' ? '廣東話' : lang === 'zh-CN' ? '普通話' : 'English'}
        </span>
      </div>

      {/* ── Report Header ── */}
      <div className="flex items-center gap-3 pb-3 border-b border-gray-200 print:border-gray-300">
        <img src={dragonLogo} alt="DragonGP" className="h-8 w-auto print:h-6" />
        <div className="flex-1">
          <h1 className="text-lg font-bold" style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
            {l.reportTitle}
          </h1>
          <p className="text-xs text-muted-foreground">
            {l.dateLabel}: {today}
          </p>
        </div>
        <div className="text-right text-xs text-muted-foreground">
          <span className="font-semibold">{report.ticker}</span>
          <span className="block">{l.status}</span>
        </div>
      </div>

      {/* ── Executive Thesis ── */}
      <Section>
        <SectionTitle>{l.executiveThesisTitle}</SectionTitle>
        <div className="p-4 rounded-lg bg-blue-50/50 border border-blue-100">
          <p className="text-sm leading-relaxed">{report.executiveThesis || l.noAdvice}</p>
        </div>
      </Section>

      {/* ── Market Data ── */}
      <Section>
        <SectionTitle>{l.marketData}</SectionTitle>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.livePrice}</p>
            <p className="text-lg font-bold">{currencySymbol}{report.price}</p>
            <p className={`text-xs ${report.priceUp ? 'text-green-600' : 'text-red-600'}`}>
              {report.priceChange}
            </p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.weekHigh}</p>
            <p className="text-lg font-bold text-green-600">{currencySymbol}{report.weekHigh}</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.weekLow}</p>
            <p className="text-lg font-bold text-red-600">{currencySymbol}{report.weekLow}</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.volume}</p>
            <p className="text-lg font-bold">{report.volume}</p>
          </div>
        </div>
      </Section>

      {/* ── Sector & Industry ── */}
      {(report.sector || report.industry) && (
        <div className="flex flex-wrap gap-2 py-2">
          {report.sector && (
            <span className="px-3 py-1 text-xs rounded-full bg-blue-100 text-blue-800 font-medium">
              {report.sector}
            </span>
          )}
          {report.industry && (
            <span className="px-3 py-1 text-xs rounded-full bg-purple-100 text-purple-800 font-medium">
              {report.industry}
            </span>
          )}
        </div>
      )}

      {/* ── Recommendation Sidebar ── */}
      <Section>
        <RecommendationSidebar
          lang={lang}
          currentPrice={report.price}
          targetPrice={report.buyTarget}
          buyPct={report.buyPct}
          holdPct={report.holdPct}
          sellPct={report.sellPct}
        />
      </Section>

      {/* ── AI Probability & Confidence ── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 py-3">
        <div className="flex flex-col items-center p-4 rounded-lg border border-gray-200 bg-gray-50/50">
          <p className="text-sm font-medium mb-2">{l.aiProbability}</p>
          <ProbabilityGauge value={report.probability} size={140} />
        </div>
        <div className="flex flex-col items-center p-4 rounded-lg border border-gray-200 bg-gray-50/50">
          <AnalystConfidenceGauge value={report.confidenceScore || 65} lang={lang} />
        </div>
      </div>

      {/* ── Decision Matrix ── */}
      <Section>
        <SectionTitle>{l.decisionMatrix}</SectionTitle>
        <div className="flex h-6 rounded-full overflow-hidden border border-gray-200">
          <div className="flex items-center justify-center text-white text-xs font-bold" style={{ width: `${report.buyPct}%`, background: '#15803d' }}>
            {report.buyPct > 10 ? `${report.buyPct}%` : ''}
          </div>
          <div className="flex items-center justify-center text-white text-xs font-bold" style={{ width: `${report.holdPct}%`, background: '#b45309' }}>
            {report.holdPct > 10 ? `${report.holdPct}%` : ''}
          </div>
          <div className="flex items-center justify-center text-white text-xs font-bold" style={{ width: `${report.sellPct}%`, background: '#dc2626' }}>
            {report.sellPct > 10 ? `${report.sellPct}%` : ''}
          </div>
        </div>
        <div className="flex justify-between text-xs font-medium mt-1">
          <span className="text-green-600">{l.buy} {report.buyPct}%</span>
          <span className="text-amber-600">{l.hold} {report.holdPct}%</span>
          <span className="text-red-600">{l.sell} {report.sellPct}%</span>
        </div>
      </Section>

      {/* ── AI Recommendation ── */}
      <Section>
        <SectionTitle>{l.aiRecommendation}</SectionTitle>
        <div className="p-4 rounded-lg border border-gray-200 bg-gray-50/50">
          <p className="text-sm font-medium">{report.recommendation}</p>
          {report.rsi !== undefined && getRSISignalText(report.rsi) && (
            <p className="text-xs text-muted-foreground mt-1">{getRSISignalText(report.rsi)}</p>
          )}
        </div>
      </Section>

      {/* ── Technical Indicators ── */}
      <Section>
        <SectionTitle>{l.techIndicators}</SectionTitle>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div className="p-3 rounded-lg border border-gray-200">
            <p className="text-xs font-medium">{l.rsiIndicator}</p>
            <p className="text-xl font-bold">{report.rsi.toFixed(1)}</p>
            <p className="text-xs text-muted-foreground">{report.rsiStatus}</p>
          </div>
          <div className="p-3 rounded-lg border border-gray-200">
            <p className="text-xs font-medium">{l.macdIndicator}</p>
            <p className="text-xl font-bold">{report.macdStatus}</p>
            <p className="text-xs text-muted-foreground">{report.macdLine}</p>
          </div>
          <div className="p-3 rounded-lg border border-gray-200">
            <p className="text-xs font-medium">{l.trendStrength}</p>
            <p className="text-xl font-bold">{report.trendStrength}%</p>
            <p className="text-xs text-muted-foreground">{l.sentiment}</p>
          </div>
        </div>
      </Section>

      {/* ── Price vs Index Chart ── */}
      <Section>
        <PriceVsIndexChart lang={lang} ticker={report.ticker} companyName={report.companyName} />
      </Section>

      {/* ── Company Profile ── */}
      <CompanyProfile
        lang={lang}
        companyName={report.companyName || report.ticker}
        description={report.companyDescription || ''}
        sector={report.sector}
        industry={report.industry}
      />

      {/* ── Market Depth ── */}
      <MarketDepthSection
        lang={lang}
        bid={report.bid}
        ask={report.ask}
        bidSize={report.bidSize}
        askSize={report.askSize}
        dayRange={report.dayRange}
        volume={report.volume}
        marketState={report.marketState}
        currencySymbol={currencySymbol}
        previousCloseVolume={report.previousCloseVolume}
      />

      {/* ── Peer Comparison ── */}
      <PeerComparisonTable
        lang={lang}
        targetTicker={report.ticker}
        targetCompany={report.companyName || report.ticker}
        targetPrice={report.price}
        targetMarketCap={report.marketCap}
        targetPE={report.peRatio}
        targetROE={report.roe}
        targetDivYield={report.dividendYield}
      />

      {/* ── News ── */}
      <NewsSection lang={lang} news={report.news} />

      {/* ── Bull & Bear Cases ── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 py-3">
        <div className="p-4 rounded-lg border border-green-200 bg-green-50/30">
          <h4 className="text-sm font-bold text-green-700 flex items-center gap-2">
            <TrendingUp className="h-4 w-4" />
            {l.bullCase}
          </h4>
          <ul className="mt-2 space-y-1 text-sm text-gray-700">
            {report.bullPoints?.map((point, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-green-500">•</span>
                {point}
              </li>
            )) || <li>{l.noAdvice}</li>}
          </ul>
        </div>
        <div className="p-4 rounded-lg border border-red-200 bg-red-50/30">
          <h4 className="text-sm font-bold text-red-700 flex items-center gap-2">
            <TrendingDown className="h-4 w-4" />
            {l.bearCase}
          </h4>
          <ul className="mt-2 space-y-1 text-sm text-gray-700">
            {report.bearPoints?.map((point, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-red-500">•</span>
                {point}
              </li>
            )) || <li>{l.noAdvice}</li>}
          </ul>
        </div>
      </div>

      {/* ── Financial Snapshot ── */}
      <Section>
        <SectionTitle>{l.financialSnapshot}</SectionTitle>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.marketCap}</p>
            <p className="text-sm font-bold">{report.marketCap}</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.peRatio}</p>
            <p className="text-sm font-bold">{report.peRatio}</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.roeLabel}</p>
            <p className="text-sm font-bold">{report.roe}%</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.dividendYield}</p>
            <p className="text-sm font-bold">{report.dividendYield}</p>
          </div>
        </div>
      </Section>

      {/* ── Risk Assessment ── */}
      <Section>
        <SectionTitle>{l.riskTitle}</SectionTitle>
        <div className="space-y-3">
          <div className="p-3 rounded-lg border border-gray-200 bg-gray-50/50">
            <p className="text-sm font-medium">{l.riskMarket}</p>
            <p className="text-xs text-muted-foreground">{l.riskMarketDesc}</p>
            <ul className="mt-1 space-y-0.5 text-xs text-gray-600">
              {report.riskAssessment?.market?.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-gray-400">•</span>
                  {item}
                </li>
              )) || <li>{l.noAdvice}</li>}
            </ul>
          </div>
          <div className="p-3 rounded-lg border border-gray-200 bg-gray-50/50">
            <p className="text-sm font-medium">{l.riskCompany}</p>
            <p className="text-xs text-muted-foreground">{l.riskCompanyDesc}</p>
            <ul className="mt-1 space-y-0.5 text-xs text-gray-600">
              {report.riskAssessment?.company?.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-gray-400">•</span>
                  {item}
                </li>
              )) || <li>{l.noAdvice}</li>}
            </ul>
          </div>
          <div className="p-3 rounded-lg border border-gray-200 bg-gray-50/50">
            <p className="text-sm font-medium">{l.riskModel}</p>
            <p className="text-xs text-muted-foreground">{l.riskModelDesc}</p>
            <ul className="mt-1 space-y-0.5 text-xs text-gray-600">
              {report.riskAssessment?.model?.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-gray-400">•</span>
                  {item}
                </li>
              )) || <li>{l.noAdvice}</li>}
            </ul>
          </div>
          <div className="p-3 rounded-lg border border-amber-200 bg-amber-50/30">
            <p className="text-sm font-medium text-amber-800">{l.riskSelfDecision}</p>
            <p className="text-xs text-amber-700">{l.riskSelfDecisionBody}</p>
          </div>
        </div>
      </Section>

      {/* ── Voice Transcript Section ── */}
      {voiceText && (
        <Section>
          <SectionTitle>{l.voiceTranscript}</SectionTitle>
          <div className="p-4 rounded-lg bg-blue-50/50 border border-blue-200 text-sm leading-relaxed whitespace-pre-wrap">
            {voiceText}
          </div>
        </Section>
      )}

      {/* ── Disclaimer ── */}
      <div className="py-3 text-xs text-muted-foreground space-y-1 border-t border-gray-200 mt-4 print:mt-2">
        <p>{l.finalDisclaimer}</p>
        <p className="text-[10px]">{l.confidential}</p>
        <p className="text-[10px]">{l.footnote1}</p>
        <p className="text-[10px]">{l.footnote2}</p>
        <p className="text-[10px]">{l.footnote3}</p>
      </div>

      {/* ── Action Bar ── */}
      <div className="flex flex-wrap items-center justify-center gap-2 py-4 print:hidden border-t border-gray-200 mt-4">
        <Button variant="outline" size="sm" onClick={handleSelectAnother}>
          <ArrowLeft className="h-4 w-4 mr-1" />
          {l.selectAnother}
        </Button>

        <Button variant="outline" size="sm" onClick={handlePrint}>
          <Printer className="h-4 w-4 mr-1" />
          {l.printPDF}
        </Button>

        <Button variant="outline" size="sm" onClick={handleSaveAsText}>
          <Download className="h-4 w-4 mr-1" />
          {l.savePDF}
        </Button>

        <Button variant="outline" size="sm" onClick={handleSavePDF} disabled={pdfLoading}>
          {pdfLoading ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <FileDown className="h-4 w-4 mr-1" />}
          {pdfLoading ? l.downloading : l.downloadPDF}
        </Button>

        {!inWatchlist && onAddWatchlist && (
          <Button variant="outline" size="sm" onClick={onAddWatchlist} className="text-amber-600 border-amber-300 hover:bg-amber-50">
            <Star className="h-4 w-4 mr-1 fill-amber-400 text-amber-400" />
            {l.addWatchlist}
          </Button>
        )}
      </div>

      {/* ── Share Buttons ── */}
      <div className="flex flex-wrap items-center justify-center gap-2 py-2 print:hidden border-t border-gray-200">
        <span className="text-xs text-muted-foreground mr-1">{l.share}:</span>
        <button onClick={handleFacebookShare} className="p-1.5 rounded hover:bg-gray-100 transition-colors" title={l.shareFacebook}>
          <Facebook className="h-4 w-4 text-[#1877F2]" />
        </button>
        <button onClick={handleWhatsAppShare} className="p-1.5 rounded hover:bg-gray-100 transition-colors" title={l.shareWhatsApp}>
          <MessageCircle className="h-4 w-4 text-[#25D366]" />
        </button>
        <button onClick={handleTwitterShare} className="p-1.5 rounded hover:bg-gray-100 transition-colors" title={l.shareTwitter}>
          <Twitter className="h-4 w-4 text-[#000000]" />
        </button>
        <button onClick={handleLinkedInShare} className="p-1.5 rounded hover:bg-gray-100 transition-colors" title={l.shareLinkedIn}>
          <Linkedin className="h-4 w-4 text-[#0A66C2]" />
        </button>
        <button onClick={handleCopyText} className="p-1.5 rounded hover:bg-gray-100 transition-colors" title={l.copyReport}>
          {isCopied ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
        </button>
      </div>

      {/* ── Go to Mark6 ── */}
      <div className="py-3 print:hidden">
        <Link
          to="/ai-games"
          className="flex items-center justify-center gap-2 w-full py-3 px-4 bg-gradient-to-r from-amber-500 to-yellow-500 text-white font-bold rounded-xl hover:opacity-90 transition-opacity"
        >
          <Sparkles className="h-5 w-5" />
          {l.goToMark6}
        </Link>
      </div>
    </div>
  );
};

export default StockReport;