// src/components/ai-stocks/StockReport.tsx
import { useState, useEffect, useRef } from "react";
import {
  Star,
  Shield,
  TrendingUp,
  TrendingDown,
  Activity,
  BarChart3,
  Volume2,
  Printer,
  FileDown,
  Share2,
  Facebook,
  Copy,
  Check,
  ArrowLeft,
  Sparkles,
  AlertTriangle,
  ChevronDown,
  Heart,
  ArrowRight,
  Play,
  Pause,
  Square,
  Twitter,
  Linkedin,
  MessageCircle,
  Download,
  Loader2
} from "lucide-react";
import type { LangKey } from "@/contexts/LanguageContext";
import type { StockNewsItem } from "@/hooks/useStockData";
import { Button } from "@/components/ui/button";
import ProbabilityGauge from "./ProbabilityGauge";
import PeerComparisonTable from "./PeerComparisonTable";
import RecommendationSidebar from "./RecommendationSidebar";
import AnalystConfidenceGauge from "./AnalystConfidenceGauge";
import MarketDepthSection from "./MarketDepthSection";
import CompanyProfile from "./CompanyProfile";
import NewsSection from "./NewsSection";
import dragonLogo from "@/assets/dragon-logo.png";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { toast } from "sonner";
import { Link } from "react-router-dom";
import { useWatchlist } from "@/hooks/useWatchlist";
import { useSpeech } from "@/hooks/useSpeech";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from "recharts";
import ReportActionBar from "@/components/ai-stocks/ReportActionBar";

/* ── Trilingual labels ───────────────────────── */
const translations = {
  en: {
    reportTitle: "AI Stock Probability Report",
    subject: "Subject",
    dateLabel: "Date of Analysis",
    status: "Cognitive Engagement Exercise",
    marketData: "Market Data",
    livePrice: "Live Price",
    weekHigh: "52-Week High",
    weekLow: "52-Week Low",
    volume: "Volume",
    techIndicators: "Technical Indicators",
    rsiIndicator: "RSI (14) Indicator",
    macdIndicator: "MACD Indicator",
    macdLine: "MACD Line",
    signalLine: "Signal Line",
    histogram: "Histogram",
    aiProbPricing: "AI Probability Pricing",
    aiProbability: "AI Probability",
    buyTarget: "Buy Target",
    sellTarget: "Sell Target",
    decisionMatrix: "Decision Matrix",
    buy: "Buy",
    hold: "Hold",
    sell: "Sell",
    aiRecommendation: "AI Recommendation",
    deepDive: "AI Deep-Dive Analysis",
    bullCase: "The Bull Case (Positive Drivers)",
    bearCase: "The Bear Case (Risk Factors)",
    financialSnapshot: "Financial Snapshot",
    healthScoreTitle: "Financial Health Score",
    healthExcellent: "Excellent",
    healthGood: "Good",
    healthFair: "Fair",
    healthWeak: "Weak",
    healthAdviceExcellent: "Strong fundamentals across all dimensions — suitable for long-term holding with high conviction.",
    healthAdviceGood: "Solid overall health with minor areas to monitor — a dependable choice for most portfolios.",
    healthAdviceFair: "Mixed financial signals — conduct deeper research before committing significant capital.",
    healthAdviceWeak: "Multiple financial concerns detected — higher risk, only suitable for speculative positions.",
    debtLabel: "Debt-to-Equity",
    cashFlowLabel: "Cash Flow Trend",
    cashFlowUp: "Increasing",
    cashFlowStable: "Stable",
    cashFlowDown: "Declining",
    dividendYield: "Dividend Yield",
    volatilityIndex: "Volatility Index",
    strategicAdvice: "Strategic Advice",
    conservative: "Conservative Investor:",
    value: "Value Investor:",
    sentiment: "Algorithmic Sentiment",
    trendStrength: "Trend Strength",
    addWatchlist: "Save to Watchlist",
    savedToWatchlist: "⭐ Saved",
    selfDecision: "Principle of Self-Decision",
    finalDisclaimer: "This report is generated by a mathematical AI model for educational and mental stimulation purposes only. The founder holds No Professional or Gambling Licenses. This is not financial advice.",
    confidential: "CONFIDENTIAL — For Intended Recipient Only",
    executiveThesisTitle: "Executive Investment Thesis",
    sectorLabel: "Sector",
    industryLabel: "Industry",
    keyMultiples: "Key Financial Multiples",
    marketCap: "Market Cap",
    peRatio: "P/E Ratio",
    roeLabel: "ROE",
    riskTitle: "Investment Risk Assessment",
    riskTierLabel: "Risk Tier",
    riskTierConservative: "Conservative",
    riskTierGrowth: "Growth",
    riskTierHighRisk: "High Risk",
    riskTierAdviceConservative: "This stock has low volatility — suitable as a core holding with stable returns.",
    riskTierAdviceGrowth: "This stock has moderate volatility — consider limiting to 10-15% of your total portfolio.",
    riskTierAdviceHighRisk: "This stock has high volatility — consider limiting to no more than 5% of your total portfolio.",
    riskMarket: "Market Risk",
    riskMarketDesc: "Risks from broad market movements that affect all stocks",
    riskCompany: "Company-Specific Risk",
    riskCompanyDesc: "Risks unique to this particular company or its sector",
    riskModel: "AI Model Limitations",
    riskModelDesc: "Limitations of the mathematical model used in this analysis",
    riskSelfDecision: "Principle of Self-Decision",
    riskSelfDecisionBody: "AI probability scores are mathematical calculations based on historical data — they are NOT guarantees of profit or loss. Always make your own informed decision and consult a licensed financial advisor before investing.",
    footnote1: "This document is produced by DragonGPAi.com for informational purposes only and does not constitute an offer, solicitation, or recommendation to buy or sell any security.",
    footnote2: "The analysis herein is based on mathematical probability models and publicly available market data. DragonGPAi.com holds no professional financial advisory or gambling licenses.",
    footnote3: "Past performance is not indicative of future results. All investments carry risk, including the possible loss of principal.",
    priceVsIndex: "12-Month Price vs. Index Performance",
    reportFooter: "Report created by DragonGPAi.com, powered by Gemini",
    noAdvice: "Maintain existing positions with tight risk management.",
    noValueAdvice: "Wait for clearer value signals before making decisions.",
    loading: "Loading report data...",
    printPDF: "Print",
    savePDF: "Save as Text",
    downloadPDF: "Download PDF",
    share: "Share",
    textToVoice: "Text-to-Voice",
    textToVoiceDesc: "Click the 🔊 Read Analysis button above to listen to this report. The AI will read the full analysis including price, RSI, MACD, and recommendations in your selected language.",
    textToVoiceSpeaking: "🔊 AI is now reading the report aloud...",
    shareFacebook: "Share on Facebook",
    shareWhatsApp: "Share on WhatsApp",
    shareTwitter: "Share on Twitter",
    shareLinkedIn: "Share on LinkedIn",
    copyReport: "Copy Report",
    copied: "Copied!",
    goToMark6: "Go to AI Mark6 Probability Game Now",
    selectAnother: "Next Select",
    scrollDown: "Scroll Down for Full Report / 向下移動查看完整報告",
    aiAnalysisLogic: "AI Analysis Logic",
    rsiExplanation: "Measures if the stock is overextended (overbought/oversold).",
    macdExplanation: "Measures the strength and direction of the current trend.",
    saveToWatchlist: "Save to Watchlist",
    watchlistCTA: "Want to add to your Watch List? (Max 10)",
    watchlistFull: "Watch List full. Please remove a stock first.",
    marketDepth: "Market Depth",
    bid: "Bid",
    ask: "Ask",
    dayRange: "Day Range",
    prevClose: "Prev. Close",
    marketOpen: "Market Open",
    marketClosed: "Market Closed",
    companyProfile: "Company Profile",
    noDividends: "No Dividends",
    readReport: "Read Analysis",
    speaking: "Speaking...",
    paused: "Paused",
    ready: "Ready",
    play: "Play",
    pauseCtrl: "Pause",
    stop: "Stop",
    buySignal: "RSI(14) at {value} indicates oversold conditions. This is typically considered a BUY signal, suggesting the stock may be undervalued and due for a rebound.",
    sellSignal: "RSI(14) at {value} indicates overbought conditions. This is typically considered a SELL signal, suggesting the stock may be overvalued and due for a pullback.",
    voiceTranscript: "📢 AI Voice Analysis Transcript",
    downloading: "Downloading...",
    voiceSummary: "Summary",
    voiceTechnical: "Technical Analysis",
    voiceFundamental: "Fundamental Analysis",
    voiceSentiment: "News Sentiment",
    voiceRisk: "Risk Analysis",
    voiceBull: "Bull Case",
    voiceBear: "Bear Case",
    voiceFinal: "Final Recommendation",
  },
  "zh-TW": {
    reportTitle: "AI 股票概率報告",
    subject: "標的",
    dateLabel: "分析日期",
    status: "認知參與練習",
    marketData: "市場數據",
    livePrice: "現價",
    weekHigh: "52週高",
    weekLow: "52週低",
    volume: "成交量",
    techIndicators: "技術指標",
    rsiIndicator: "RSI (14) 指標",
    macdIndicator: "MACD 指標",
    macdLine: "MACD 線",
    signalLine: "信號線",
    histogram: "柱狀圖",
    aiProbPricing: "AI 概率定價",
    aiProbability: "AI 概率",
    buyTarget: "買入目標",
    sellTarget: "賣出目標",
    decisionMatrix: "決策矩陣",
    buy: "買入",
    hold: "持有",
    sell: "賣出",
    aiRecommendation: "AI 建議",
    deepDive: "AI 深度分析",
    bullCase: "牛市論點（正面驅動因素）",
    bearCase: "熊市論點（風險因素）",
    financialSnapshot: "財務概況",
    healthScoreTitle: "財務健康綜合評分",
    healthExcellent: "優秀",
    healthGood: "良好",
    healthFair: "普通",
    healthWeak: "偏弱",
    healthAdviceExcellent: "各維度基本面強勁——適合高信心長期持有。",
    healthAdviceGood: "整體健康穩健，少數方面需關注——對大多數投資組合是可靠選擇。",
    healthAdviceFair: "財務信號喜憂參半——投入大量資金前需做更深入研究。",
    healthAdviceWeak: "偵測到多項財務隱憂——風險較高，僅適合投機性持倉。",
    debtLabel: "負債權益比",
    cashFlowLabel: "現金流趨勢",
    cashFlowUp: "上升",
    cashFlowStable: "穩定",
    cashFlowDown: "下降",
    dividendYield: "股息收益率",
    volatilityIndex: "波動指數",
    strategicAdvice: "策略建議",
    conservative: "穩健型投資者：",
    value: "價值型投資者：",
    sentiment: "算法情緒",
    trendStrength: "趨勢強度",
    addWatchlist: "加入自選",
    savedToWatchlist: "⭐ 已儲存",
    selfDecision: "自主決策原則",
    finalDisclaimer: "本報告由數學 AI 模型生成，僅供教育和認知刺激之用。創辦人不持有任何專業或博弈牌照。此非財務建議。",
    confidential: "機密 — 僅限預期收件人",
    executiveThesisTitle: "執行投資論點",
    sectorLabel: "板塊",
    industryLabel: "行業",
    keyMultiples: "主要財務指標",
    marketCap: "市值",
    peRatio: "市盈率",
    roeLabel: "股本回報率",
    riskTitle: "投資風險評估",
    riskTierLabel: "風險等級",
    riskTierConservative: "穩健型",
    riskTierGrowth: "成長型",
    riskTierHighRisk: "高風險型",
    riskTierAdviceConservative: "本標的波動較低，適合作為核心持倉，回報相對穩定。",
    riskTierAdviceGrowth: "本標的波動適中，建議佔總倉位不超過 10-15%。",
    riskTierAdviceHighRisk: "本標的波動較大，建議佔總倉位不超過 5%。",
    riskMarket: "市場風險",
    riskMarketDesc: "影響所有股票的大盤波動風險",
    riskCompany: "個股風險",
    riskCompanyDesc: "此公司或其板塊特有的風險",
    riskModel: "AI 模型限制",
    riskModelDesc: "本分析所用數學模型的局限性",
    riskSelfDecision: "自主決策原則",
    riskSelfDecisionBody: "AI 概率評分是基於歷史數據的數學推算——並非獲利或虧損的保證。請務必自行做出明智決定，並在投資前諮詢持牌財務顧問。",
    footnote1: "本文件由 DragonGPAi.com 製作，僅供參考之用，不構成任何買賣證券的要約、招攬或建議。",
    footnote2: "本分析基於數學概率模型及公開市場數據。DragonGPAi.com 不持有任何專業財務顧問或博弈牌照。",
    footnote3: "過往表現並非未來表現的指標。所有投資均存在風險，包括可能損失本金。",
    priceVsIndex: "12個月股價 vs 指數表現",
    reportFooter: "報告由 DragonGPAi.com 製作，由 Gemini 提供支持",
    noAdvice: "維持現有倉位，嚴格風險管理。",
    noValueAdvice: "等待更清晰的價值信號再做決策。",
    loading: "正在載入報告數據...",
    printPDF: "列印",
    savePDF: "儲存為文字",
    downloadPDF: "下載 PDF",
    share: "分享",
    textToVoice: "文字轉語音",
    textToVoiceDesc: "點擊上方的 🔊 朗讀分析 按鈕收聽此報告。AI 將以您選擇的語言朗讀完整分析，包括價格、RSI、MACD 和建議。",
    textToVoiceSpeaking: "🔊 AI 正在朗讀報告...",
    shareFacebook: "分享到 Facebook",
    shareWhatsApp: "分享到 WhatsApp",
    shareTwitter: "分享到 Twitter",
    shareLinkedIn: "分享到 LinkedIn",
    copyReport: "複製報告",
    copied: "已複製！",
    goToMark6: "立即前往 AI 六合彩概率遊戲",
    selectAnother: "下一隻",
    scrollDown: "向下滾動查看完整報告 / Scroll Down for Full Report",
    aiAnalysisLogic: "AI 分析邏輯",
    rsiExplanation: "衡量股票是否超買或超賣。",
    macdExplanation: "衡量當前趨勢的強度與方向。",
    saveToWatchlist: "加入自選股",
    watchlistCTA: "想加入您的自選股名單嗎？(最多10個)",
    watchlistFull: "自選股名單已滿，請先刪除一個。",
    marketDepth: "市場深度",
    bid: "買盤",
    ask: "賣盤",
    dayRange: "日內範圍",
    prevClose: "前收盤價",
    marketOpen: "交易中",
    marketClosed: "已收盤",
    companyProfile: "公司簡介",
    noDividends: "不派息",
    readReport: "朗讀分析",
    speaking: "朗讀中...",
    paused: "暫停",
    ready: "就緒",
    play: "播放",
    pauseCtrl: "暫停",
    stop: "停止",
    buySignal: "RSI(14) 為 {value}，處於超賣區間。這通常被視為買入信號，顯示該股可能被低估，有望反彈。",
    sellSignal: "RSI(14) 為 {value}，處於超買區間。這通常被視為賣出信號，顯示該股可能被高估，有望回調。",
    voiceTranscript: "📢 AI 語音分析轉錄",
    downloading: "下載中...",
    voiceSummary: "摘要",
    voiceTechnical: "技術分析",
    voiceFundamental: "基本面分析",
    voiceSentiment: "新聞情緒",
    voiceRisk: "風險分析",
    voiceBull: "看好因素",
    voiceBear: "看淡因素",
    voiceFinal: "最終建議",
  },
  "zh-CN": {
    reportTitle: "AI 股票概率报告",
    subject: "标的",
    dateLabel: "分析日期",
    status: "认知参与练习",
    marketData: "市场数据",
    livePrice: "现价",
    weekHigh: "52周高",
    weekLow: "52周低",
    volume: "成交量",
    techIndicators: "技术指标",
    rsiIndicator: "RSI (14) 指标",
    macdIndicator: "MACD 指标",
    macdLine: "MACD 线",
    signalLine: "信号线",
    histogram: "柱状图",
    aiProbPricing: "AI 概率定价",
    aiProbability: "AI 概率",
    buyTarget: "买入目标",
    sellTarget: "卖出目标",
    decisionMatrix: "决策矩阵",
    buy: "买入",
    hold: "持有",
    sell: "卖出",
    aiRecommendation: "AI 建议",
    deepDive: "AI 深度分析",
    bullCase: "牛市论点（正面驱动因素）",
    bearCase: "熊市论点（风险因素）",
    financialSnapshot: "财务概况",
    healthScoreTitle: "财务健康综合评分",
    healthExcellent: "优秀",
    healthGood: "良好",
    healthFair: "普通",
    healthWeak: "偏弱",
    healthAdviceExcellent: "各维度基本面强劲——适合高信心长期持有。",
    healthAdviceGood: "整体健康稳健，少数方面需关注——对大多数投资组合是可靠选择。",
    healthAdviceFair: "财务信号喜忧参半——投入大量资金前需做更深入研究。",
    healthAdviceWeak: "侦测到多项财务隐忧——风险较高，仅适合投机性持仓。",
    debtLabel: "负债权益比",
    cashFlowLabel: "现金流趋势",
    cashFlowUp: "上升",
    cashFlowStable: "稳定",
    cashFlowDown: "下降",
    dividendYield: "股息收益率",
    volatilityIndex: "波动指数",
    strategicAdvice: "策略建议",
    conservative: "稳健型投资者：",
    value: "价值型投资者：",
    sentiment: "算法情绪",
    trendStrength: "趋势强度",
    addWatchlist: "加入自选",
    savedToWatchlist: "⭐ 已保存",
    selfDecision: "自主决策原则",
    finalDisclaimer: "本报告由数学 AI 模型生成，仅供教育和认知刺激之用。创办人不持有任何专业或博弈牌照。此非财务建议。",
    confidential: "机密 — 仅限预期收件人",
    executiveThesisTitle: "执行投资论点",
    sectorLabel: "板块",
    industryLabel: "行业",
    keyMultiples: "主要财务指标",
    marketCap: "市值",
    peRatio: "市盈率",
    roeLabel: "股本回报率",
    riskTitle: "投资风险评估",
    riskTierLabel: "风险等级",
    riskTierConservative: "稳健型",
    riskTierGrowth: "成长型",
    riskTierHighRisk: "高风险型",
    riskTierAdviceConservative: "本标的波动较低，适合作为核心持仓，回报相对稳定。",
    riskTierAdviceGrowth: "本标的波动适中，建议占总仓位不超过 10-15%。",
    riskTierAdviceHighRisk: "本标的波动较大，建议占总仓位不超过 5%。",
    riskMarket: "市场风险",
    riskMarketDesc: "影响所有股票的大盘波动风险",
    riskCompany: "个股风险",
    riskCompanyDesc: "此公司或其板块特有的风险",
    riskModel: "AI 模型限制",
    riskModelDesc: "本分析所用数学模型的局限性",
    riskSelfDecision: "自主决策原则",
    riskSelfDecisionBody: "AI 概率评分是基于历史数据的数学推算——并非获利或亏损的保证。请务必自行做出明智决定，并在投资前咨询持牌财务顾问。",
    footnote1: "本文件由 DragonGPAi.com 制作，仅供参考之用，不构成任何买卖证券的要约、招揽或建议。",
    footnote2: "本分析基于数学概率模型及公开市场数据。DragonGPAi.com 不持有任何专业财务顾问或博弈牌照。",
    footnote3: "过往表现并非未来表现的指标。所有投资均存在风险，包括可能损失本金。",
    priceVsIndex: "12个月股价 vs 指数表现",
    reportFooter: "报告由 DragonGPAi.com 制作，由 Gemini 提供支持",
    noAdvice: "维持现有仓位，严格风险管理。",
    noValueAdvice: "等待更清晰的价值信号再做决策。",
    loading: "正在加载报告数据...",
    printPDF: "打印",
    savePDF: "保存为文字",
    downloadPDF: "下载 PDF",
    share: "分享",
    textToVoice: "文字转语音",
    textToVoiceDesc: "点击上方的 🔊 朗读分析 按钮收听此报告。AI 将以您选择的语言朗读完整分析，包括价格、RSI、MACD 和建议。",
    textToVoiceSpeaking: "🔊 AI 正在朗读报告...",
    shareFacebook: "分享到 Facebook",
    shareWhatsApp: "分享到 WhatsApp",
    shareTwitter: "分享到 Twitter",
    shareLinkedIn: "分享到 LinkedIn",
    copyReport: "复制报告",
    copied: "已复制！",
    goToMark6: "立即前往 AI 六合彩概率游戏",
    selectAnother: "下一只",
    scrollDown: "向下滚动查看完整报告 / Scroll Down for Full Report",
    aiAnalysisLogic: "AI 分析逻辑",
    rsiExplanation: "衡量股票是否超买或超卖。",
    macdExplanation: "衡量当前趋势的强度与方向。",
    saveToWatchlist: "加入自选股",
    watchlistCTA: "想加入您的自选股名单吗？(最多10个)",
    watchlistFull: "自选股名单已满，请先删除一个。",
    marketDepth: "市场深度",
    bid: "买盘",
    ask: "卖盘",
    dayRange: "日内范围",
    prevClose: "前收盘价",
    marketOpen: "交易中",
    marketClosed: "已收盘",
    companyProfile: "公司简介",
    noDividends: "不派息",
    readReport: "朗读分析",
    speaking: "朗读中...",
    paused: "暂停",
    ready: "就绪",
    play: "播放",
    pauseCtrl: "暂停",
    stop: "停止",
    buySignal: "RSI(14) 为 {value}，处于超卖区间。这通常被视为买入信号，显示该股可能被低估，有望反弹。",
    sellSignal: "RSI(14) 为 {value}，处于超买区间。这通常被视为卖出信号，显示该股可能被高估，有望回调。",
    voiceTranscript: "📢 AI 语音分析转录",
    downloading: "下载中...",
    voiceSummary: "摘要",
    voiceTechnical: "技术分析",
    voiceFundamental: "基本面分析",
    voiceSentiment: "新闻情绪",
    voiceRisk: "风险分析",
    voiceBull: "看好因素",
    voiceBear: "看淡因素",
    voiceFinal: "最终建议",
  },
};

export interface ReportData {
  ticker: string;
  companyName?: string;
  date: string;
  price: string;
  priceChange: string;
  priceUp: boolean;
  weekHigh: string;
  weekLow: string;
  volume: string;
  rsi: number;
  rsiStatus: string;
  macdLine: string;
  signalLine: string;
  histogram: string;
  macdStatus: string;
  probability: number;
  buyTarget: string;
  sellTarget: string;
  buyPct: number;
  holdPct: number;
  sellPct: number;
  recommendation: string;
  bullPoints: string[];
  bearPoints: string[];
  dividendYield: string;
  volatility: string;
  conservativeAdvice: string;
  valueAdvice: string;
  sentimentScore: number;
  trendStrength: number;
  executiveThesis: string;
  sector: string;
  industry: string;
  marketCap: string;
  peRatio: string;
  roe: string;
  riskAssessment: {
    market: string[];
    company: string[];
    model: string[];
  };
  financialHealthScore: number;
  debtToEquity: number;
  cashFlowTrend: "up" | "stable" | "down";
  bid: number;
  ask: number;
  bidSize: number;
  askSize: number;
  dayRange: string;
  marketState: string;
  currencySymbol: string;
  previousCloseVolume: string;
  companyDescription: string;
  news: StockNewsItem[];
  upcomingDividend?: { amount: string; exDate: string } | null;
  confidenceScore?: number;
  trend?: string;
  riskTierLabel?: string;
  // ⭐ ADD THIS:
  stockScore?: {
    totalScore: number;
    recommendation: 'STRONG BUY' | 'BUY' | 'HOLD' | 'SELL' | 'STRONG SELL';
    riskLevel: 'Low' | 'Low-Moderate' | 'Moderate' | 'High' | 'Very High';
    scores: {
      trend: { score: number; maxScore: number; emoji: '🟢' | '🟡' | '🔴'; details: string[] };
      momentum: { score: number; maxScore: number; emoji: '🟢' | '🟡' | '🔴'; details: string[] };
      volume: { score: number; maxScore: number; emoji: '🟢' | '🟡' | '🔴'; details: string[] };
      valuation: { score: number; maxScore: number; emoji: '🟢' | '🟡' | '🔴'; details: string[] };
      fundamentals: { score: number; maxScore: number; emoji: '🟢' | '🟡' | '🔴'; details: string[] };
      risk: { score: number; maxScore: number; emoji: '🟢' | '🟡' | '🔴'; details: string[] };
      market: { score: number; maxScore: number; emoji: '🟢' | '🟡' | '🔴'; details: string[] };
    };
    explanation: string;
  };
}

/* ── Section helpers ──────────────────────────── */
const Section = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => (
  <div className={`py-3 ${className}`} style={{ pageBreakInside: "avoid", breakInside: "avoid" }}>
    {children}
  </div>
);

const SectionTitle = ({ children }: { children: React.ReactNode }) => (
  <h3
    className="text-[13px] font-bold tracking-wide uppercase pb-1.5 mb-2"
    style={{
      fontFamily: "'Playfair Display', Georgia, 'Times New Roman', serif",
      color: "#1e293b",
      borderBottom: "2px solid #1e293b",
    }}
  >
    {children}
  </h3>
);

interface Props {
  report: ReportData;
  lang: LangKey;
  inWatchlist: boolean;
  onAddWatchlist: () => void;
  onSpeakAnalysis?: () => void;
  isSpeaking?: boolean;
}

const StockReport = ({ report, lang, inWatchlist, onAddWatchlist }: Props) => {
  // Normalize language - handle any possible language value
  const normalizedLang = ((): LangKey => {
    if (lang === 'en' || lang === 'zh-TW' || lang === 'zh-CN') return lang;
    if (lang === 'tc' || lang === 'tw' || lang === 'zh' || lang === 'zh_TW' || lang === 'zh_HK' || lang === 'zh-HK') return 'zh-TW';
    if (lang === 'sc' || lang === 'cn' || lang === 'zh_CN') return 'zh-CN';
    return 'en';
  })();

  const l = translations[normalizedLang] || translations.en;
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const [isCopied, setIsCopied] = useState(false);
  const [isReading, setIsReading] = useState(false);
  const [voiceText, setVoiceText] = useState('');
  const { speak, stop, isSpeaking: speechIsSpeaking, isSupported } = useSpeech({
    lang: normalizedLang === 'zh-TW' ? 'zh-HK' : normalizedLang === 'zh-CN' ? 'zh-CN' : 'en-US',
    rate: 0.9,
  });

  const conservativeAdvice = report.conservativeAdvice && report.conservativeAdvice !== 'N/A'
    ? report.conservativeAdvice
    : l.noAdvice;

  const valueAdvice = report.valueAdvice && report.valueAdvice !== 'N/A'
    ? report.valueAdvice
    : l.noValueAdvice;

  const currencySymbol = report.currencySymbol || '$';

  // ── Generate Voice Text with 8 Sections ──
const generateVoiceText = (): string => {
  const isChinese = normalizedLang === 'zh-TW' || normalizedLang === 'zh-CN';
  const isTraditional = normalizedLang === 'zh-TW';
  const parts: string[] = [];

  const getChineseTextLocal = (traditional: string, simplified: string) => {
    return isTraditional ? traditional : simplified;
  };

  const getRsiStatusTranslation = (status: string): string => {
    if (!isChinese) return status;
    const chineseStatuses = ['超買', '超买', '超賣', '超卖', '中性'];
    if (chineseStatuses.some(s => status === s || status.includes(s))) {
      return status;
    }
    const statusMap: Record<string, string> = {
      'Overbought': getChineseTextLocal('超買', '超买'),
      'Oversold': getChineseTextLocal('超賣', '超卖'),
      'Neutral': getChineseTextLocal('中性', '中性'),
    };
    return statusMap[status] || status;
  };

  const getMacdStatusTranslation = (status: string): string => {
    if (!isChinese) return status;
    const chineseStatuses = ['看好', '看淡', '中性'];
    if (chineseStatuses.some(s => status === s || status.includes(s))) {
      return status;
    }
    const statusMap: Record<string, string> = {
      'Bullish': getChineseTextLocal('看好', '看好'),
      'Bearish': getChineseTextLocal('看淡', '看淡'),
      'Neutral': getChineseTextLocal('中性', '中性'),
    };
    return statusMap[status] || status;
  };

  const getRecommendationTranslation = (rec: string): string => {
    if (!isChinese) return rec;
    const chineseRecs = ['買入', '买入', '持有', '賣出', '卖出', '強烈買入', '强烈买入', '強烈賣出', '强烈卖出'];
    if (chineseRecs.some(s => rec === s || rec.includes(s))) {
      return rec;
    }
    const recMap: Record<string, string> = {
      'Buy': getChineseTextLocal('買入', '买入'),
      'Hold': getChineseTextLocal('持有', '持有'),
      'Sell': getChineseTextLocal('賣出', '卖出'),
      'Strong Buy': getChineseTextLocal('強烈買入', '强烈买入'),
      'Strong Sell': getChineseTextLocal('強烈賣出', '强烈卖出'),
    };
    return recMap[rec] || rec;
  };

  const getSentimentTranslation = (sentiment: string): string => {
    if (!isChinese) return sentiment;
    const sentimentMap: Record<string, string> = {
      'positive': getChineseTextLocal('正面', '正面'),
      'neutral': getChineseTextLocal('中性', '中性'),
      'negative': getChineseTextLocal('負面', '负面'),
    };
    return sentimentMap[sentiment] || sentiment;
  };

  const rsiStatusTranslated = getRsiStatusTranslation(report.rsiStatus);
  const macdStatusTranslated = getMacdStatusTranslation(report.macdStatus);
  const recommendationTranslated = getRecommendationTranslation(report.recommendation);
  
  const sentimentText = report.sentimentScore > 60 
    ? getSentimentTranslation('positive')
    : report.sentimentScore > 40 
      ? getSentimentTranslation('neutral')
      : getSentimentTranslation('negative');

  const riskLevel = report.volatility.includes('High') 
    ? (isChinese ? getChineseTextLocal('高', '高') : 'High')
    : report.volatility.includes('Moderate') 
      ? (isChinese ? getChineseTextLocal('中等', '中等') : 'Moderate')
      : (isChinese ? getChineseTextLocal('低', '低') : 'Low');
  
  const riskTier = isChinese 
    ? getChineseTextLocal(report.riskTierLabel || '中等', report.riskTierLabel || '中等')
    : (report.riskTierLabel || 'Moderate');

  const bullText = report.bullPoints?.slice(0, 2).join(isChinese ? '；' : '; ') 
    || (isChinese 
      ? getChineseTextLocal('看好因素包括技術面改善和市場情緒向好', '看好因素包括技术面改善和市场情绪向好') 
      : 'Bullish factors include improving technicals and positive market sentiment.');

  const bearText = report.bearPoints?.slice(0, 2).join(isChinese ? '；' : '; ') 
    || (isChinese 
      ? getChineseTextLocal('看淡因素包括宏觀不確定性和行業競爭加劇', '看淡因素包括宏观不确定性和行业竞争加剧') 
      : 'Bearish factors include macro uncertainty and increasing competition.');

  const selfDecisionText = isChinese
    ? getChineseTextLocal('自主決策原則', '自主决策原则')
    : 'Principle of Self-Decision';

  // ── Section 1: Summary ──
  parts.push(isChinese
    ? `${l.voiceSummary}：${report.companyName || report.ticker} 目前價格 ${report.price}，${report.priceUp ? '上漲' : '下跌'} ${report.priceChange}。AI 預測概率 ${report.probability}%，${recommendationTranslated} 信號。當前價格相對於 52週高點 ${report.weekHigh} 和 52週低點 ${report.weekLow}，處於中間區間。`
    : `${l.voiceSummary}: ${report.companyName || report.ticker} is currently trading at ${report.price}, ${report.priceUp ? 'up' : 'down'} ${report.priceChange}. AI probability is ${report.probability}% with a ${report.recommendation} signal. The current price is trading between the 52-week high of ${report.weekHigh} and 52-week low of ${report.weekLow}.`
  );

  // ── Section 2: Technical Analysis ──
  parts.push(isChinese
    ? `${l.voiceTechnical}：RSI(14) 指標為 ${report.rsi.toFixed(1)}，${rsiStatusTranslated} 區間。${rsiStatusTranslated === '超賣' ? '這表示股票可能被低估，存在反彈潛力。' : rsiStatusTranslated === '超買' ? '這表示股票可能被高估，存在回調風險。' : '這表示市場動能處於平衡狀態。'} MACD 指標顯示 ${macdStatusTranslated} 信號，${macdStatusTranslated === '看好' ? '表示多頭動能正在增強。' : macdStatusTranslated === '看淡' ? '表示空頭動能正在增強。' : '表示趨勢方向不明確。'} 成交量為 ${report.volume}，市場參與度${parseFloat(report.volume) > 1000000 ? '較高' : '一般'}。`
    : `${l.voiceTechnical}: The RSI(14) is at ${report.rsi.toFixed(1)}, indicating ${report.rsiStatus} conditions. ${report.rsiStatus === 'Oversold' ? 'This suggests the stock may be undervalued with potential for a rebound.' : report.rsiStatus === 'Overbought' ? 'This suggests the stock may be overvalued with potential for a pullback.' : 'This indicates balanced momentum.'} The MACD indicator shows a ${report.macdStatus} signal, ${report.macdStatus === 'Bullish' ? 'indicating bullish momentum is increasing.' : report.macdStatus === 'Bearish' ? 'indicating bearish momentum is increasing.' : 'indicating the trend direction is unclear.'} Volume is ${report.volume}, showing ${parseFloat(report.volume) > 1000000 ? 'strong' : 'moderate'} market participation.`
  );

  // ── Section 3: Fundamental Analysis ──
  parts.push(isChinese
    ? `${l.voiceFundamental}：公司市值 ${report.marketCap}，市盈率 ${report.peRatio}，股本回報率 ${report.roe}%。${parseFloat(report.roe) > 15 ? '股本回報率高於 15%，顯示公司盈利能力強勁。' : parseFloat(report.roe) > 8 ? '股本回報率在 8-15% 之間，顯示公司盈利能力穩定。' : '股本回報率低於 8%，顯示公司盈利能力有待改善。'} 股息收益率 ${report.dividendYield}，${report.dividendYield === '不派息' ? '公司目前不派發股息，可能將利潤用於再投資。' : '提供穩定的現金回報。'}`
    : `${l.voiceFundamental}: The company has a market cap of ${report.marketCap}, P/E ratio of ${report.peRatio}, and ROE of ${report.roe}%. ${parseFloat(report.roe) > 15 ? 'An ROE above 15% indicates strong profitability.' : parseFloat(report.roe) > 8 ? 'An ROE between 8-15% indicates stable profitability.' : 'An ROE below 8% indicates profitability needs improvement.'} The dividend yield is ${report.dividendYield}, ${report.dividendYield === 'No Dividends' ? 'the company currently does not pay dividends, likely reinvesting profits for growth.' : 'providing stable cash returns.'}`
  );

  // ── Section 4: News Sentiment ──
  parts.push(isChinese
    ? `${l.voiceSentiment}：整體市場情緒為 ${sentimentText}，信心指數 ${report.sentimentScore}%。${report.sentimentScore > 60 ? '市場對該股票持樂觀態度，正面新聞佔主導。' : report.sentimentScore > 40 ? '市場情緒中性，正面和負面新聞相對平衡。' : '市場對該股票持悲觀態度，負面新聞較多。'} 技術趨勢強度為 ${report.trendStrength}%，${report.trendStrength > 60 ? '顯示強勁趨勢動能。' : report.trendStrength > 40 ? '顯示溫和趨勢動能。' : '顯示趨勢動能較弱。'}`
    : `${l.voiceSentiment}: Overall market sentiment is ${sentimentText} with a confidence score of ${report.sentimentScore}%. ${report.sentimentScore > 60 ? 'The market is optimistic about this stock with positive news dominating.' : report.sentimentScore > 40 ? 'Market sentiment is neutral with balanced positive and negative news.' : 'The market is pessimistic about this stock with negative news prevailing.'} The technical trend strength is ${report.trendStrength}%, ${report.trendStrength > 60 ? 'indicating strong trend momentum.' : report.trendStrength > 40 ? 'indicating moderate trend momentum.' : 'indicating weak trend momentum.'}`
  );

  // ── Section 5: Risk Analysis ──
  parts.push(isChinese
    ? `${l.voiceRisk}：波動率為 ${riskLevel}，風險等級 ${riskTier}。${riskLevel === '高' ? '高波動率表示價格波動較大，風險較高，適合風險承受能力較強的投資者。' : riskLevel === '中等' ? '中等波動率表示價格波動適中，風險可控，適合大多數投資者。' : '低波動率表示價格波動較小，風險較低，適合保守型投資者。'} ${report.riskAssessment?.market?.length > 0 ? `市場風險包括：${report.riskAssessment.market.slice(0, 2).join('；')}` : ''}`
    : `${l.voiceRisk}: Volatility is ${riskLevel} with a ${riskTier} risk tier. ${riskLevel === 'High' ? 'High volatility indicates larger price swings, higher risk, suitable for risk-tolerant investors.' : riskLevel === 'Moderate' ? 'Moderate volatility indicates balanced price movements, manageable risk for most investors.' : 'Low volatility indicates smaller price swings, lower risk suitable for conservative investors.'} ${report.riskAssessment?.market?.length > 0 ? `Market risks include: ${report.riskAssessment.market.slice(0, 2).join('; ')}` : ''}`
  );

  // ── Section 6: Bull Case ──
  parts.push(isChinese
    ? `${l.voiceBull}：${bullText}${report.bullPoints?.length > 2 ? ` 此外，${report.bullPoints.slice(2).join('；')}` : ''} 整體來看，${report.probability > 60 ? 'AI模型顯示較高的上漲概率，看好因素較多。' : report.probability > 40 ? 'AI模型顯示中性概率，看好因素和看淡因素相對平衡。' : 'AI模型顯示較低的上漲概率，看淡因素較多。'}`
    : `${l.voiceBull}: ${bullText}${report.bullPoints?.length > 2 ? ` Additionally, ${report.bullPoints.slice(2).join('; ')}` : ''} Overall, ${report.probability > 60 ? 'the AI model shows a high probability of upside with more bullish factors.' : report.probability > 40 ? 'the AI model shows a neutral probability with balanced bullish and bearish factors.' : 'the AI model shows a low probability of upside with more bearish factors.'}`
  );

  // ── Section 7: Bear Case ──
  parts.push(isChinese
    ? `${l.voiceBear}：${bearText}${report.bearPoints?.length > 2 ? ` 此外，${report.bearPoints.slice(2).join('；')}` : ''} ${report.sellPct > 30 ? '賣出信號佔比較高，需謹慎評估風險。' : '賣出信號佔比適中，風險相對可控。'}`
    : `${l.voiceBear}: ${bearText}${report.bearPoints?.length > 2 ? ` Additionally, ${report.bearPoints.slice(2).join('; ')}` : ''} ${report.sellPct > 30 ? 'Sell signals are relatively high, requiring careful risk assessment.' : 'Sell signals are moderate, with relatively manageable risk.'}`
  );

  // ── Section 8: Final Recommendation ──
  parts.push(isChinese
    ? `${l.voiceFinal}：基於 AI 模型分析，${recommendationTranslated} 建議。目標價 ${report.buyTarget}，止蝕位 ${report.sellTarget}。${report.buyPct > 50 ? '買入信號佔比超過 50%，建議積極考慮。' : report.holdPct > 40 ? '持有信號佔比最高，建議保持觀望。' : '賣出信號佔比較高，建議謹慎操作。'} ${selfDecisionText}：所有投資決策應基於個人風險承受能力和財務狀況。`
    : `${l.voiceFinal}: Based on AI model analysis, the recommendation is ${report.recommendation}. The target price is ${report.buyTarget} with a stop loss at ${report.sellTarget}. ${report.buyPct > 50 ? 'Buy signals exceed 50%, suggesting active consideration.' : report.holdPct > 40 ? 'Hold signals are dominant, suggesting a wait-and-see approach.' : 'Sell signals are relatively high, suggesting caution.'} ${selfDecisionText}: All investment decisions should be based on individual risk tolerance and financial situation.`
  );

  // ── Disclaimer ──
  const disclaimer = isChinese
    ? '免責聲明：此分析由 DragonGPAI.com 生成，僅供參考。股票選擇遵循自主決策原則，投資前請諮詢專業持牌顧問。'
    : 'Disclaimer: This analysis is generated by DragonGPAI.com for reference only. Stock selection follows the principle of self-decision. Please consult a licensed professional advisor before investing.';

  // Join all sections with appropriate separators
  const fullText = parts.join(isChinese ? '。 ' : '. ') + (isChinese ? '。 ' : '. ') + disclaimer;

  return fullText;
};

  // ── Handle Voice Play ──
  const handleSpeakAnalysis = () => {
    if (speechIsSpeaking || isReading) {
      stop();
      setIsReading(false);
      return;
    }
    setIsReading(true);
    const text = generateVoiceText();
    setVoiceText(text);
    speak(text);
    setTimeout(() => {
      setIsReading(false);
    }, Math.min(text.length * 80, 30000));
  };

  // ── Auto-play useEffect ──
  useEffect(() => {
    const timer = setTimeout(() => {
      const text = generateVoiceText();
      setVoiceText(text);
      speak(text);
      setIsReading(true);
      
      setTimeout(() => {
        setIsReading(false);
      }, Math.min(text.length * 80, 30000));
    }, 1500);
    
    return () => {
      clearTimeout(timer);
      stop();
    };
  }, [report]);

  // ── Share Text Generation ──
  const getShareText = (includeFullAnalysis: boolean = false) => {
    const isChinese = normalizedLang === 'zh-TW' || normalizedLang === 'zh-CN';
    const isTraditional = normalizedLang === 'zh-TW';
    const companyName = report.companyName || report.ticker || 'N/A';
    const ticker = report.ticker || 'N/A';
    const price = report.price || 'N/A';
    const change = report.priceChange || '0.00%';
    const rsi = report.rsi !== undefined ? report.rsi.toFixed(1) : 'N/A';
    const rsiStatus = report.rsiStatus || 'Neutral';
    const probability = report.probability !== undefined ? report.probability : 50;
    const recommendation = report.recommendation || 'HOLD';
    const buyTarget = report.buyTarget || 'N/A';
    const sellTarget = report.sellTarget || 'N/A';
    const weekHigh = report.weekHigh || 'N/A';
    const weekLow = report.weekLow || 'N/A';

    const getChineseTextLocal = (traditional: string, simplified: string) => {
      return isTraditional ? traditional : simplified;
    };

    const getRsiForShare = (status: string): string => {
      if (!isChinese) return status;
      const chineseStatuses = ['超買', '超买', '超賣', '超卖', '中性'];
      if (chineseStatuses.some(s => status === s || status.includes(s))) {
        return status;
      }
      const statusMap: Record<string, string> = {
        'Overbought': getChineseTextLocal('超買', '超买'),
        'Oversold': getChineseTextLocal('超賣', '超卖'),
        'Neutral': getChineseTextLocal('中性', '中性'),
      };
      return statusMap[status] || status;
    };

    const getRecForShare = (rec: string): string => {
      if (!isChinese) return rec;
      const chineseRecs = ['買入', '买入', '持有', '賣出', '卖出', '強烈買入', '强烈买入', '強烈賣出', '强烈卖出'];
      if (chineseRecs.some(s => rec === s || rec.includes(s))) {
        return rec;
      }
      const recMap: Record<string, string> = {
        'Buy': getChineseTextLocal('買入', '买入'),
        'Hold': getChineseTextLocal('持有', '持有'),
        'Sell': getChineseTextLocal('賣出', '卖出'),
      };
      return recMap[rec] || rec;
    };

    const rsiStatusTranslated = getRsiForShare(rsiStatus);
    const recommendationTranslated = getRecForShare(recommendation);

    const parts = [
      isChinese 
        ? `📊 ${getChineseTextLocal('今日關注', '今日关注')}：${companyName} (${ticker})` 
        : `📊 Stock Watch: ${companyName} (${ticker})`,
      isChinese 
        ? `💰 ${getChineseTextLocal('股價', '股价')} ${price} (${change})` 
        : `💰 Price ${price} (${change})`,
      isChinese 
        ? `📈 RSI(14) ${rsi} (${rsiStatusTranslated})` 
        : `📈 RSI(14) ${rsi} (${rsiStatus})`,
      isChinese 
        ? `🎯 AI ${getChineseTextLocal('預測概率', '预测概率')} ${probability}%` 
        : `🎯 AI Probability ${probability}%`,
      isChinese 
        ? `💡 AI ${getChineseTextLocal('建議', '建议')} ${recommendationTranslated}` 
        : `💡 AI Recommendation ${recommendation}`,
      isChinese 
        ? `🎯 ${getChineseTextLocal('目標價', '目标价')} ${buyTarget} | ${getChineseTextLocal('止蝕位', '止损位')} ${sellTarget}` 
        : `🎯 Target ${buyTarget} | Stop Loss ${sellTarget}`,
      isChinese 
        ? `📆 52${getChineseTextLocal('週', '周')}${getChineseTextLocal('區間', '区间')} ${weekLow} - ${weekHigh}` 
        : `📆 52-week Range ${weekLow} - ${weekHigh}`,
      '',
      isChinese 
        ? `⚡ ${getChineseTextLocal('由 DragonGP.AI 提供 AI 分析', '由 DragonGP.AI 提供 AI 分析')}` 
        : `⚡ Powered by DragonGP.AI`,
      isChinese 
        ? `🔗 ${getChineseTextLocal('了解更多', '了解更多')}：https://www.dragongpai.com/ai-stocks?symbol=${ticker}` 
        : `🔗 Learn more: https://www.dragongpai.com/ai-stocks?symbol=${ticker}`
    ];

    if (includeFullAnalysis && voiceText) {
      parts.push('');
      parts.push('📝 ' + (isChinese ? getChineseTextLocal('完整分析', '完整分析') : 'Full Analysis:'));
      parts.push(voiceText);
    }

    return parts.join('\n');
  };

  // ── Share Handlers ──
  const handleFacebookShare = () => {
    const voiceContent = voiceText || generateVoiceText();
    const isChinese = normalizedLang === 'zh-TW' || normalizedLang === 'zh-CN';
    const isTraditional = normalizedLang === 'zh-TW';
    const companyName = report.companyName || report.ticker || 'N/A';
    const ticker = report.ticker || 'N/A';
    
    const getChineseTextLocal = (traditional: string, simplified: string) => {
      return isTraditional ? traditional : simplified;
    };

    const truncatedVoice = voiceContent.length > 1000 ? voiceContent.substring(0, 997) + '...' : voiceContent;
    
    const shareText = isChinese
      ? `${getChineseTextLocal('📊 今日關注', '📊 今日关注')}：${companyName} (${ticker})\n\n${truncatedVoice}\n\n${getChineseTextLocal('由 DragonGP.AI 提供 AI 分析', '由 DragonGP.AI 提供 AI 分析')}\n🔗 https://www.dragongpai.com/ai-stocks?symbol=${ticker}`
      : `📊 Stock Watch: ${companyName} (${ticker})\n\n${truncatedVoice}\n\nPowered by DragonGP.AI\n🔗 https://www.dragongpai.com/ai-stocks?symbol=${ticker}`;

    const encodedText = encodeURIComponent(shareText);
    const shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(`https://www.dragongpai.com/ai-stocks?symbol=${ticker}`)}&quote=${encodedText}`;
    window.open(shareUrl, 'facebook-share-dialog', 'width=626,height=436,toolbar=0,menubar=0,scrollbars=yes');
  };

  const handleWhatsAppShare = () => {
    const voiceContent = voiceText || generateVoiceText();
    const isChinese = normalizedLang === 'zh-TW' || normalizedLang === 'zh-CN';
    const isTraditional = normalizedLang === 'zh-TW';
    const companyName = report.companyName || report.ticker || 'N/A';
    const ticker = report.ticker || 'N/A';
    const price = report.price || 'N/A';
    const change = report.priceChange || '0.00%';
    const probability = report.probability !== undefined ? report.probability : 50;
    const recommendation = report.recommendation || 'HOLD';
    const rsi = report.rsi !== undefined ? report.rsi.toFixed(1) : 'N/A';
    const rsiStatus = report.rsiStatus || 'Neutral';
    
    const getChineseTextLocal = (traditional: string, simplified: string) => {
      return isTraditional ? traditional : simplified;
    };

    const getRsiForShare = (status: string): string => {
      if (!isChinese) return status;
      const chineseStatuses = ['超買', '超买', '超賣', '超卖', '中性'];
      if (chineseStatuses.some(s => status === s || status.includes(s))) {
        return status;
      }
      const statusMap: Record<string, string> = {
        'Overbought': getChineseTextLocal('超買', '超买'),
        'Oversold': getChineseTextLocal('超賣', '超卖'),
        'Neutral': getChineseTextLocal('中性', '中性'),
      };
      return statusMap[status] || status;
    };

    const getRecForShare = (rec: string): string => {
      if (!isChinese) return rec;
      const chineseRecs = ['買入', '买入', '持有', '賣出', '卖出', '強烈買入', '强烈买入', '強烈賣出', '强烈卖出'];
      if (chineseRecs.some(s => rec === s || rec.includes(s))) {
        return rec;
      }
      const recMap: Record<string, string> = {
        'Buy': getChineseTextLocal('買入', '买入'),
        'Hold': getChineseTextLocal('持有', '持有'),
        'Sell': getChineseTextLocal('賣出', '卖出'),
      };
      return recMap[rec] || rec;
    };

    const rsiStatusTranslated = getRsiForShare(rsiStatus);
    const recommendationTranslated = getRecForShare(recommendation);

    const truncatedVoice = voiceContent.length > 2000 ? voiceContent.substring(0, 1997) + '...' : voiceContent;
    
    const shareText = isChinese 
      ? `📊 ${getChineseTextLocal('今日關注', '今日关注')}：${companyName} (${ticker})
💰 ${getChineseTextLocal('股價', '股价')} ${price} (${change})
📈 RSI(14) ${rsi} (${rsiStatusTranslated})
🎯 AI ${getChineseTextLocal('預測概率', '预测概率')} ${probability}%
💡 AI ${getChineseTextLocal('建議', '建议')} ${recommendationTranslated}

📝 ${getChineseTextLocal('完整分析', '完整分析')}：
${truncatedVoice}

⚡ ${getChineseTextLocal('由 DragonGPAI.com 提供 AI 分析', '由 DragonGPAI.com 提供 AI 分析')}
🔗 https://www.dragongpai.com/ai-stocks?symbol=${ticker}`
      : `📊 Stock Watch: ${companyName} (${ticker})
💰 Price ${price} (${change})
📈 RSI(14) ${rsi} (${rsiStatus})
🎯 AI Probability ${probability}%
💡 AI Recommendation ${recommendation}

📝 Full Analysis:
${truncatedVoice}

⚡ Powered by DragonGPAI.com
🔗 https://www.dragongpai.com/ai-stocks?symbol=${ticker}`;

    const encodedText = encodeURIComponent(shareText);
    const whatsappUrl = `https://wa.me/?text=${encodedText}`;
    window.open(whatsappUrl, '_blank');
  };

  const handleTwitterShare = () => {
    const voiceContent = voiceText || generateVoiceText();
    const isChinese = normalizedLang === 'zh-TW' || normalizedLang === 'zh-CN';
    const isTraditional = normalizedLang === 'zh-TW';
    const companyName = report.companyName || report.ticker || 'N/A';
    const ticker = report.ticker || 'N/A';
    
    const getChineseTextLocal = (traditional: string, simplified: string) => {
      return isTraditional ? traditional : simplified;
    };

    const shortContent = voiceContent.substring(0, 80) + (voiceContent.length > 80 ? '...' : '');
    const shareText = isChinese
      ? `📊 ${companyName} ${getChineseTextLocal('AI分析', 'AI分析')}：${shortContent} ${getChineseTextLocal('由 DragonGPAI.com 提供', '由 DragonGPAI.com 提供')}`
      : `📊 ${companyName} AI Analysis: ${shortContent} Powered by DragonGPAI.com`;
    
    const encodedText = encodeURIComponent(shareText);
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodedText}&url=${encodeURIComponent(`https://www.dragongpai.com/ai-stocks?symbol=${ticker}`)}`;
    window.open(twitterUrl, '_blank');
  };

  const handleLinkedInShare = () => {
    const voiceContent = voiceText || generateVoiceText();
    const isChinese = normalizedLang === 'zh-TW' || normalizedLang === 'zh-CN';
    const isTraditional = normalizedLang === 'zh-TW';
    const companyName = report.companyName || report.ticker || 'N/A';
    const ticker = report.ticker || 'N/A';
    
    const getChineseTextLocal = (traditional: string, simplified: string) => {
      return isTraditional ? traditional : simplified;
    };

    const shareText = isChinese
      ? `${companyName} (${report.ticker}) ${getChineseTextLocal('AI分析報告', 'AI分析报告')}\n\n${voiceContent}\n\n${getChineseTextLocal('由 DragonGPAI.com 提供', '由 DragonGPAI.com 提供')}\nhttps://www.dragongpai.com/ai-stocks?symbol=${ticker}`
      : `${companyName} (${report.ticker}) AI Analysis Report\n\n${voiceContent}\n\nPowered by DragonGPAI.com\nhttps://www.dragongpai.com/ai-stocks?symbol=${ticker}`;
    
    const encodedText = encodeURIComponent(shareText);
    const linkedinUrl = `https://www.linkedin.com/sharing/share-offsite/?summary=${encodedText}`;
    window.open(linkedinUrl, '_blank');
  };

  const handleCopyText = () => {
    const voiceContent = voiceText || generateVoiceText();
    const isChinese = normalizedLang === 'zh-TW' || normalizedLang === 'zh-CN';
    const isTraditional = normalizedLang === 'zh-TW';
    const companyName = report.companyName || report.ticker || 'N/A';
    const ticker = report.ticker || 'N/A';
    const price = report.price || 'N/A';
    const change = report.priceChange || '0.00%';
    const probability = report.probability !== undefined ? report.probability : 50;
    const recommendation = report.recommendation || 'HOLD';
    const rsi = report.rsi !== undefined ? report.rsi.toFixed(1) : 'N/A';
    const rsiStatus = report.rsiStatus || 'Neutral';
    
    const getChineseTextLocal = (traditional: string, simplified: string) => {
      return isTraditional ? traditional : simplified;
    };

    const getRsiForShare = (status: string): string => {
      if (!isChinese) return status;
      const chineseStatuses = ['超買', '超买', '超賣', '超卖', '中性'];
      if (chineseStatuses.some(s => status === s || status.includes(s))) {
        return status;
      }
      const statusMap: Record<string, string> = {
        'Overbought': getChineseTextLocal('超買', '超买'),
        'Oversold': getChineseTextLocal('超賣', '超卖'),
        'Neutral': getChineseTextLocal('中性', '中性'),
      };
      return statusMap[status] || status;
    };

    const getRecForShare = (rec: string): string => {
      if (!isChinese) return rec;
      const chineseRecs = ['買入', '买入', '持有', '賣出', '卖出', '強烈買入', '强烈买入', '強烈賣出', '强烈卖出'];
      if (chineseRecs.some(s => rec === s || rec.includes(s))) {
        return rec;
      }
      const recMap: Record<string, string> = {
        'Buy': getChineseTextLocal('買入', '买入'),
        'Hold': getChineseTextLocal('持有', '持有'),
        'Sell': getChineseTextLocal('賣出', '卖出'),
      };
      return recMap[rec] || rec;
    };

    const rsiStatusTranslated = getRsiForShare(rsiStatus);
    const recommendationTranslated = getRecForShare(recommendation);

    const shareText = isChinese 
      ? `📊 ${getChineseTextLocal('今日關注', '今日关注')}：${companyName} (${ticker})
💰 ${getChineseTextLocal('股價', '股价')} ${price} (${change})
📈 RSI(14) ${rsi} (${rsiStatusTranslated})
🎯 AI ${getChineseTextLocal('預測概率', '预测概率')} ${probability}%
💡 AI ${getChineseTextLocal('建議', '建议')} ${recommendationTranslated}

📝 ${getChineseTextLocal('完整分析', '完整分析')}：
${voiceContent}

⚡ ${getChineseTextLocal('由 DragonGPAI.com 提供 AI 分析', '由 DragonGPAI.com 提供 AI 分析')}
🔗 https://www.dragongpai.com/ai-stocks?symbol=${ticker}`
      : `📊 Stock Watch: ${companyName} (${ticker})
💰 Price ${price} (${change})
📈 RSI(14) ${rsi} (${rsiStatus})
🎯 AI Probability ${probability}%
💡 AI Recommendation ${recommendation}

📝 Full Analysis:
${voiceContent}

⚡ Powered by DragonGPAI.com
🔗 https://www.dragongpai.com/ai-stocks?symbol=${ticker}`;

    navigator.clipboard.writeText(shareText).then(() => {
      setIsCopied(true);
      toast.success(l.copied || 'Copied!');
      setTimeout(() => setIsCopied(false), 3000);
    }).catch(() => {
      toast.error('Failed to copy');
    });
  };

  // ── Print/PDF functions ──
  const handlePrint = () => {
    if (typeof window.print !== "function") {
      toast.error("Printing is not supported in this browser.", { duration: 5000 });
      return;
    }
    try {
      window.print();
    } catch (error) {
      console.error("Print failed:", error);
      toast.error("Print failed. Please try again.", { duration: 5000 });
    }
  };

  const [pdfLoading, setPdfLoading] = useState(false);

  const handleSavePDF = async () => {
    const element = document.getElementById("stock-report");
    if (!element) return;

    setPdfLoading(true);
    const loadingToast = toast.loading("Generating PDF...");

    try {
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#ffffff",
        logging: false,
        windowWidth: element.scrollWidth,
        windowHeight: element.scrollHeight,
      });

      const imgData = canvas.toDataURL('image/jpeg', 0.95);
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 5;
      const usableWidth = pageWidth - margin * 2;
      const imgAspect = canvas.height / canvas.width;
      const imgHeightInMM = usableWidth * imgAspect;

      pdf.addImage(imgData, 'JPEG', margin, margin, usableWidth, imgHeightInMM);
      pdf.save(`${report.ticker || "stock"}-AI-Report.pdf`);

      toast.dismiss(loadingToast);
      toast.success("PDF downloaded successfully!", { duration: 3000 });
    } catch (error) {
      console.error("PDF generation failed:", error);
      toast.dismiss(loadingToast);
      toast.error("Failed to generate PDF. Please try again.", { duration: 5000 });
    } finally {
      setPdfLoading(false);
    }
  };

  const handleSaveAsText = () => {
    const el = document.getElementById("stock-report");
    if (!el) return;
    const text = el.innerText;
    const blob = new Blob([text], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${report.ticker || "stock"}-report.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const handleSelectAnother = () => {
    window.location.reload();
  };

  // ── Get RSI Signal Text ──
  const getRSISignalText = (rsi: number): string => {
    if (rsi < 30) {
      return l.buySignal.replace('{value}', rsi.toFixed(1));
    } else if (rsi > 70) {
      return l.sellSignal.replace('{value}', rsi.toFixed(1));
    }
    return '';
  };

  // ── Price vs Index Chart ──
  const PriceVsIndexChart = ({ lang: chartLang, ticker, companyName }: { lang: LangKey; ticker: string; companyName?: string }) => {
    const chartLabels = {
      en: {
        title: "12-Month Price vs. Index Performance",
        stock: "Stock",
        index: "Index",
        legend: "Indexed to 100 at start of period. Past performance is not indicative of future results.",
      },
      "zh-TW": {
        title: "12個月股價 vs 指數表現",
        stock: "股票",
        index: "指數",
        legend: "以期初為基數 100 計算。過往表現並非未來表現的指標。",
      },
      "zh-CN": {
        title: "12个月股价 vs 指数表现",
        stock: "股票",
        index: "指数",
        legend: "以期初为基数 100 计算。过往表现并非未来表现的指标。",
      },
    };

    const chartNormalizedLang = ((): LangKey => {
      if (chartLang === 'en' || chartLang === 'zh-TW' || chartLang === 'zh-CN') return chartLang;
      if (chartLang === 'tc' || chartLang === 'tw' || chartLang === 'zh' || chartLang === 'zh_TW' || chartLang === 'zh_HK' || chartLang === 'zh-HK') return 'zh-TW';
      if (chartLang === 'sc' || chartLang === 'cn' || chartLang === 'zh_CN') return 'zh-CN';
      return 'en';
    })();

    const cl = chartLabels[chartNormalizedLang] || chartLabels.en;

    // Generate synthetic 12-month performance data based on ticker
    const generatePerformanceData = (tickerParam: string) => {
      // FIX: Handle undefined or empty ticker
      const safeTicker = tickerParam || 'DEFAULT';
      const months = ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb"];
      const seed = safeTicker.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
      const rng = (i: number) => Math.sin(seed * 0.1 + i * 0.7) * 0.5 + 0.5;

      let stockVal = 100;
      let indexVal = 100;

      return months.map((m, i) => {
        if (i > 0) {
          stockVal += (rng(i) - 0.4) * 8;
          indexVal += (rng(i + 50) - 0.45) * 5;
        }
        return {
          month: m,
          stock: Math.round(stockVal * 10) / 10,
          index: Math.round(indexVal * 10) / 10,
        };
      });
    };

    // Map ticker to benchmark
    const getIndexName = (tickerParam: string): string => {
      if (!tickerParam) return "S&P 500";
      if (tickerParam.endsWith(".HK")) return "HSI";
      if (tickerParam.endsWith(".TW")) return "TAIEX";
      return "S&P 500";
    };

    const safeTicker = ticker || 'DEFAULT';
    const data = generatePerformanceData(safeTicker);
    const indexName = getIndexName(safeTicker);
    const stockLabel = companyName || safeTicker;

    return (
      <div style={{ pageBreakInside: "avoid", breakInside: "avoid" }}>
        <h3
          className="text-[15px] font-bold tracking-wide uppercase pb-2 mb-4"
          style={{
            fontFamily: "'Playfair Display', Georgia, 'Times New Roman', serif",
            color: "#1e293b",
            borderBottom: "2px solid #1e293b",
          }}
        >
          {cl.title}
        </h3>

        <div
          className="rounded p-4"
          style={{ border: "1px solid #e5e7eb", background: "#fafbfc" }}
        >
          <ResponsiveContainer width="100%" height={240}>
            <LineChart data={data} margin={{ top: 5, right: 20, left: 0, bottom: 5 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
              <XAxis
                dataKey="month"
                tick={{ fontSize: 10, fill: "#94a3b8" }}
                axisLine={{ stroke: "#e2e8f0" }}
                tickLine={false}
              />
              <YAxis
                tick={{ fontSize: 10, fill: "#94a3b8" }}
                axisLine={{ stroke: "#e2e8f0" }}
                tickLine={false}
                domain={[(dataMin: number) => Math.floor(Math.min(dataMin, 95)), (dataMax: number) => Math.ceil(Math.max(dataMax, 105))]}
              />
              <Tooltip
                contentStyle={{
                  background: "#1e293b",
                  border: "none",
                  borderRadius: "4px",
                  fontSize: "11px",
                  color: "#ffffff",
                }}
                itemStyle={{ color: "#ffffff" }}
                labelStyle={{ color: "#94a3b8", fontSize: "10px" }}
              />
              <Legend
                wrapperStyle={{ fontSize: "10px", color: "#64748b" }}
                iconType="line"
              />
              <Line
                type="monotone"
                dataKey="stock"
                name={`${stockLabel} (${cl.stock})`}
                stroke="#003366"
                strokeWidth={2.5}
                dot={false}
                activeDot={{ r: 4, fill: "#003366" }}
              />
              <Line
                type="monotone"
                dataKey="index"
                name={indexName}
                stroke="#94a3b8"
                strokeWidth={1.5}
                strokeDasharray="5 3"
                dot={false}
                activeDot={{ r: 3, fill: "#94a3b8" }}
              />
            </LineChart>
          </ResponsiveContainer>
        </div>

        <p className="mt-2 text-[9px] italic leading-relaxed" style={{ color: "#94a3b8" }}>
          {cl.legend}
        </p>
      </div>
    );
  };

  // ── Report Content ──
  return (
    <div id="stock-report" className="max-w-4xl mx-auto px-4 py-6 print:px-0 print:py-0">
      {/* ── Voice Button Bar ── */}
      <div className="flex flex-wrap items-center justify-between gap-3 mb-4 print:hidden">
        <div className="flex items-center gap-2">
          <Button
            onClick={handleSpeakAnalysis}
            className={`gap-2 ${isReading || speechIsSpeaking ? 'bg-red-500 hover:bg-red-600' : 'bg-blue-600 hover:bg-blue-700'}`}
          >
            {isReading || speechIsSpeaking ? <Square className="h-4 w-4" /> : <Volume2 className="h-4 w-4" />}
            {isReading || speechIsSpeaking ? l.stop : l.readReport}
          </Button>
          {(isReading || speechIsSpeaking) && (
            <span className="text-sm text-muted-foreground animate-pulse">
              {l.speaking}
            </span>
          )}
        </div>
        <span className="text-xs text-muted-foreground">
          {normalizedLang === 'zh-TW' ? '廣東話' : normalizedLang === 'zh-CN' ? '普通話' : 'English'}
        </span>
      </div>

      {/* ── Report Header ── */}
      <div className="flex items-center gap-3 pb-3 border-b border-gray-200 print:border-gray-300">
        <img src={dragonLogo} alt="DragonGP" className="h-8 w-auto print:h-6" />
        <div className="flex-1">
          <h1 className="text-lg font-bold" style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
            {l.reportTitle}
          </h1>
          <p className="text-xs text-muted-foreground">
            {l.dateLabel}: {today}
          </p>
        </div>
        <div className="text-right text-xs text-muted-foreground">
          <span className="font-semibold">{report.ticker}</span>
          <span className="block">{l.status}</span>
        </div>
      </div>

      {/* ── Executive Thesis ── */}
      <Section>
        <SectionTitle>{l.executiveThesisTitle}</SectionTitle>
        <div className="p-4 rounded-lg bg-blue-50/50 border border-blue-100">
          <p className="text-sm leading-relaxed">{report.executiveThesis || l.noAdvice}</p>
        </div>
      </Section>

      {/* ── Market Data ── */}
      <Section>
        <SectionTitle>{l.marketData}</SectionTitle>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.livePrice}</p>
            <p className="text-lg font-bold">{currencySymbol}{report.price}</p>
            <p className={`text-xs ${report.priceUp ? 'text-green-600' : 'text-red-600'}`}>
              {report.priceChange}
            </p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.weekHigh}</p>
            <p className="text-lg font-bold text-green-600">{currencySymbol}{report.weekHigh}</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.weekLow}</p>
            <p className="text-lg font-bold text-red-600">{currencySymbol}{report.weekLow}</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.volume}</p>
            <p className="text-lg font-bold">{report.volume}</p>
          </div>
        </div>
      </Section>

      {/* ── Sector & Industry ── */}
      {(report.sector || report.industry) && (
        <div className="flex flex-wrap gap-2 py-2">
          {report.sector && (
            <span className="px-3 py-1 text-xs rounded-full bg-blue-100 text-blue-800 font-medium">
              {report.sector}
            </span>
          )}
          {report.industry && (
            <span className="px-3 py-1 text-xs rounded-full bg-purple-100 text-purple-800 font-medium">
              {report.industry}
            </span>
          )}
        </div>
      )}

      {/* ── Recommendation Sidebar ── */}
      <Section>
        <RecommendationSidebar
          lang={normalizedLang}
          currentPrice={report.price}
          targetPrice={report.buyTarget}
          buyPct={report.buyPct}
          holdPct={report.holdPct}
          sellPct={report.sellPct}
        />
      </Section>

      {/* ── AI Probability & Confidence ── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 py-3">
        <div className="flex flex-col items-center p-4 rounded-lg border border-gray-200 bg-gray-50/50">
          <p className="text-sm font-medium mb-2">{l.aiProbability}</p>
          <ProbabilityGauge value={report.probability} size={140} />
        </div>
        <div className="flex flex-col items-center p-4 rounded-lg border border-gray-200 bg-gray-50/50">
          <AnalystConfidenceGauge value={report.confidenceScore || 65} lang={normalizedLang} />
        </div>
      </div>

      {/* ── Decision Matrix ── */}
      <Section>
        <SectionTitle>{l.decisionMatrix}</SectionTitle>
        <div className="flex h-6 rounded-full overflow-hidden border border-gray-200">
          <div className="flex items-center justify-center text-white text-xs font-bold" style={{ width: `${report.buyPct}%`, background: '#15803d' }}>
            {report.buyPct > 10 ? `${report.buyPct}%` : ''}
          </div>
          <div className="flex items-center justify-center text-white text-xs font-bold" style={{ width: `${report.holdPct}%`, background: '#b45309' }}>
            {report.holdPct > 10 ? `${report.holdPct}%` : ''}
          </div>
          <div className="flex items-center justify-center text-white text-xs font-bold" style={{ width: `${report.sellPct}%`, background: '#dc2626' }}>
            {report.sellPct > 10 ? `${report.sellPct}%` : ''}
          </div>
        </div>
        <div className="flex justify-between text-xs font-medium mt-1">
          <span className="text-green-600">{l.buy} {report.buyPct}%</span>
          <span className="text-amber-600">{l.hold} {report.holdPct}%</span>
          <span className="text-red-600">{l.sell} {report.sellPct}%</span>
        </div>
      </Section>

      {/* ── AI Recommendation ── */}
      <Section>
        <SectionTitle>{l.aiRecommendation}</SectionTitle>
        <div className="p-4 rounded-lg border border-gray-200 bg-gray-50/50">
          <p className="text-sm font-medium">{report.recommendation}</p>
          {report.rsi !== undefined && getRSISignalText(report.rsi) && (
            <p className="text-xs text-muted-foreground mt-1">{getRSISignalText(report.rsi)}</p>
          )}
        </div>
      </Section>

      {/* ── Technical Indicators ── */}
      <Section>
        <SectionTitle>{l.techIndicators}</SectionTitle>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div className="p-3 rounded-lg border border-gray-200">
            <p className="text-xs font-medium">{l.rsiIndicator}</p>
            <p className="text-xl font-bold">{report.rsi.toFixed(1)}</p>
            <p className="text-xs text-muted-foreground">{report.rsiStatus}</p>
          </div>
          <div className="p-3 rounded-lg border border-gray-200">
            <p className="text-xs font-medium">{l.macdIndicator}</p>
            <p className="text-xl font-bold">{report.macdStatus}</p>
            <p className="text-xs text-muted-foreground">{report.macdLine}</p>
          </div>
          <div className="p-3 rounded-lg border border-gray-200">
            <p className="text-xs font-medium">{l.trendStrength}</p>
            <p className="text-xl font-bold">{report.trendStrength}%</p>
            <p className="text-xs text-muted-foreground">{l.sentiment}</p>
          </div>
        </div>
      </Section>

      {/* ── Price vs Index Chart ── */}
      <Section>
        <PriceVsIndexChart 
          lang={normalizedLang} 
          ticker={report.ticker || 'UNKNOWN'} 
          companyName={report.companyName} 
        />
      </Section>

      {/* ── Company Profile ── */}
      <CompanyProfile
        lang={normalizedLang}
        companyName={report.companyName || report.ticker}
        description={report.companyDescription || ''}
        sector={report.sector}
        industry={report.industry}
      />

      {/* ── Market Depth ── */}
      <MarketDepthSection
        lang={normalizedLang}
        bid={report.bid}
        ask={report.ask}
        bidSize={report.bidSize}
        askSize={report.askSize}
        dayRange={report.dayRange}
        volume={report.volume}
        marketState={report.marketState}
        currencySymbol={currencySymbol}
        previousCloseVolume={report.previousCloseVolume}
      />

      {/* ── Peer Comparison ── */}
      <PeerComparisonTable
        lang={normalizedLang}
        targetTicker={report.ticker}
        targetCompany={report.companyName || report.ticker}
        targetPrice={report.price}
        targetMarketCap={report.marketCap}
        targetPE={report.peRatio}
        targetROE={report.roe}
        targetDivYield={report.dividendYield}
      />

      {/* ── News ── */}
      <NewsSection lang={normalizedLang} news={report.news} />

      {/* ── Bull & Bear Cases ── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 py-3">
        <div className="p-4 rounded-lg border border-green-200 bg-green-50/30">
          <h4 className="text-sm font-bold text-green-700 flex items-center gap-2">
            <TrendingUp className="h-4 w-4" />
            {l.bullCase}
          </h4>
          <ul className="mt-2 space-y-1 text-sm text-gray-700">
            {report.bullPoints?.map((point, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-green-500">•</span>
                {point}
              </li>
            )) || <li>{l.noAdvice}</li>}
          </ul>
        </div>
        <div className="p-4 rounded-lg border border-red-200 bg-red-50/30">
          <h4 className="text-sm font-bold text-red-700 flex items-center gap-2">
            <TrendingDown className="h-4 w-4" />
            {l.bearCase}
          </h4>
          <ul className="mt-2 space-y-1 text-sm text-gray-700">
            {report.bearPoints?.map((point, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-red-500">•</span>
                {point}
              </li>
            )) || <li>{l.noAdvice}</li>}
          </ul>
        </div>
      </div>

      {/* ── Financial Snapshot ── */}
      <Section>
        <SectionTitle>{l.financialSnapshot}</SectionTitle>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.marketCap}</p>
            <p className="text-sm font-bold">{report.marketCap}</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.peRatio}</p>
            <p className="text-sm font-bold">{report.peRatio}</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.roeLabel}</p>
            <p className="text-sm font-bold">{report.roe}%</p>
          </div>
          <div className="p-3 text-center rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-xs text-muted-foreground">{l.dividendYield}</p>
            <p className="text-sm font-bold">{report.dividendYield}</p>
          </div>
        </div>
      </Section>

      {/* ── Risk Assessment ── */}
      <Section>
        <SectionTitle>{l.riskTitle}</SectionTitle>
        <div className="space-y-3">
          <div className="p-3 rounded-lg border border-gray-200 bg-gray-50/50">
            <p className="text-sm font-medium">{l.riskMarket}</p>
            <p className="text-xs text-muted-foreground">{l.riskMarketDesc}</p>
            <ul className="mt-1 space-y-0.5 text-xs text-gray-600">
              {report.riskAssessment?.market?.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-gray-400">•</span>
                  {item}
                </li>
              )) || <li>{l.noAdvice}</li>}
            </ul>
          </div>
          <div className="p-3 rounded-lg border border-gray-200 bg-gray-50/50">
            <p className="text-sm font-medium">{l.riskCompany}</p>
            <p className="text-xs text-muted-foreground">{l.riskCompanyDesc}</p>
            <ul className="mt-1 space-y-0.5 text-xs text-gray-600">
              {report.riskAssessment?.company?.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-gray-400">•</span>
                  {item}
                </li>
              )) || <li>{l.noAdvice}</li>}
            </ul>
          </div>
          <div className="p-3 rounded-lg border border-gray-200 bg-gray-50/50">
            <p className="text-sm font-medium">{l.riskModel}</p>
            <p className="text-xs text-muted-foreground">{l.riskModelDesc}</p>
            <ul className="mt-1 space-y-0.5 text-xs text-gray-600">
              {report.riskAssessment?.model?.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-gray-400">•</span>
                  {item}
                </li>
              )) || <li>{l.noAdvice}</li>}
            </ul>
          </div>
          <div className="p-3 rounded-lg border border-amber-200 bg-amber-50/30">
            <p className="text-sm font-medium text-amber-800">{l.riskSelfDecision}</p>
            <p className="text-xs text-amber-700">{l.riskSelfDecisionBody}</p>
          </div>
        </div>
      </Section>

      {/* ── Voice Transcript Section ── */}
      {voiceText && (
        <Section>
          <SectionTitle>{l.voiceTranscript}</SectionTitle>
          <div className="p-4 rounded-lg bg-blue-50/50 border border-blue-200 text-sm leading-relaxed whitespace-pre-wrap">
            {voiceText}
          </div>
        </Section>
      )}

      {/* ── Disclaimer ── */}
      <div className="py-3 text-xs text-muted-foreground space-y-1 border-t border-gray-200 mt-4 print:mt-2">
        <p>{l.finalDisclaimer}</p>
        <p className="text-[10px]">{l.confidential}</p>
        <p className="text-[10px]">{l.footnote1}</p>
        <p className="text-[10px]">{l.footnote2}</p>
        <p className="text-[10px]">{l.footnote3}</p>
      </div>



    </div>
  );
};

export default StockReport;