import { Shield, Activity, BarChart3, Printer, Share2, Download, ArrowLeft, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import type { LangKey } from "@/contexts/LanguageContext";
import { useToast } from "@/hooks/use-toast";
import ProbabilityGauge from "@/components/ai-stocks/ProbabilityGauge";
import SparklineChart from "@/components/ai-stocks/SparklineChart";
import { getBallColor } from "./mark6-data";

const Glass = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => (
  <div className={`rounded-xl border border-white/[0.06] bg-white/[0.03] backdrop-blur-md p-5 ${className}`}>
    {children}
  </div>
);

const labels = {
  en: {
    reportTitle: "AI Mark 6 Probability Report",
    partner: "AI Partner",
    dateLabel: "Simulation Date",
    status: "Cognitive Engagement Exercise",
    yourNumbers: "Your Selected Numbers",
    probScore: "Mathematical Probability Score",
    volatility: "Volatility Index",
    patternDensity: "Pattern Density",
    analysis: "📊 Statistical Analysis",
    oddEven: "Odd/Even Ratio",
    highLow: "High/Low Ratio",
    sumTotal: "Sum Total",
    sumRange: "Sum Range",
    optimal: "Within Optimal (91-230)",
    outside: "Outside Normal Range",
    consecutive: "Consecutive Numbers",
    yes: "Yes — detected",
    no: "None detected",
    hotCold: "🔥 Hot & Cold Analysis",
    hotNumbers: "Hot Numbers in Selection",
    coldNumbers: "Cold Numbers in Selection",
    none: "None",
    methodology: "🧠 AI Methodology",
    disclaimer: "Principle of Self-Decision",
    disclaimerText: "This report is generated by a mathematical AI model for educational and mental stimulation purposes only. The founder holds No Professional or Gambling Licenses. This does NOT predict lottery results.",
    pickAnother: "Pick Another Set",
    print: "Print",
    share: "Share",
    save: "Save as Text",
    goToStocks: "Go to AI Stocks Probability Now",
    copied: "Link copied to clipboard!",
  },
  tc: {
    reportTitle: "AI Mark 6 概率報告",
    partner: "AI 夥伴",
    dateLabel: "模擬日期",
    status: "認知參與練習",
    yourNumbers: "您選擇的號碼",
    probScore: "數學概率分數",
    volatility: "波動指數",
    patternDensity: "模式密度",
    analysis: "📊 統計分析",
    oddEven: "奇偶比",
    highLow: "大小比",
    sumTotal: "總和",
    sumRange: "總和範圍",
    optimal: "在最佳範圍內 (91-230)",
    outside: "超出正常範圍",
    consecutive: "連號",
    yes: "是 — 已檢測",
    no: "未檢測到",
    hotCold: "🔥 冷熱號碼分析",
    hotNumbers: "選擇中的熱門號碼",
    coldNumbers: "選擇中的冷門號碼",
    none: "無",
    methodology: "🧠 AI 方法論",
    disclaimer: "自主決策原則",
    disclaimerText: "本報告由數學 AI 模型生成，僅供教育和認知刺激之用。創辦人不持有任何專業或博弈牌照。此報告不能預測彩票結果。",
    pickAnother: "重新選擇",
    print: "列印",
    share: "分享",
    save: "儲存為文字",
    goToStocks: "立即前往 AI 股票概率",
    copied: "連結已複製到剪貼板！",
  },
  sc: {
    reportTitle: "AI Mark 6 概率报告",
    partner: "AI 伙伴",
    dateLabel: "模拟日期",
    status: "认知参与练习",
    yourNumbers: "您选择的号码",
    probScore: "数学概率分数",
    volatility: "波动指数",
    patternDensity: "模式密度",
    analysis: "📊 统计分析",
    oddEven: "奇偶比",
    highLow: "大小比",
    sumTotal: "总和",
    sumRange: "总和范围",
    optimal: "在最佳范围内 (91-230)",
    outside: "超出正常范围",
    consecutive: "连号",
    yes: "是 — 已检测",
    no: "未检测到",
    hotCold: "🔥 冷热号码分析",
    hotNumbers: "选择中的热门号码",
    coldNumbers: "选择中的冷门号码",
    none: "无",
    methodology: "🧠 AI 方法论",
    disclaimer: "自主决策原则",
    disclaimerText: "本报告由数学 AI 模型生成，仅供教育和认知刺激之用。创办人不持有任何专业或博弈牌照。此报告不能预测彩票结果。",
    pickAnother: "重新选择",
    print: "打印",
    share: "分享",
    save: "保存为文本",
    goToStocks: "立即前往 AI 股票概率",
    copied: "链接已复制到剪贴板！",
  },
};

interface SimResult {
  probability: number;
  volatility: number;
  patternDensity: number;
  oddEven: string;
  highLow: string;
  sum: number;
  sumRange: string;
  hasConsecutive: boolean;
  hotNumbers: number[];
  coldNumbers: number[];
}

interface Props {
  lang: LangKey;
  selectedNumbers: number[];
  partnerName: string;
  partnerMethod: string;
  result: SimResult;
  onReset: () => void;
}

const Mark6Report = ({ lang, selectedNumbers, partnerName, partnerMethod, result, onReset }: Props) => {
  const t = labels[lang];
  const { toast } = useToast();

  const handlePrint = () => window.print();
  const handleShare = async () => {
    const text = lang === "en"
      ? `My AI Mark 6 numbers: ${selectedNumbers.sort((a,b)=>a-b).join(", ")} — ${partnerName} 🐲🎯 ${window.location.origin}/ai-games`
      : lang === "tc"
        ? `我的 AI Mark 6 號碼：${selectedNumbers.sort((a,b)=>a-b).join(", ")} — ${partnerName} 🐲🎯 ${window.location.origin}/ai-games`
        : `我的 AI Mark 6 号码：${selectedNumbers.sort((a,b)=>a-b).join(", ")} — ${partnerName} 🐲🎯 ${window.location.origin}/ai-games`;
    await navigator.clipboard.writeText(text);
    toast({ title: t.copied });
  };
  const handleSave = () => {
    const el = document.getElementById("mark6-report");
    if (!el) return;
    const blob = new Blob([el.innerText], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `mark6-report-${selectedNumbers.join("-")}.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const volData = Array.from({ length: 10 }, () => Math.floor(Math.random() * 60) + 20);
  const patData = Array.from({ length: 10 }, () => Math.floor(Math.random() * 50) + 30);

  return (
    <div id="mark6-report" className="space-y-5 animate-fade-in">
      {/* Header */}
      <Glass>
        <h2 className="text-xl font-bold text-primary">{t.reportTitle}</h2>
        <p className="text-sm text-muted-foreground mt-1">
          {t.partner}: <span className="font-bold text-foreground">{partnerName}</span> — {partnerMethod}
        </p>
        <p className="text-xs text-muted-foreground">
          {t.dateLabel}: {new Date().toISOString().split("T")[0]} | {t.status}
        </p>
      </Glass>

      {/* Selected numbers */}
      <Glass>
        <h3 className="font-bold text-primary text-sm mb-3">{t.yourNumbers}</h3>
        <div className="flex items-center gap-2 justify-center flex-wrap">
          {selectedNumbers.sort((a, b) => a - b).map((n) => (
            <span key={n} className={`w-10 h-10 rounded-full ${getBallColor(n)} text-white font-bold text-sm flex items-center justify-center shadow-lg`}>
              {n}
            </span>
          ))}
        </div>
      </Glass>

      {/* Probability Gauge */}
      <Glass className="text-center">
        <h3 className="font-bold text-primary text-sm mb-4">{t.probScore}</h3>
        <div className="relative flex justify-center">
          <ProbabilityGauge value={result.probability} size={160} label="Probability" />
        </div>
      </Glass>

      {/* Volatility & Pattern Density */}
      <div className="grid grid-cols-2 gap-3">
        <Glass className="text-center">
          <Activity className="mx-auto text-amber-400 mb-1" size={20} />
          <p className="text-[10px] uppercase tracking-wider text-muted-foreground">{t.volatility}</p>
          <SparklineChart data={volData} color="#f59e0b" width={100} height={28} />
          <p className="text-2xl font-extrabold text-foreground mt-1">{result.volatility}/100</p>
        </Glass>
        <Glass className="text-center">
          <BarChart3 className="mx-auto text-emerald-400 mb-1" size={20} />
          <p className="text-[10px] uppercase tracking-wider text-muted-foreground">{t.patternDensity}</p>
          <SparklineChart data={patData} color="#22c55e" width={100} height={28} />
          <p className="text-2xl font-extrabold text-foreground mt-1">{result.patternDensity}/100</p>
        </Glass>
      </div>

      {/* Statistical Analysis */}
      <Glass>
        <h3 className="font-bold text-primary text-sm mb-3">{t.analysis}</h3>
        <div className="grid grid-cols-2 gap-3 text-sm">
          <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3 text-center">
            <p className="text-xs text-muted-foreground">{t.oddEven}</p>
            <p className="text-lg font-bold text-foreground mt-1">{result.oddEven}</p>
          </div>
          <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3 text-center">
            <p className="text-xs text-muted-foreground">{t.highLow}</p>
            <p className="text-lg font-bold text-foreground mt-1">{result.highLow}</p>
          </div>
          <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3 text-center">
            <p className="text-xs text-muted-foreground">{t.sumTotal}</p>
            <p className="text-lg font-bold text-foreground mt-1">{result.sum}</p>
          </div>
          <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3 text-center">
            <p className="text-xs text-muted-foreground">{t.consecutive}</p>
            <p className={`text-lg font-bold mt-1 ${result.hasConsecutive ? "text-emerald-400" : "text-muted-foreground"}`}>
              {result.hasConsecutive ? t.yes : t.no}
            </p>
          </div>
        </div>
        <div className={`mt-3 rounded-lg p-2 text-center text-xs font-semibold ${result.sumRange === "optimal" ? "border border-emerald-500/20 bg-emerald-500/5 text-emerald-400" : "border border-red-500/20 bg-red-500/5 text-red-400"}`}>
          {t.sumRange}: {result.sumRange === "optimal" ? t.optimal : t.outside}
        </div>
      </Glass>

      {/* Hot & Cold */}
      <Glass>
        <h3 className="font-bold text-primary text-sm mb-3">{t.hotCold}</h3>
        <div className="grid grid-cols-2 gap-3">
          <div className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
            <p className="text-xs text-muted-foreground mb-2">{t.hotNumbers}</p>
            <div className="flex gap-1 flex-wrap">
              {result.hotNumbers.length > 0
                ? result.hotNumbers.map((n) => (
                    <span key={n} className="w-8 h-8 rounded-full bg-red-500 text-white text-xs font-bold flex items-center justify-center">{n}</span>
                  ))
                : <span className="text-muted-foreground text-xs">{t.none}</span>}
            </div>
          </div>
          <div className="rounded-lg border border-blue-500/20 bg-blue-500/5 p-3">
            <p className="text-xs text-muted-foreground mb-2">{t.coldNumbers}</p>
            <div className="flex gap-1 flex-wrap">
              {result.coldNumbers.length > 0
                ? result.coldNumbers.map((n) => (
                    <span key={n} className="w-8 h-8 rounded-full bg-blue-500 text-white text-xs font-bold flex items-center justify-center">{n}</span>
                  ))
                : <span className="text-muted-foreground text-xs">{t.none}</span>}
            </div>
          </div>
        </div>
      </Glass>

      {/* Disclaimer */}
      <div className="rounded-xl border border-primary/30 bg-card/50 p-4 flex items-start gap-3">
        <Shield className="text-primary shrink-0 mt-0.5" size={18} />
        <div className="text-xs text-muted-foreground leading-relaxed">
          <span className="font-bold text-foreground">{t.disclaimer}:</span> {t.disclaimerText}
        </div>
      </div>

      {/* Action Bar */}
      <div className="space-y-3 pt-2">
        <div className="flex flex-wrap items-center justify-center gap-3">
          <button onClick={onReset} className="inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-sm font-semibold bg-primary text-primary-foreground hover:bg-primary/90 transition-colors">
            <ArrowLeft size={16} /> {t.pickAnother}
          </button>
          <button onClick={handlePrint} className="inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-sm font-semibold border border-border text-muted-foreground hover:text-foreground hover:border-primary/50 transition-colors">
            <Printer size={16} /> {t.print}
          </button>
          <button onClick={handleShare} className="inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-sm font-semibold border border-border text-muted-foreground hover:text-foreground hover:border-primary/50 transition-colors">
            <Share2 size={16} /> {t.share}
          </button>
        </div>
        <div className="flex justify-center">
          <button onClick={handleSave} className="inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-sm font-semibold border border-border text-muted-foreground hover:text-foreground hover:border-primary/50 transition-colors">
            <Download size={16} /> {t.save}
          </button>
        </div>
        <Link
          to="/ai-stocks"
          className="block w-full max-w-2xl mx-auto rounded-xl bg-gradient-to-r from-primary to-amber-500 py-4 text-center text-sm font-bold text-primary-foreground hover:from-primary/90 hover:to-amber-400 transition-colors"
        >
          <TrendingUp size={16} className="inline mr-2" />
          {t.goToStocks}
        </Link>
      </div>
    </div>
  );
};

export default Mark6Report;
